### ISSUE TITLE
Very tiny doc error

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#1001]
At: [https://docs.microsoft.com/en-us/office/vba/api/office.iribbonui]
In the following example, a dot is placed after (...)?"
(…) and search for "How can I determine the correct signatures for each callback **procedure?".**

I am not sure what applies to American-English grammar, but to Dutch grammar, if a quote concludes a sentence, no extra point is used to close the sentence.

It's a small matter, but perhaps also a good tip if this happens more often.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks, Peter. I moved the string to the middle of the sentence so we didn't have to deal with double punctuation. Changes will be live later today.

For information about the callback functions available for each UI element, search for "How can I determine the correct signatures for each callback procedure?" in [Customizing the 2007 Office Fluent Ribbon for Developers](https://docs.microsoft.com/previous-versions/office/developer/office-2007/aa722523(v=office.12)).

**Comment by PeterVanLoosbroek** [comment]
OK Linda. I respect you because you have an open mind to improve even such small things.
