### ISSUE TITLE
Code  errors, easy to fix

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#1004]
**Case 1**
https://docs.microsoft.com/en-us/office/vba/api/office.iribbonui
In the example XML the following code generates an error because the attribute OnLoad is not declared. Thus, OnLoad should be onLoad. (All attributes in the Ribbon XML customization markup use the camel-casing convention, which capitalizes the first character of each word except the first word.)
Just one little letter can cause al lot of problems. People search for hours and wonder: "How is it possible that my Ribbons don't work? I do everything exactly as the example."

Wrong: <customUI … OnLoad="MyAddInInitialize" …>
Correct: <customUI … onLoad="MyAddInInitialize" …>

Change on this page also:
Dim MyRibbon As IRibbonUI
to:
Public MyRibbon As IRibbonUI
(Dim is possible, but Public better, you'll see that in next pages)

**Case 2**
(Same page as Case 1)
In the example VBA the following code generates an error because of the parenthesis after the method Invalidate.
Explanation: 
When using parenthesis, then arguments must be passed. The method Invalidate has no arguments. (In the next cases you'll see parenthesis will be used.)

Sub myFunction() 
    MyRibbon.Invalidate() ' Invalidates the caches of all of this add-in's controls 
End Sub
Should be:
Sub myFunction() 
 MyRibbon.Invalidate ' Invalidates the caches of all of this add-in's controls 
End Sub

**Note 1**: Also I recommend to change the example name myFunction to myProcedure (also in the next cases). Reason: there are two different procedures in VBA: a procedure Sub and a procedure Function. The given example is a procedure Sub. But the used name suggest (for beginners) this is a procedure Function. For them this can be confusing.

**Case 3**
https://docs.microsoft.com/en-us/office/vba/api/office.iribbonui.invalidate
The same story as in Case 1 and 3.

**Case 4**
https://docs.microsoft.com/en-us/office/vba/api/office.iribbonui.invalidatecontrol
XML Example:
Wrong: <customUI … OnLoad="MyAddInInitialize" …>
Correct: <customUI … onLoad="MyAddInInitialize" …>

**Note 2**: In this VBA Example parenthesis after InvalidateControl are correct used because InvalidateControl has an argument.
Only change the name myFunction to myProcedure (if you agree with me).

Sub myFunction() 
    MyRibbon.InvalidateControl("control1") ' Invalidates the cache of a single control 
End Sub

**Case 5**
https://docs.microsoft.com/en-us/office/vba/api/office.iribbonui.invalidatecontrolmso
The same as Case 4.

**Case 6**
https://docs.microsoft.com/en-us/office/vba/api/office.iribbonui.activatetab
In this case it's about the space between ActivateTab and (control.ID) 
This is not an error. When the code is paste in the Visual Basic Editor, VBA will automatically remove the space. But to remove the space in the example is exactly as it should be.

Public myRibbon As IRibbonUI 
Sub tabActivate(ByVal control As IRibbonControl) 
    myRibbon.ActivateTab (control.ID) 
End Sub

**Case 7**
https://docs.microsoft.com/en-us/office/vba/api/office.iribbonui.activatetabmso
The same as Case 5, plus textual error and code error.
"The following code makes a built-in tab as specified by the control ID of the active tab."
The code doesn't make, but activate the built-in tab.  (It makes the tab the active tab.)
And not by the control ID of the active tab, but by just the control id which is passed (the control ID a user clicks).
Should be:
"The following code activates a built-in tab by the passed control ID."
As I mentioned, this example is a bad one. So there are two things what makes this difficult: the bad example and the wrong text. I'll explain.

The argument control in ByVal control As IRibbonControl, is the control which a user clicked. This control (a button or so) is on a certain tab. The statement myRibbon.ActivateTabMso (control.ID)  tells the application to activate the built-in tab with the same ID as the clicked control… This results in a runtime error.

Sub tabActivate(ByVal control As IRibbonControl) 
    myRibbon.ActivateTabMso (control.ID) 
End Sub

I suggest to change the bad example in a good one including the text:

The following code activates the built-in tab "TabHome".
Sub MyTest(control As IRibbonControl)
    MyRibbon.ActivateTabMso "TabHome"
End Sub

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks for all of this! This is the type of thing that you can submit as a PR (you can include all the files in the same PR). So...do a fresh clone of VBA-Docs, make the changes in your fork, and then create a pull request to merge your changes to master. Sound good? This qualifies for a PR because of the number of changes (and how minute they are). Let me know if you have any questions.

**Comment by PeterVanLoosbroek** [comment]
Yes, Linda, sounds good, but I have to take time to study how it works. I've read today partly https://github.com/MicrosoftDocs/VBA-Docs/blob/master/contributing.md
These days I will take a closer look. Probably on the weekend. If I have questions, I ring the bell.
PR = Pull requests?

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks. Yes, PR = pull request.

**Comment by PeterVanLoosbroek** [comment]
OK, Linda, I am working on it this weekend. As far as I'm concerned you can close this post. I will read one and the other and then submit these things as a PR.

**Comment by Linda-Editor** [comment]
Thanks, Peter.
