### ISSUE TITLE
Expand Page With List of Constants

### ISSUE THREAD

**Issue by Janmanden** [MicrosoftDocs/VBA-Docs#101]
Under Parameters You write:

"What Optional Variant The kind of item to which the range is moved. Can be one of the WdGoToItem constants. " 
"Which Optional Variant The item to which the range is moved. Can be one of the WdGoToDirection constants. "

Please list the WdGoToItem contants and the WdGoToDirection constants here too. 

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: f86c8b01-5153-2ca6-2108-76c65d7b0ff6
* Version Independent ID: a5b95c38-60d5-1515-3d27-d0c493af00c5
* Content: [Range.GoTo Method (Word)](https://docs.microsoft.com/da-dk/office/vba/api/Word.Range.GoTo)
* Content Source: [api/Word.Range.GoTo.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Word.Range.GoTo.md)
* Product: **word**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@Janmanden 
Thanks for the feedback. I added links to the two constants. Changes will be live later today.

| _What_|Optional| **Variant**|The kind of item to which the range is moved. Can be one of the **[wdGoToItem](word.wdgotoitem.md)** constants.|
| _Which_|Optional| **Variant**|The item to which the range is moved. Can be one of the **[wdGoToDirection](word.wdgotodirection.md)** constants.|
