### ISSUE TITLE
What do we replace "?" with in this topic?

### ISSUE THREAD

**Issue by Linda-Editor** [MicrosoftDocs/VBA-Docs#1015]
@MarkFern Question for you: I'm editing the WorksheetFunction topics, and there is clearly an error in these docs where a question mark appears instead of the intended function. I think this is a result of when we migrated the topics; there was some coded symbol that didn't come over.

See the Remarks section on this page for an example: https://docs.microsoft.com/en-us/office/vba/api/excel.worksheetfunction.z_test.

I'm guessing that the ? is probably a greater than or less than sign, or maybe even a minus or plus sign, but I don't know for sure, and this is happening a lot in the docs for the WorksheetFunction object methods.

Any idea what the ? should be replaced with? Thanks for your help in advance. :-)

**Comment by MarkFern** [comment]
Hello @Linda-Editor.

It appears that it is a [long dash](https://en.oxforddictionaries.com/grammar/dash-and-em-dash). I've never used a long dash but it appears that at times when I've used the normal dash instead, I should instead have used the long dash  - never knew about this before.

I tried to get the old documentation using the [wayback machine](https://web.archive.org/web/*/https://msdn.microsoft.com/zh-cn/vba/vba-excel/*) but the documentation was unfortunately not archived.

I then downloaded the [Office 2013 VBA documentation](https://www.microsoft.com/en-gb/download/details.aspx?id=40326) but initially found that the .chm file was not working properly. I extracted the archive represented by the file (I think it might be just zip compressed), searched the .htm files, and found the page for the Z_Test function.

![Screenshot of Office 2013 VBA documentation for Z_Test function](https://user-images.githubusercontent.com/49532200/58082082-35e16280-7bae-11e9-9014-505238dc6601.png)

**Comment by Linda-Editor** [comment]
@MarkFern Thanks, Mark. The first one I figured out; many of these are m-dashes. But the ones I have a question about are under Remarks further down the page, and I don't think they're m-dashes. I tried downloading the chm too, but no luck. What were the steps you took to get to the htm files?

**Comment by Linda-Editor** [comment]
@MarkFern Guess what, I just found these pages here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.excel.worksheetfunction.z_test?view=excel-pia

Looks like it's a special math symbol...

**Comment by MarkFern** [comment]
To: @Linda-Editor.

I think PeaZip automatically detected the .chm file was an archive and enabled me to extract it straight from explorer.

If you rename the '.chm' to a '.zip' file, you'll probably be able to extract it as you would with any zip archive.
