### ISSUE TITLE
Ampersands in code

### ISSUE THREAD

**Issue by Linda-Editor** [MicrosoftDocs/VBA-Docs#1029]
@MarkFern Question for you:

I found some instances of `&amp;` in code samples; examples:
1) `vWhere = vWhere &amp; " AND [PymtTypeID]=" + Me.cboPaymentTypes`
2) `MsgBox "Report " &amp; strReportName &amp; _`

These should all be changed to `&`, correct? If so, I can easily do a search/replace on them. Please verify. Thanks...

**Comment by MarkFern** [comment]
@Linda-Editor&mdash;never seen this syntax before so I'm guessing that your suggested change is correct as with an actual ampersand character (as you suggest), the code looks correct.

When I start my Windows machine again, I'll find out whether this guessing of mine is actually correct.

If you have Excel installed, you could try pasting the code into a module & then try compiling it (I don't know how well versed you are with actually using VBA...) If the '\&amp;' text is coloured in red in the VBE, or the compiler / parser complains about it, then the syntax is invalid.

**Comment by Linda-Editor** [comment]
@MarkFern Thanks...I don't actually compile the code ever. If you can test it, that would be great. I think the ampersand code that appears is the result of a migration snafu...

**Comment by MarkFern** [comment]
@Linda-Editor, okay sure. We might be able to leverage the Rubberduck VBA grammar to set-up a web-page utility where you can test whether code syntax is correct or not.

@retailcoder might have some useful thoughts about such a utility as he seems to be in charge of the Rubberduck project.

**Comment by MarkFern** [comment]
The text '\&amp;' text has been incorrectly used in the related code examples. You can see this for some of the code by examining the following screenshots where the offending text is coloured in red.

![image](https://user-images.githubusercontent.com/49532200/58791161-9da19f80-85e9-11e9-90a0-17f48cabd5c3.png)

![image](https://user-images.githubusercontent.com/49532200/58791236-bdd15e80-85e9-11e9-8144-4c6f761bd64b.png)

Changing the '\&amp;' text to '&' text (after other code fixes I have suggested in PR #1032) creates code that parses, compiles & runs for the code examples @ https://github.com/MicrosoftDocs/VBA-Docs/blob/1763575e2778cbc7bd2bd1c7b465d6d46905fcf8/api/Access.CurrentProject.md & https://github.com/MicrosoftDocs/VBA-Docs/blob/03bb162aa9b653f1572b52d2864eb84ec67be2f1/api/Access.ComboBox.md .

Without such changes, the code doesn't parse & so subsequently also doesn't compile & run. In certain places in the code examples, such changes appear to make sense with respect to what the original code contributors seemed to be trying to achieve with the code. I didn't notice a place in the code examples where such changes appeared to ruin what the code contributors wanted the code to do.

**If I were you, I would make such changes for these code examples.**

**Comment by Linda-Editor** [comment]
@MarkFern: thanks for the feedback. I can change `&amp;` to `&` by doing a search/replace. If there are other code changes that need to be made that are more discrete, I'll need you to submit them as a PR, unless there's a straightforward search/replace option that I can do. Thanks.

**Comment by Linda-Editor** [comment]
@MarkFern Disregard my last comment. I just saw your PR. ;-)

**Comment by Linda-Editor** [comment]
@MarkFern I updated all instances of `&amp;` to `&`. In a prior bug, there were instances of `&;` that we changed to `&` as well (during the migration time period). The current update affected 231 files. Thanks for your help with this.
