### ISSUE TITLE
too slow

### ISSUE THREAD

**Issue by mrmuratinan** [MicrosoftDocs/VBA-Docs#103]
The web pages load very very slow. Especially  feedback section. :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd7466c-346e-f573-64cd-1d883ff0fd03
* Version Independent ID: 29c9ce52-f2da-fff9-e190-50f5810c78d8
* Content: [Access Visual Basic for Applications (VBA) reference](https://docs.microsoft.com/en-us/office/vba/api/overview/access)
* Content Source: [api/overview/Access.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/overview/Access.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Kagre** [comment]
@Linda-Editor possible dupe of #60

**Comment by lindalu-MSFT** [comment]
Need steps to repro including what version of access, vba, and what browser. Please provide and I'll reopen if this is still an issue.
