### ISSUE TITLE
C# code 

### ISSUE THREAD

**Issue by uzair-rm** [MicrosoftDocs/VBA-Docs#104]
This is for VB, would like to have C# code for the same to be used in ASP.NET MVC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10f9f6e9-25e2-c0f3-cdf2-a28a3f19c802
* Version Independent ID: 73d76073-a490-7189-7c66-919d94c1bc87
* Content: [Items.ItemAdd Event (Outlook)](https://docs.microsoft.com/en-us/office/vba/api/Outlook.Items.ItemAdd)
* Content Source: [api/Outlook.Items.ItemAdd.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Outlook.Items.ItemAdd.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Kagre** [comment]
I'm not 100% sure, but still fairly certain that's not possible. Also note this is for VBA which would be the COM model not the .NET.

**Comment by Linda-Editor** [comment]
@uzair-rm thanks for the feedback.
@Kagre thanks for your response.

Closing this issue.
