### ISSUE TITLE
Mistake on Decimal data type page re. bytes

### ISSUE THREAD

**Issue by MarkFern** [MicrosoftDocs/VBA-Docs#1044]
Hello @Linda-Editor,

On [**Decimal** data type page](https://docs.microsoft.com/en-gb/office/vba/language/reference/user-interface-help/decimal-data-type), please change:
- > Decimal variables are stored as 96-bit (12-byte) signed integers scaled by a variable power of 10. The power of 10 scaling factor specifies the number of digits to the right of the decimal point, and ranges from 0 to 28. ...

to:
- 'Decimal variables are stored as 96-bit (12-byte) unsigned integers, together with a scaling factor (used to either indicate a whole-number power of 10 to scale the integer down by, or that there should be no scaling), & also together with a value indicating whether the **Decimal** number is positive or negative. The scaling factor is the number of digits to store to the right of the decimal point, and ranges from 0 to 28. ...'

This correction can be verified by consulting the OLE Automation specification on the DECIMAL type that VBA's **Decimal** type maps to, [here](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-oaut/b5493025-e447-4109-93a8-ac29c48d018d).

**Comment by Linda-Editor** [comment]
@MarkFern Thanks. I made this update to the page (with minor edits to your submission); please confirm that it's okay or let me know if you want updates; changes will go live later today:

[Decimal variables](../../Glossary/vbe-glossary.md#decimal-data-type) are stored as 96-bit (12-byte) unsigned integers, together with a scaling factor (used to indicate either a whole number power of 10 to scale the integer down by, or that there should be no scaling) and a value (used to indicate whether the decimal number is positive or negative). 

The scaling factor is the number of digits to store to the right of the decimal point, and ranges from 0 to 28.

**Comment by MarkFern** [comment]
@Linda-Editor, thanks for looking at this.

The following text:
>  ... (used to indicate whether the decimal number is positive or negative) ...

shouldn't have brackets because it is of primary importance and not simply extra information.

Other edits seem fine. 

Your ability to fathom these other edits, is probably the reason why you're the editor. &nbsp;👍 &nbsp;😊

**Comment by Linda-Editor** [comment]
@MarkFern Thanks, Mark. I'll make those changes. :-)
