### ISSUE TITLE
Adding 'markup conventions & rules' section to contributing.md

### ISSUE THREAD

**Issue by MarkFern** [MicrosoftDocs/VBA-Docs#1051]
I'm aiming to make a PR in respect of this ISSUE at some point.

This ISSUE is related to ISSUE #999.

It is becoming clear that it would be useful to have more official guidance on what the form of content changes made to this repository should be. This ISSUE is concerned with the creation of documentation partially covering such official guidance.

See progress made so far concerning the proposal for this issue [here](https://github.com/MicrosoftDocs/VBA-Docs/compare/master...MarkFern:MF-PATCH/contributing.md/new_markup-conventions-&-rules_section).

If you would like me to PR the proposal straight-away, or by a certain date, let me know.

**Comment by MarkFern** [comment]
### HTML4 tags
See question [here](https://ux.stackexchange.com/questions/126306/do-html5-browsers-have-to-be-able-to-properly-process-html4-tags-when-the-tags-a) for information on whether HTML4 tags (& attributes) should be used in the markdown files of this repository. BTW, the markdown files in this repository are rendered as HTML5 pages. It's unclear whether HTML4 tags work in HTML5 pages.

**Comment by MarkFern** [comment]
### Note
If using HTML \<TABLE\> tag, then do properly & fully use the \<THEAD\> tag in order to make the information accessible to things like screen readers. See https://www.w3.org/WAI/tutorials/tables/ for more information.

**Comment by MarkFern** [comment]
### HTML
Whenever you can replace HTML with 'pure' markdown, do such replacement. HTML is more difficult to maintain & comprehend by general users. See https://github.com/MicrosoftDocs/VBA-Docs/issues/987#issuecomment-502127007 for more info.

**Comment by lindalu-MSFT** [comment]
@MarkFern thanks for taking the time to make this update. Your help is appreciated! I merged your fix and will publish shortly so closing this issue. Note we no longer monitor this repo regularly and in fact, we recently lost our beloved vendor (@Linda-Editor ) who was working on this docset. I pop in occasionally to see if there's anything to be merged, but I don't have regular bandwidth to monitor or follow up with issues.
