### ISSUE TITLE
Inaccurate ReDim remark when passing array ByRef.

### ISSUE THREAD

**Issue by IvenBach** [MicrosoftDocs/VBA-Docs#1069]
Reading through VB & VBA In a nutshell and testing the ReDim statement. The author points out that you can ReDim an array passed ByRef. Current [ReDim statement Remarks](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/redim-statement#remarks) says "If you pass an array to a procedure by reference, you can't redimension the array within the procedure." which is shown to be inaccurate based on the code below. That sentence can be removed.

```vb
Private Sub ResizingArrayPassedByRefIsPossible()
    Dim stringArray() As String
    ReDim stringArray(9)
    
    Dim counter As Long
    For counter = LBound(stringArray) To UBound(stringArray)
        stringArray(counter) = "Original element"
    Next
    
    ExpandArray stringArray
    
    For counter = LBound(stringArray) To UBound(stringArray)
        Debug.Print stringArray(counter)
    Next
End Sub

Private Sub ExpandArray(ByRef dynamicArray() As String)
    Dim oldUpperBound As Long
    oldUpperBound = UBound(dynamicArray)
    
    ReDim Preserve dynamicArray(UBound(dynamicArray) * 2)
    
    Dim counter As Long
    For counter = oldUpperBound + 1 To UBound(dynamicArray)
        dynamicArray(counter) = "New Element"
    Next
End Sub
```

**Comment by Linda-Editor** [comment]
@IvenBach  I've fixed this. Changes will be live later today. FYI - today is my last day. Another editor will take over going forward. It's been nice working with you. :-)

**Comment by IvenBach** [comment]
Congrats and I wish you well on your next assignment.
