### ISSUE TITLE
Unspecified limits

### ISSUE THREAD

**Issue by coolactuary** [MicrosoftDocs/VBA-Docs#107]
I think you should have specified that this method cannot create more than 255 sheets in one go - at least in 32 bit Excel 2010. I had to write a loop to create my 25,000 sheets!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d723863-e292-e18a-7732-b25d05f127aa
* Version Independent ID: 91bccf72-9566-7d4d-fe53-06b930008924
* Content: [Sheets.Add Method (Excel)](https://docs.microsoft.com/en-us/office/vba/api/Excel.Sheets.Add#feedback)
* Content Source: [api/Excel.Sheets.Add.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Sheets.Add.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@coolactuary 
Thanks for the feedback. I added a note at the bottom of the topic with your comment.  Changes will be live later today.
