### ISSUE TITLE
 VBA-Docs/api/Word.Styles.Add.md contains cut & paste errors

### ISSUE THREAD

**Issue by DaLynxx** [MicrosoftDocs/VBA-Docs#1071]
The  VBA-Docs/api/Word.Styles.Add.md have not been created correctly. It is incorrectly just a cut & paste from the HeadingStyles.Add method.

**Comment by Linda-Editor** [comment]
Is the information at https://docs.microsoft.com/en-us/office/vba/api/word.styles correct?

**Comment by Linda-Editor** [comment]
From the object page, I determined that indeed it was a bad copy/paste, and I fixed it according to the info on the object page. You can see the results in Git here: https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Word.Styles.Add.md. Changes will be live in a few days or so...

Thanks for finding this.
