### ISSUE TITLE
 VBA-Docs/api/Word.WdStyleType.md list of values incomplete?

### ISSUE THREAD

**Issue by DaLynxx** [MicrosoftDocs/VBA-Docs#1073]
The documentation currently lists 4 values (1 to 4).

However, when looking in the object Browser (in Visual Basic in Word) the WdStyleType is reported having 6 values.

The two missing ones are
wdStyleTypeParagraphOnly (=5) och wdStyleTypeLinked (=6).

The documentation should probably also mention that if you create a Style with ActiveDocument.Styles.Add("StyleName", wdStyleTypeParagraph) you get a "linked" style as a result. You have to use the wdStyleTypeParagraphOnly to get a "pure" paragraph style.

Not sure what the difference is between using wdStyleTypeParagraph and wdStyleTypeLinked is in practice and why the wdStyleTypeParagraphOnly had to be created.

**Comment by Linda-Editor** [comment]
Adding the live link for reference: https://docs.microsoft.com/en-us/office/vba/api/word.wdstyletype

Thanks for this info; @Lindalu-MSFT, can you follow up?

**Comment by lindalu-MSFT** [comment]
@Linda-Editor sure, thanks for the heads up!

**Comment by lindalu-MSFT** [comment]
Actually, it appears that wdStyleTypeLinked and wdStyleTypeParagraphOnly are reserved for internal use only. I will need to follow up with the product team for verification.

**Comment by lindalu-MSFT** [comment]
wdStyleTypeLinked and wdStyleTypeParagraphOnly are reserved for internal use only. Closing issue.
