### ISSUE TITLE
Missing values in api/PowerPoint.PpEntryEffect.md

### ISSUE THREAD

**Issue by mitechzone** [MicrosoftDocs/VBA-Docs#1074]
https://docs.microsoft.com/en-us/office/vba/api/PowerPoint.PpEntryEffect

The following values are missing:

ppEffectWheelReverse1Spoke	3862
ppEffectVortexLeft	3863
ppEffectVortexUp	3864
ppEffectVortexRight	3865
ppEffectVortexDown	3866
ppEffectRippleCenter	3867
ppEffectRippleRightUp	3868
ppEffectRippleLeftUp	3869
ppEffectRippleLeftDown	3870
ppEffectRippleRightDown	3871
ppEffectGlitterDiamondLeft	3872
ppEffectGlitterDiamondUp	3873
ppEffectGlitterDiamondRight	3874
ppEffectGlitterDiamondDown	3875
ppEffectGlitterHexagonLeft	3876
ppEffectGlitterHexagonUp	3877
ppEffectGlitterHexagonRight	3878
ppEffectGlitterHexagonDown	3879
ppEffectGalleryLeft	3880
ppEffectGalleryRight	3881
ppEffectConveyorLeft	3882
ppEffectConveyorRight	3883
ppEffectDoorsVertical	3884
ppEffectDoorsHorizontal	3885
ppEffectWindowVertical	3886
ppEffectWindowHorizontal	3887
ppEffectWarpIn	3888
ppEffectWarpOut	3889
ppEffectFlyThroughIn	3890
ppEffectFlyThroughOut	3891
ppEffectFlyThroughInBounce	3892
ppEffectFlyThroughOutBounce	3893
ppEffectRevealSmoothLeft	3894
ppEffectRevealSmoothRight	3895
ppEffectRevealBlackLeft	3896
ppEffectRevealBlackRight	3897
ppEffectHoneycomb	3898
ppEffectFerrisWheelLeft	3899
ppEffectFerrisWheelRight	3900
ppEffectSwitchLeft	3901
ppEffectSwitchUp	3902
ppEffectSwitchRight	3903
ppEffectSwitchDown	3904
ppEffectFlipLeft	3905
ppEffectFlipUp	3906
ppEffectFlipRight	3907
ppEffectFlipDown	3908
ppEffectFlashbulb	3909
ppEffectShredStripsIn	3910
ppEffectShredStripsOut	3911
ppEffectShredRectangleIn	3912
ppEffectShredRectangleOut	3913
ppEffectCubeLeft	3914
ppEffectCubeUp	3915
ppEffectCubeRight	3916
ppEffectCubeDown	3917
ppEffectRotateLeft	3918
ppEffectRotateUp	3919
ppEffectRotateRight	3920
ppEffectRotateDown	3921
ppEffectBoxLeft	3922
ppEffectBoxUp	3923
ppEffectBoxRight	3924
ppEffectBoxDown	3925
ppEffectOrbitLeft	3926
ppEffectOrbitUp	3927
ppEffectOrbitRight	3928
ppEffectOrbitDown	3929
ppEffectPanLeft	3930
ppEffectPanUp	3931
ppEffectPanRight	3932
ppEffectPanDown	3933

**Comment by Linda-Editor** [comment]
Added new constants to enumeration page. Changes will be live in a few days.
