### ISSUE TITLE
Formatting issue - api/Outlook.olunifiedgrouptype.md and Outlook.olunifiedgroupfoldertype.md

### ISSUE THREAD

**Issue by mitechzone** [MicrosoftDocs/VBA-Docs#1075]
Tables not formatted correctly.

https://docs.microsoft.com/en-us/office/vba/api/outlook.olunifiedgrouptype
https://docs.microsoft.com/en-us/office/vba/api/outlook.olunifiedgroupfoldertype

**Comment by Linda-Editor** [comment]
Fixed tables. Thanks for pointing this out. Changes will be live in a few days.
