### ISSUE TITLE
VBA-Docs/outlook/Concepts/Forms/globally-change-a-default-form.md not valid anymore

### ISSUE THREAD

**Issue by jadoming** [MicrosoftDocs/VBA-Docs#1083]
The information in this document is not valid anymore and customers need an alternative solution that works with Office 365.

**Comment by lindalu-MSFT** [comment]
Hi, @jadoming Can you please provide steps to repro? Is this the topic you're referring, to?
[https://docs.microsoft.com/en-us/office/vba/outlook/concepts/forms/globally-change-a-default-form](https://docs.microsoft.com/en-us/office/vba/outlook/concepts/forms/globally-change-a-default-form)

**Comment by lindalu-MSFT** [comment]
No repro steps from customer, closing issue. Please reopen and ping me if you feel this issue needs attention still! We need the steps to repro why the steps are no longer valid. 
Steps to repro, expected results, and actual results. Thanks, lindalu
