### ISSUE TITLE
Missing links in a page "Cannot open a database created with a previous version of your application. (Error 3041)"

### ISSUE THREAD

**Issue by ryanmajidi** [MicrosoftDocs/VBA-Docs#1087]
Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1740) by @tygrus2

This page has links which are missing (out-of-date). Cannot open a database created with a previous version of your application. (Error 3041)
Error in the following links ="404 – Page not found"

Application.CompactRepair method (Access)
https://msdn.microsoft.com/library/4820fd79-d907-21bc-0ad5-5fc096c1ef3b%28Office.15%29.aspx

Compact and Repair a Database
https://msdn.microsoft.com/library/5ad4e6b1-abfd-3f89-5c80-9e41397a96e8%28Office.15%29.aspx

It appears users have lost functionality and access to old files because Microsoft has a short attention span.

At the very least, these links should be updated or redirected to related information.

If there are some issues of security then the user should be given a prompt before opening and has the ability to convert to a newer file format (for newer app version). Then the user can open the old content as a new file.

**Comment by Linda-Editor** [comment]
It appears that the references mentioned no longer exist. I added the following link to the page instead: https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/dbengine-compactdatabase-method-dao. Changes should be live later today.
