### ISSUE TITLE
Newly introduced bug: VBA.Array() returns "<Invalid procedure call or argument>"

### ISSUE THREAD

**Issue by karstenheld3** [MicrosoftDocs/VBA-Docs#1104]
The following code does not run with Microsoft Office 365 MSO (16.0.11328.20362) 32 Bit:
```
Sub test()
  Dim a As Variant
  a = VBA.Array()
  Dim b() As Variant
  b = VBA.Array() ' <- crashes with Runtime error '5': Invalid procedure call or argumet
End Sub
```
It did run with Microsoft Office 365 MSO (16.0.10730.20348) 32 Bit and lower.
In the watch window one can observe the content of `a` being `<Invalid procedure call or argument>` `VBA.Array()` can no longer be used to create empty typed arrays.

**Comment by retailcoder** [comment]
Should be fixed with kb4512494, see
https://support.microsoft.com/en-us/help/4512494/windows-10-update-kb4512494

**Comment by Linda-Editor** [comment]
@retailcoder Thanks for the fix! I'll close this issue; please reopen if there are further comments.
