### ISSUE TITLE
Worksheet.Protect method doesn't indicate UserInterfaceOnly is removed on closing Workbook

### ISSUE THREAD

**Issue by IvenBach** [MicrosoftDocs/VBA-Docs#1109]
Steps to reproduce/illustrate behavior:
1. Create new blank Worksheet.
2. `Alt+F11` to open the VBA Integrated Developer Environment (IDE).
3. If Immediate Window isn't displayed from menu at top choose View>Immediate Window (Hotkey: `Ctrl+G`
4. In Immediate Window copy and paste the following code `ActiveSheet.Protect Password:=vbNullString, UserInterfaceOnly:=True` and execute it by hitting [Enter]. As per [Worksheet.Protect](https://docs.microsoft.com/en-us/office/vba/api/excel.worksheet.protect) the inclusion of  `UserInterfaceOnly:=True` will "protect the user interface, but not macros."
5. Confirm the ActiveSheet user interface is locked by attempting to double click any cell. Dialog will display indicating it is protected.
6. Confirm the ActiveSheet can be modified by code. Execute in the Immediate Window `ActiveSheet.Range("A1").Value2 = "Entered while Worksheet was locked"` executing with [Enter] to display the text string in cell A1.
7. Save the workbook to an easily accessible location such as the Desktop.
8. Open workbook and repeat step 6. A dialog will be shown stating the Worksheet needs to be unlocked first.

[Deprecated documentation](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/s1cay0kc(v=vs.100)#remarks) indicates this behavior while [current documentation](https://docs.microsoft.com/en-us/office/vba/api/excel.worksheet.protect#remarks) does not. Found from https://stackoverflow.com/questions/38353751/sheet-protection-userinterfaceonly-gone.

**Comment by lindalu-MSFT** [comment]
@IvenBach Thanks for pointing this out. I repro'd these steps in my environment, so I added a NOTE to the current topic and refer to the behavior in previous versions, and how to fix.

**Comment by lindalu-MSFT** [comment]
See [https://github.com/MicrosoftDocs/VBA-Docs/pull/1168](https://github.com/MicrosoftDocs/VBA-Docs/pull/1168). Will merge to live shortly. Thanks again @IvenBach Kind regards, lindalu
