### ISSUE TITLE
info

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#1116]
Dear Linda,

I just want to let you know that I'm still here. Recently I have not had the opportunity. But I noted everything well, so I know well what I promised. I will definitely resume my help as soon as I have the time.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks. I'm actually no longer at Microsoft, but you can work with @lindalu-MSFT to post issues and PRs. However, I'm still on GitHub, so I may see your requests come thru and possibly comment on them. Take care.
