### ISSUE TITLE
Broken link in Outlook.checkbox.object.md caused by incorrect filename Outlook.checkbox(properties.md

### ISSUE THREAD

**Issue by Hydro95** [MicrosoftDocs/VBA-Docs#1118]
A missing closing bracket in the markdown link name causes the anchor link to break in the webpage (blame link below since I don't think I can link the markdown correctly any other way). 

I was originally going to open a PR to fix the missing closing bracket in the link, but following the new link causes a 404 because the actual filename turns out to be also missing the closing bracket, so this may require a closer look than I would have experience to fix.

The broken link is here specifically: https://github.com/MicrosoftDocs/VBA-Docs/blame/master/api/Outlook.checkbox.object.md#L19

The incorrectly named file is located at api/Outlook.checkbox(properties.md

**Comment by Linda-Editor** [comment]
@Hydro95 thanks for finding this. There are actually numerous errors in the section that need to be cleaned up, but we're not there yet. However, I did fix the Checkbox object pages. There are redundant pages that need to be removed that exist from our old information architecture. Someone will get to this eventually. Changes will be live by tomorrow. Go to https://docs.microsoft.com/en-us/office/vba/api/outlook.checkbox to see the changes.
