### ISSUE TITLE
Examples written with localized input should be disclaimed as such

### ISSUE THREAD

**Issue by gidven** [MicrosoftDocs/VBA-Docs#1119]
Example:
https://docs.microsoft.com/en-us/office/vba/api/excel.range.style

The samples work *only* if you are running an English version of Excel. Incorporating this code in your VBA and sharing the file with, say, a Spanish user is impossible, because the styles "Normal" or "Good" or "Bad" do not exist in Spanish Excel.

Moreover, I don't believe these styles have a generic ID that you can reference instead? (correct me if I am wrong)

Another example:
https://docs.microsoft.com/en-us/office/vba/api/excel.range.formula

The formula at the bottom fails in non-English Excel versions because it is hard-coded.

Proposed solution:
Add a note to samples that include localized VBA, or provide a generic alternative that is not bound to the specific language Excel is running in.

**Comment by lindalu-MSFT** [comment]
@gidven I agree, for the most part the localized VBA topics describe the style and translation. FOr example, here is the localized version that uses "Normal"  and "Percent" in the code example:
[https://docs.microsoft.com/es-es/office/vba/api/excel.range.style](https://docs.microsoft.com/es-es/office/vba/api/excel.range.style) But the description of the code explains the style name "Normal" (same in this example) and "porcentaje." So, in the URL just replace /en-us/ with /es-es/. I do not think there is a list of codes for style names where you can lookup the localized version. Try StackOverflow to see if anyone's come up with code that does this!
