### ISSUE TITLE
How do i copy excel table to word using python with win32com

### ISSUE THREAD

**Issue by He-haitao** [MicrosoftDocs/VBA-Docs#1130]
like below, copy excel table to a word and how to keep the format of tables using win32com?
It's really hard to read the docs
sheet1.Name
sheet1

sheet2.Name
sheet2

Can somebody try to help me!

**Comment by barnam3** [comment]
There are many answers and examples on [stackoverflow ](https://stackoverflow.com/questions/50504112/how-to-paste-excel-table-into-word-using-python) addressing these methods. If you have an issue with a specific document that can be improved, please link to it here and someone will take a look.
