### ISSUE TITLE
Add Warning about issue with Week 53

### ISSUE THREAD

**Issue by Markgi999** [MicrosoftDocs/VBA-Docs#1147]
Please add this warning to the top of the topic:

**Warning**    There is an issue with the use of this function. The last Monday in some calendar years can be returned as week 53 when it should be week 1. For more information and a workaround, see "Format or DatePart functions can return wrong week number for last Monday in Year" (https://docs.microsoft.com/en-us/office/troubleshoot/access/functions-return-wrong-week-number).

For reference, see also https://support.office.com/en-us/article/DatePart-Function-26868A79-5505-4E5A-8905-6001372223FA

**Comment by lindalu-MSFT** [comment]
@Markgi999 Thanks for pointing this out! This issue is now documented and appears in the topic on the live site.
