### ISSUE TITLE
Add Warning to top of topic re Last Monday issue

### ISSUE THREAD

**Issue by Markgi999** [MicrosoftDocs/VBA-Docs#1148]
Please add this warning to the top of the topic:

**Warning**    There is an issue with the use of this function. The last Monday in some calendar years can be returned as week 53 when it should be week 1. For more information and a workaround, see "Format or DatePart functions can return wrong week number for last Monday in Year" (https://docs.microsoft.com/en-us/office/troubleshoot/access/functions-return-wrong-week-number).

For reference, see also https://support.office.com/en-us/article/Format-Function-6F29D87B-8761-408D-81D3-63B9CD842530

**Comment by lindalu-MSFT** [comment]
[https://docs.microsoft.com/en-us/office/troubleshoot/access/functions-return-wrong-week-number](https://docs.microsoft.com/en-us/office/troubleshoot/access/functions-return-wrong-week-number)

The ref is here, I can updated but IF (unlikely) we ever build VBA again, it might get overwritten! Still worth updating manually, though.
[https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/datepart-function](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/datepart-function)

**Comment by Markgi999** [comment]
Linda,
Ok, I defer to your judgement on this. 😉
But, please edify us on this rebuild issue.
It’s possible we may be requesting changes to a number of Access VBA topics in the near future.
Will it be problematic? Why would changes get over-written?
Thanks, Mark

**Comment by lindalu-MSFT** [comment]
Actually, I can fix the VBA ref, but I do not have permissions to merge PRs in the repo where this  support article lives:
[https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/functions-return-wrong-week-number.md](https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Office/Client/access/functions-return-wrong-week-number.md
). I submitted the PR, but it looks like no one is monitoring them. I'll try to find out who can grant me permissions so I can handle these (I've been updating SOC content for decades, no reason I shouldn't be able to do this!)

**Comment by lindalu-MSFT** [comment]
@davidchesnut Do you have admin perms in MicrosoftDocs? Can you grant me admin rights to OfficeDocs-Support?

**Comment by davidchesnut** [comment]
@lindalu-MSFT I do not have admin perms on OfficeDocs-Support. Sorry...

**Comment by lindalu-MSFT** [comment]
Fixed where we have permissions to fix! CSS fixing on their site, as well.
