### ISSUE TITLE
See also ShowModal property

### ISSUE THREAD

**Issue by geoffm** [MicrosoftDocs/VBA-Docs#116]
https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/showmodal-property

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93a2758f-6eb0-98ce-12eb-8e33b243aeb0
* Version Independent ID: 218ef567-bf1f-f829-47c6-2a645292cf98
* Content: [Show Method](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/show-method)
* Content Source: [Language/Reference/User-Interface-Help/show-method.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/show-method.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@geoffm 
Thanks. I added the See also link to the show method page. Changes will be live later today.
