### ISSUE TITLE
instead of using error handling ...

### ISSUE THREAD

**Issue by ashleedawg** [MicrosoftDocs/VBA-Docs#133]
Instead of using error handling to determine if there's a match (like the second example), I'd suggest using `Is Nothing` (like the first example).

IMO the second example is poorly written and therefore should be removed from this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e2ceb10-7976-f7ea-e3c7-b97afb6ff4cc
* Version Independent ID: 6cdbbded-ee51-bc63-7551-f36d4d544c12
* Content: [Range.Find Method (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.range.find)
* Content Source: [api/Excel.Range.Find.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Range.Find.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ashleedawg 

Thanks. I commented out the second example. Changes will be live later today.
