### ISSUE TITLE
RelativeTo parameter default

### ISSUE THREAD

**Issue by AlanOlrog** [MicrosoftDocs/VBA-Docs#148]
The Description of the optional "RelativeTo" parameter states that:
"If RowAbsolute and ColumnAbsolute are False, and ReferenceStyle is xlR1C1, you must include a starting point for the relative reference."

Testing with Excel VBA 7.1 shows that an explicit starting point is NOT mandatory. There appears to be a default reference of $A$1, which should be mentioned in the Description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4607d14-ea1a-4280-fc40-71f8f970daf3
* Version Independent ID: 8512cc38-aaa6-2d93-2dd3-6054616b4eeb
* Content: [Range.Address Property (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.range.address?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev11.query%3FappId%3DDev11IDEF1%26l%3Den-US%26k%3Dk(vbaxl10.chm144076)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv16)%26rd%3Dtrue#see-also)
* Content Source: [api/Excel.Range.Address.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Range.Address.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlanOlrog** [comment]
![range address parameter feedback](https://user-images.githubusercontent.com/42843810/45425414-2e69d100-b691-11e8-830c-8fa2247eb193.png)

**Comment by Linda-Editor** [comment]
@AlanOlrog 
Thanks for the feedback. I added your comment as a NOTE in the RelativeTo section of the table: "**NOTE**: Testing with Excel VBA 7.1 shows that an explicit starting point is not mandatory. There appears to be a default reference of $A$1." Changes will be live later today.
