### ISSUE TITLE
Is optional parameters formating correct?

### ISSUE THREAD

**Issue by FlameHorizon** [MicrosoftDocs/VBA-Docs#149]
`Format(Expression [ ,Format [ ,FirstDayOfWeek [ ,FirstWeekOfYear ]]])` in syntax section looks kinda funky.

I would expect: `Format(Expression, [Format], [FirstDayOfWeek], [FirstWeekOfYear])`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bb4add8-09d2-3251-6654-aef5bf11fcc4
* Version Independent ID: b81975f3-b0c2-52ad-529d-d4ac2c3df9f1
* Content: [Format function (Visual Basic for Applications)](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/format-function-visual-basic-for-applications#feedback)
* Content Source: [Language/Reference/User-Interface-Help/format-function-visual-basic-for-applications.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/format-function-visual-basic-for-applications.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@GustavBrock - can you comment on this? I agree that this string is strange; if you agree, I'll fix it.

**Comment by GustavBrock** [comment]
To be honest, I forgot to debug that - it also looked wrong to me. Thanks for the reminder.
The proposed syntax matches that of _IntelliSense_:

`Format(Expression, [Format], [FirstDayOfWeek], [FirstWeekOfYear])`

However, a trailing comma is not allowed - a comma must always be followed by either another comma or a parameter. The extended syntax to reflect this would be close to incomprehensible.

**Comment by Linda-Editor** [comment]
Okay, so should I update the strings to the IntelliSense format that you provided? And just to confirm, there's no space between `Format(Expression...`?

**Comment by GustavBrock** [comment]
Yes, that's what I would suggest. And right, no space:

![Format IntelliSense](https://user-images.githubusercontent.com/6253835/45560509-982adc00-b845-11e8-8800-14ef3c137013.png)

**Comment by Linda-Editor** [comment]
@FlameHorizon @GustavBrock 

I changed it to this: **Format**(_Expression_, [_Format_], [_FirstDayOfWeek_], [_FirstWeekOfYear_])

Changes should be live by tomorrow. Let me know if you have any questions.
