### ISSUE TITLE
Missing text in first paragragh of section explaning. "Include Single Quotation Marks".

### ISSUE THREAD

**Issue by barnam3** [MicrosoftDocs/VBA-Docs#152]
"For instance, suppose your criteria argument must contain a string variable called ." Called what? strName?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 088c9210-5f79-264e-9d5b-2b17a911c603
* Version Independent ID: 1104e32c-3a0c-9ad8-e84c-248a9e869b8f
* Content: [Quotation Marks in Strings](https://docs.microsoft.com/en-us/office/vba/access/concepts/criteria-expressions/quotation-marks-in-strings)
* Content Source: [access/Concepts/Criteria-Expressions/quotation-marks-in-strings.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/access/Concepts/Criteria-Expressions/quotation-marks-in-strings.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@barnam3 

Thanks for the feedback. I fixed this page; does it make sense now?
