### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by pascalito80** [MicrosoftDocs/VBA-Docs#154]
Shouldn't it be xlIconSet?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d0418bfd-335a-0360-6eda-c274dbe5b583
* Version Independent ID: cca6e731-fb0b-320f-a7be-0db683143f89
* Content: [XlFormatConditionType Enumeration (Excel)](https://docs.microsoft.com/fr-fr/office/vba/api/excel.xlformatconditiontype)
* Content Source: [api/Excel.XlFormatConditionType.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.XlFormatConditionType.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@pascalito80 
Yes, good catch! I made the update, and changes should be live later today.
