### ISSUE TITLE
Unresolved Error workarround

### ISSUE THREAD

**Issue by JKeith42** [MicrosoftDocs/VBA-Docs#158]
By pulling out sections of the query I was attempting, I determined it was the criteria trying to limit to a range of datetime values.  My workaround was to build a temp table without the datetime selection, then in a later query use the temp table instead of the linked ODBC table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c41411fd-9bf1-9e7f-d99b-cfde4e330645
* Version Independent ID: ccd6ff03-36ca-8fd8-13cb-5ac96c687165
* Content: [Reserved error &lt;Item&gt;; there is no message for this error. (Error 3000)](https://docs.microsoft.com/en-us/office/vba/access/concepts/miscellaneous/reserved-error-itemthere-is-no-message-for-this-errorerror-3000?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev11.query%3FappId%3DDev11IDEF1%26l%3Den-US%26k%3Dk(jeterr40.chm5003000)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv16)%26rd%3Dtrue)
* Content Source: [access/Concepts/Miscellaneous/reserved-error-itemthere-is-no-message-for-this-errorerror-3000.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/access/Concepts/Miscellaneous/reserved-error-itemthere-is-no-message-for-this-errorerror-3000.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@JKeith42 
Thanks for your contribution. I added your comment as a note on the Error 3000 topic. Changes will go live later today.
