### ISSUE TITLE
Two small typos in the VB Code sample

### ISSUE THREAD

**Issue by GaryBartlett** [MicrosoftDocs/VBA-Docs#165]
Line 2 should read: With myDocument.Shapes.BuildFreeform(EditingType:=msoEditingCorner, _ 
    X1:=360, Y1:=200) 
       ^             ^

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 559976f9-537d-7d40-4fc7-d3e589cacb0d
* Version Independent ID: aa88ea41-b165-9eca-4475-7f980c7ed16b
* Content: [Shapes.BuildFreeform Method (PowerPoint)](https://docs.microsoft.com/en-us/office/vba/api/powerpoint.shapes.buildfreeform)
* Content Source: [api/PowerPoint.Shapes.BuildFreeform.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/PowerPoint.Shapes.BuildFreeform.md)
* Product: **powerpoint**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@GaryBartlett I fixed this issue. Thanks for contributing. Changes should be live by tomorrow.
