### ISSUE TITLE
You can also use the series name

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/VBA-Docs#174]
Like this:
expression.FullSeriesCollection("series name in quotes")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a828ff3-cab8-f55d-4c58-c4336f5899ce
* Version Independent ID: fc66ba16-1405-014f-3be9-1a253da5f1fd
* Content: [Chart.FullSeriesCollection Method (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.chart.fullseriescollection)
* Content Source: [api/Excel.chart.fullseriescollection.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.chart.fullseriescollection.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@HairyDrumroll 

Thanks for the feedback. I added your comment as a note under Remarks. Changes should go live later today.
