### ISSUE TITLE
Missing value

### ISSUE THREAD

**Issue by cronaueres** [MicrosoftDocs/VBA-Docs#177]
Pivot table connection uses value 9. Seems to be a No source connection, with xlConnectionTypeNOSOURCE name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48f0bb52-ae01-d31a-ccb5-0583114990d2
* Version Independent ID: 0448c7f6-3a80-951e-365e-097f5bbbbf11
* Content: [XlConnectionType Enumeration (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.xlconnectiontype)
* Content Source: [api/Excel.XlConnectionType.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.XlConnectionType.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@cronaueres 

Thanks for your feedback. Can you show me exactly how you'd like it added to the table?

**Comment by cronaueres** [comment]
Sure! In line xlConnectionTypeNOSOURCE, value 9, description No source. Something like this:

XlConnectionType.xlConnectionTypeMODEL | 7 | PowerPivot Model
xlConnectionTypeNOSOURCE |  _**9**_ | No source
xlConnectionTypeODBC | 2 | ODBC

Thank you

**Comment by Linda-Editor** [comment]
@cronaueres 
Thanks for the clarification. I added the "9" as the value. For future reference, please be as specific as possible with any change requests. Assume nothing. :-)

Changes will go live later today.

**Comment by Linda-Editor** [comment]
@cronaueres I have a question about this page that I hope you can answer: 

Is this line correct: **XlConnectionType.xlConnectionTypeMODEL**, or should it be just **xlConnectionTypeMODEL**?

And is there a difference between using capital "Xl" vs lowercase "xl"? I think using the latter in display names makes them easier to read, but just want to confirm that it's okay to change all of them to "xl"...

Thanks for your help...

**Comment by cronaueres** [comment]
Sorry, probably I copied it wrongly. As you presume, it is only xlConnectionTypeMODEL.
In VBA there's no difference between using uppercase or lowercase characters. But, as a convention, it's typed like this:
xlConnectionTypeMODEL

Thank you, Linda

**Comment by Linda-Editor** [comment]
@cronaueres  thanks for this info. I'll fix it, and going forward will use lowercase "xl"...
