### ISSUE TITLE
.FormatConditions.Interior.ColorIndex

### ISSUE THREAD

**Issue by CapitainFlam** [MicrosoftDocs/VBA-Docs#180]
A was looking for the folowing information, but i'm unable to write it in a "Docs" format. 

Here is the idea : 
***********
Note : in case you would like to use color with FormatCondition in VB, you should look at something like .FormatConditions(IndexFormatCondition).Interior.ColorIndex
***********

If someone used to writing in those docs could handle it, it would surely be usefull for others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b432d6a-4b78-2dfd-84eb-001b9571ae8b
* Version Independent ID: ebf4528e-5d0a-26a2-ed41-b404df1a116d
* Content: [ColorIndex Property](https://docs.microsoft.com/en-us/office/vba/api/Excel.ColorIndex)
* Content Source: [api/Excel.ColorIndex.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.ColorIndex.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@CapitainFlam 

Thanks for your feedback. I added this note; is that what you meant? If not, I need you to be specific about the link you want to point people to.

> [!NOTE] 
> If you would like to use color with FormatCondition in Visual Basic, see [Interior.ColorIndex Property (Excel)](excel.interior.colorindex.md).

**Comment by CapitainFlam** [comment]
@Linda-Editor 
Thanks for your answer ! 
...Indeed, yes, it is exactly the note I would have been looking for ! 
Thanks again !

**Comment by Linda-Editor** [comment]
@CapitainFlam Thanks for confirming! Changes will go live in a day or so...
