### ISSUE TITLE
Description may be too specific?

### ISSUE THREAD

**Issue by glennfromiowa** [MicrosoftDocs/VBA-Docs#184]
Wouldn't it be more accurate to say "Specifies from where to copy the format for inserted cells" instead of "inserted rows," since rows, columns, or cells could be inserted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ec8f47-656c-3909-e09a-05b29bfd3ca4
* Version Independent ID: e42f198e-f97d-09bd-4e58-947ec4307c20
* Content: [XlInsertFormatOrigin Enumeration (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.xlinsertformatorigin)
* Content Source: [api/Excel.XlInsertFormatOrigin.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.XlInsertFormatOrigin.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@glennfromiowa 

Thanks for this feedback. You're absolutely right, so I made the change. Changes should go live later today.
