### ISSUE TITLE
Access: add DlookUp Example

### ISSUE THREAD

**Issue by ppurpura** [MicrosoftDocs/VBA-Docs#196]
Here is an coding example of using DLookUp in a Do Loop. It demonstrates how to build the Criteria string on each pass through the loop.   The loop verifies data from an input data set, in this case Operating System names, against those contained in a Master List. If an OS name is not found, then a flag is set and the name of the unknown OS is output to a table. 

First an apostrophe is concatenated at the beginning and at the end of a datum referenced by "rs1!OS", which is then concatenated to build the entire criteria string.

    Do Until I1 &gt; NRec1
    
        Str_2 = "'" & rs1!OS & "'"
        Str_1 = "[OS] = " & Str_2
        
        J1 = DLookup("[ID]", "tbl_81_Operating_Systems_Master_List", Str_1)
        
        If IsNull(J1) = True Then
        
            rs3.AddNew
            rs3.OS = rs1!OS
            rs3.Update
            Err_Fl = False

        End If

        rs1.MoveNext
        I1 = I1 + 1

    Loop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e2f232e-43d7-81e3-b277-6d0e0048f1dd
* Version Independent ID: a1c9bec7-9bc8-65cc-aac7-e164139f762b
* Content: [Application.DLookup Method (Access)](https://docs.microsoft.com/en-us/office/vba/api/access.application.dlookup)
* Content Source: [api/Access.Application.DLookup.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Access.Application.DLookup.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
Added sample with comments to DLookUp Method (Access)
