### ISSUE TITLE
MS JScript reference?

### ISSUE THREAD

**Issue by HarryCaveMan** [MicrosoftDocs/VBA-Docs#199]
Is there an Object reference for the Access.Application object for MS JScript?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07b1675b-56b3-4b50-783a-1768a127d84a
* Version Independent ID: aa3342f4-529f-13bc-54d8-53612a889f80
* Content: [Application.Run Method (Access)](https://docs.microsoft.com/en-us/office/vba/api/access.application.run)
* Content Source: [api/Access.Application.Run.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Access.Application.Run.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@HarryCaveMan 
I'm not sure, but you might try the Access Desktop Database Reference: https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/. Type "JScript" in the search filter at the top of the navigation.
