### ISSUE TITLE
Great example code!

### ISSUE THREAD

**Issue by tmhtmhtmh** [MicrosoftDocs/VBA-Docs#211]
Examples are what make the article useful!  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0459b6d1-aae9-e812-c2a0-992ac6b8e475
* Version Independent ID: 938e7aa4-6444-b43e-b61c-23ac8b760321
* Content: [ListBox.ListCount Property (Access)](https://docs.microsoft.com/en-us/office/vba/api/access.listbox.listcount)
* Content Source: [api/Access.ListBox.ListCount.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Access.ListBox.ListCount.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@tmhtmhtmh 
Thanks for the positive feedback! :-)
