### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hvin** [MicrosoftDocs/VBA-Docs#223]
There is an error

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7c5c4d8a-ecb8-2e4e-8372-236da95c33d9
* Version Independent ID: cd43767c-c838-c705-ced0-37c07287ba90
* Content: [Compile error in hidden module: , Office Shared \[vblr6.chm1040201\]](https://docs.microsoft.com/ja-jp/office/vba/f1/compile-error-in-hidden-modulemodule-nameoffice-shared-vblr6-chm1040201?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev11.query%3FappId%3DDev11IDEF1%26l%3Dja-JP%26k%3Dk(vblr6.chm1040201)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv15)%26rd%3Dtrue)
* Content Source: [F1/compile-error-in-hidden-modulemodule-nameoffice-shared-vblr6-chm1040201.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/F1/compile-error-in-hidden-modulemodule-nameoffice-shared-vblr6-chm1040201.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@hvin 

Thanks for your feedback. However, we're not sure what your issue is, so we're closing it. If you're still having a problem, please re-open the issue with more specific information. Thanks.
