### ISSUE TITLE
Additional information to help others

### ISSUE THREAD

**Issue by mrduncle** [MicrosoftDocs/VBA-Docs#224]
In the "See also" section I think it would be beneficial to add DoCmd.RunCommand acCmdSaveRecord as information about this topic is hard to come by on the internet and searching on "Access" and "save" tends to lead you to this page. Possibly some comment in the "Remarks" section might be helpful as well (eg if attempting to save a record refer to link in See also section).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37f59eb3-603e-5174-9677-ae81462188ff
* Version Independent ID: effa53c6-2b6d-3d5d-a8db-ef1b3c888c73
* Content: [DoCmd.Save method (Access)](https://docs.microsoft.com/en-us/office/vba/api/access.docmd.save#feedback)
* Content Source: [api/Access.DoCmd.Save.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Access.DoCmd.Save.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@mrduncle 

Thanks for your feedback. On the Access.DoCmd.Save page, I added a See also link to the DoCmd.RunCommand method. I'm not clear about anything else you may have been asking, so if there are more changes you want, please be specific. Thanks.
