### ISSUE TITLE
Should say "read only"

### ISSUE THREAD

**Issue by ashleedawg** [MicrosoftDocs/VBA-Docs#228]
Should say "Read-only" -- like [width](https://docs.microsoft.com/office/vba/api/excel.range.width).  Also doesn't include data type, which should be "Double".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fd95e95-0447-d5cf-b7f1-f5cda6fc12d8
* Version Independent ID: 4ece7d34-f276-cc0c-7837-4db5cb6c6d8f
* Content: [Range.Height Property (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.range.height)
* Content Source: [api/Excel.Range.Height.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Range.Height.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ashleedawg 

Thanks for the feedback. To confirm, you'd like "Read-only **Double**" added to the first sentence?

**Comment by Linda-Editor** [comment]
@ashleedawg Closing this issue. Let me know if you need further changes to https://docs.microsoft.com/en-us/office/vba/api/excel.range.height.
