### ISSUE TITLE
Returns a 'Double', not a 'Variant'

### ISSUE THREAD

**Issue by ashleedawg** [MicrosoftDocs/VBA-Docs#229]
Returns a 'Double', not a 'Variant'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cf4080-a9fc-4d16-0c4b-2042fe1a798b
* Version Independent ID: 46f049b6-47e7-d9d8-9d61-fcfb94f362ba
* Content: [Range.RowHeight Property (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.range.rowheight)
* Content Source: [api/Excel.Range.RowHeight.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Range.RowHeight.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ashleedawg 
Are you asking to change this: "Read/write **Variant**" to this: "Read/write **Double**"? Please confirm. Or give me the exact string you want changed. Thanks.

**Comment by ashleedawg** [comment]
Correct, thank you.

Sorry for all the little submissions, but there seems to be a million minor mistakes since he documentation was moved over to the new system, and it’s driving my OCD batty… not to mention confusing the heck out of newbies!  😊

**Comment by Linda-Editor** [comment]
Thanks. I changed Variant to Double. Keep the submissions coming. Just be super specific because I'm just an editor cleaning up this stuff; I don't have all the background tech knowledge about everything. :-)
