### ISSUE TITLE
Returns a 'Double', not a 'Variant'

### ISSUE THREAD

**Issue by ashleedawg** [MicrosoftDocs/VBA-Docs#230]
Returns a 'Double', not a 'Variant'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 295361a9-1644-c4d4-f89c-10cc6560625d
* Version Independent ID: 23725e8a-86ca-f590-e206-137eb39901d8
* Content: [Range.ColumnWidth Property (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.range.columnwidth)
* Content Source: [api/Excel.Range.ColumnWidth.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Range.ColumnWidth.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ashleedawg 
Are you asking to change this: "Read/write **Variant**" to this: "Read/write **Double**"? Please confirm. Or give me the exact string you want changed. Thanks.

**Comment by Linda-Editor** [comment]
Based on your other response, I changed Variant to Double. Thanks for your submission.
