### ISSUE TITLE
This does not currently work when Project Name specifies a SubProject

### ISSUE THREAD

**Issue by ps-PKrueger** [MicrosoftDocs/VBA-Docs#233]
BoxSet does not currently work for subprojects. You can place the subproject name in the Project Name attribute and set the TaskID, but it does not perform the action to the box from the subproject in the Network Diagram. This has been broken since Project 2013 and is still broken in Project 2016, both in VBA and in C#/VSTO projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9687e142-5f21-d8b0-534f-7e6d16a20646
* Version Independent ID: deb55fbf-174c-9f07-e8c8-e322e7547550
* Content: [Application.BoxSet Method (Project)](https://docs.microsoft.com/en-us/office/vba/api/project.application.boxset)
* Content Source: [api/Project.Application.BoxSet.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Project.Application.BoxSet.md)
* Product: **project-server**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ps-PKrueger 
Thanks for this feedback. I added the first part of your statement as a NOTE at the end of the page. Let me know if you have any questions. Changes will be live later today.
