### ISSUE TITLE
The subprojects object becomes static if you add two subprojects with the same name to it

### ISSUE THREAD

**Issue by ps-PKrueger** [MicrosoftDocs/VBA-Docs#234]
If you add two subprojects with the same name to a project, it will become a static object, and will not provide information about any additional subprojects that are added to your project. This continues for the life of the project file, even if one of the similarly named subprojects is removed. You can try this by making a copy of one of the subprojects in your project, placing it into another folder, and then adding it to your project again. Subprojects will not report the new project, or provide information about any subprojects that are added to that project afterwards. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bab96b9-e1a9-dfd4-90d3-c05262824739
* Version Independent ID: 66aae624-dfa7-fc1b-62ec-a77cbe4c1db9
* Content: [Subprojects Object (Project)](https://docs.microsoft.com/en-us/office/vba/api/project.subprojects(object))
* Content Source: [api/Project.subprojects(object).md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Project.subprojects(object).md)
* Product: **project-server**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ps-PKrueger 

Thanks for this info. I added your comment as a NOTE at the end of the page. Changes will be live later today.
