### ISSUE TITLE
Enummeration wrong for msoElementPrimaryValueAxisTitleAdjacentToAxis

### ISSUE THREAD

**Issue by Berend-de-Vries** [MicrosoftDocs/VBA-Docs#235]
The enummeration for msoElementPrimaryValueAxisTitleAdjacentToAxis is the same as for msoElementPrimaryValueAxisTitleNone (306)
For msoElementPrimaryValueAxisTitleAdjacentToAxis this should be 307.
Is also wrong in the VBA library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7caaf1ab-f17a-470d-c7b9-3946451cc40a
* Version Independent ID: 693272ff-1b02-56f1-854b-a50099c80259
* Content: [MsoChartElementType Enumeration (Office)](https://docs.microsoft.com/en-us/office/vba/api/office.msochartelementtype)
* Content Source: [api/Office.MsoChartElementType.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Office.MsoChartElementType.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@Berend-de-Vries 
Thanks for this feedback. I changed 306 to 307 on the page you referenced, but cannot find any other instances in our documentation. Please send me links to pages where you want changes. Thanks.
