### ISSUE TITLE
fScale constant is wrong in Remarks

### ISSUE THREAD

**Issue by v2ike6udik** [MicrosoftDocs/VBA-Docs#239]
In Remarks:  "The fScale parameter value can be one of the following **MsoTriState** constants." 

Should be **MsoScaleFrom**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b9f9fd9-faf5-ca85-d9ff-dc23a0054a23
* Version Independent ID: d44d8a5f-3237-bab1-8456-b2da2c49ac45
* Content: [ShapeRange.ScaleHeight Method (PowerPoint)](https://docs.microsoft.com/en-us/office/vba/api/powerpoint.shaperange.scaleheight)
* Content Source: [api/PowerPoint.ShapeRange.ScaleHeight.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/PowerPoint.ShapeRange.ScaleHeight.md)
* Product: **powerpoint**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@v2ike6udik 
Thanks for this feedback. I've updated the sentence to: 
The _fScale_ parameter value can be one of the following **MsoScaleFrom** constants. 

Changes will be live later today.
