### ISSUE TITLE
Operator "&" page - wrong/missing link and page in vba

### ISSUE THREAD

**Issue by Vincent-SPC** [MicrosoftDocs/VBA-Docs#243]
correct link for the first concatenation operator & is missing on page https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/concatenation-operators (and I wasn't able to locate the right page)

**Comment by Linda-Editor** [comment]
@Vincent-SPC 
Thanks for the feedback. I'm not sure if that page exists. I think they want you to use the wildcard operator. But I'll see if I can find it somewhere.

**Comment by Vincent-SPC** [comment]
Operators + and & are both concatenation operators, with different behaviors with String <-> Number default implicit conversions.
![image](https://user-images.githubusercontent.com/43061877/48334442-fb28cb80-e65a-11e8-8de1-61650ebf7898.png)
 The page exist for the VB.NET documentation, ([here](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/concatenation-operator)), and as far as I can see most of programmers use & and nor + for string concatenation in VBA

**Comment by Linda-Editor** [comment]
@Vincent-SPC Thanks for the link to the VB.NET doc. Would it make sense to just copy that page and add it to the VBA content? Or should we just link to the VB.NET page?

**Comment by Vincent-SPC** [comment]
I think it would be better to copy this page: https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/aa242763(v=vs.60) which is located in VB6 documentation but labeled VBA.

**Comment by Linda-Editor** [comment]
@Vincent-SPC  I added the & page form the source you gave me, and also added pages for /, \, and - (minus), all of which were pointing to operator.md. I also updated the TOC and removed some nav pages. Changes will be live later today. Let me know if you have any questions or further comments.
