### ISSUE TITLE
Returns active Excel Window only

### ISSUE THREAD

**Issue by ashleedawg** [MicrosoftDocs/VBA-Docs#244]
Returns the active EXCEL Window, not "any" window that's on top as the description implies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e944f457-99aa-105b-02f0-30ba8f4db7c0
* Version Independent ID: c2b8a031-5a90-9934-1e78-b7fc6356a9f2
* Content: [Application.ActiveWindow Property (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.application.activewindow)
* Content Source: [api/Excel.Application.ActiveWindow.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Application.ActiveWindow.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ashleedawg 
Thanks for this feedback. I changed "the active window" to "the active Excel window" in two places. Let me know if you have any questions or other feedback. Thanks. Changes will be live later today.
