### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by auttakornG** [MicrosoftDocs/VBA-Docs#248]
documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcca1fa8-53a5-6184-0d20-f0fad2fbae59
* Version Independent ID: 021586f8-1f25-7a51-15e6-c9ee6f14ce1b
* Content: [Office VBA Reference](https://docs.microsoft.com/en-us/office/vba/api/overview/)
* Content Source: [api/overview/index.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/overview/index.md)
* Product: **vba**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@auttakornG 
Thanks for your feedback. However, we're not sure what your issue is, so we're closing it. If you're still having a problem, please re-open the issue with more information. Thanks.
