### ISSUE TITLE
Typesetting error？

### ISSUE THREAD

**Issue by raxod** [MicrosoftDocs/VBA-Docs#250]
The Event statements were wrong. Each statement requires another line.
    Public Event UpdateTime(ByVal dblJump As Double)Public Event ChangeText()
The following is right.
    Public Event UpdateTime(ByVal dblJump As Double)
    Public Event ChangeText()

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c7cf3fc3-2c8e-e3c8-1459-69a75473dc98
* Version Independent ID: f6749a82-e11b-4e29-dfae-7309fc232c70
* Content: [Event Statement](https://docs.microsoft.com/zh-cn/office/vba/language/reference/user-interface-help/event-statement)
* Content Source: [Language/Reference/User-Interface-Help/event-statement.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/event-statement.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@raxod Was this the only change, to move Public Event ChangeText() to another line? If so, I did this. Let me know if you have any questions. Updates go live later today.
