### ISSUE TITLE
ChartType Excel

### ISSUE THREAD

**Issue by infos2** [MicrosoftDocs/VBA-Docs#258]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: badd416c-3cce-c9a4-c7b4-f4d8ac488dd1
* Version Independent ID: 081861fe-3aac-7003-f20b-bad46be7993c
* Content: [XlChartType Enumeration (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.xlcharttype)
* Content Source: [api/Excel.XlChartType.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.XlChartType.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@infos2 
What is your issue? I'm closing this issue; please re-open another one if you have any feedback.
