### ISSUE TITLE
Spaces missing

### ISSUE THREAD

**Issue by ruvox** [MicrosoftDocs/VBA-Docs#259]
There are two spaces missing:
One here after these
//*[@id="main"]/p[2]/text()[5]
and the other there after compare
//*[@id="main"]/div[1]/table/tbody/tr[3]/td[2]/strong[1]/em

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 352cb4c4-a56d-c548-90c4-d33c46983634
* Version Independent ID: 0572c2e1-b8ec-3411-ff82-4d158b0c11bf
* Content: [StrComp Function](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/strcomp-function)
* Content Source: [Language/Reference/User-Interface-Help/strcomp-function.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/strcomp-function.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ruvox 
Thanks for your feedback. We're aware of these spacing issues and are fixing them as we find them. I fixed the ones on this page. No need to send us further requests about this unless you find some a few months from now. Thanks.
