### ISSUE TITLE
Wrong reference address in .xml and .rel files.

### ISSUE THREAD

**Issue by AzmL** [MicrosoftDocs/VBA-Docs#263]
I struggled for days understanding why I would not manage to get it working.
This post refers to the wrong addresses, it should be "http://" and NOT "https://". I figured out when valudating the XML.
This is true for the customUI.xml file, as well as the .rels file. 

# customUI.xml should be:
&lt;customUI xmlns="http://schemas.microsoft.com/office/2006/01/customui"&gt; 
&lt;ribbon&gt; 
  &lt;tabs&gt; 
    &lt;tab id="CustomTab" label="My Tab"&gt; 
      &lt;group id="SampleGroup" label="Sample Group"&gt; 
        &lt;button id="Button" label="Insert Company Name" size="large" onAction="ThisDocument.InsertCompanyName" /&gt; 
      &lt;/group &gt; 
    &lt;/tab&gt; 
  &lt;/tabs&gt; 
&lt;/ribbon&gt; 
&lt;/customUI&gt;

# .rel should be:
&lt;Relationship Id="someID" Type="http://schemas.microsoft.com/office/2006/relationships/ui/extensibility" target="customUI/customUI.xml" /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f45df1b9-16f4-4c5e-269c-49d0d58fa2b1
* Version Independent ID: 9d77130d-483c-20b3-119c-592e6b51dfbd
* Content: [Customize the Office Fluent Ribbon by Using an Open XML Formats File](https://docs.microsoft.com/en-us/office/vba/library-reference/concepts/customize-the-office-fluent-ribbon-by-using-an-open-xml-formats-file)
* Content Source: [Library-Reference/Concepts/customize-the-office-fluent-ribbon-by-using-an-open-xml-formats-file.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Library-Reference/Concepts/customize-the-office-fluent-ribbon-by-using-an-open-xml-formats-file.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@AzmL 
Thanks for the feedback. I changed these references to http://, and also updated other schemas links accordingly. Let me know if you have any questions.
