### ISSUE TITLE
'LET' Example

### ISSUE THREAD

**Issue by ashleedawg** [MicrosoftDocs/VBA-Docs#267]
This page should have lots more information including link to enumeration of options for  `vbCallType` (like [this](https://msdn.microsoft.com/library/ee157052.aspx)), differences between `Get`, `Let` and `Set`, and instructions for usage of the various forms of the function.

<sub>For example:</sub>

```
    Sub test()
        Dim user As userData                            'userdata = class name
        Set user = New userData
        user.user_id = "abc"
        Debug.Print CallByName(user, "user_id", VbGet)  'returns "abc"
        CallByName user, "user_id", VbLet, "xyz"
        Debug.Print user.user_id                        'returns "xyz"
    End Sub
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1824e39-6e85-b505-c4d8-6095de137e55
* Version Independent ID: eec8020c-3f3b-6ff0-c798-2e91bc4849b1
* Content: [CallByName Function](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/callbyname-function#example)
* Content Source: [Language/Reference/User-Interface-Help/callbyname-function.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/callbyname-function.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ashleedawg 
Thanks for the feedback. Feel free to submit this as a pull request with your proposed changes. Thanks.
