### ISSUE TITLE
This Article should Link to FormatCode documentation

### ISSUE THREAD

**Issue by Masterxilo** [MicrosoftDocs/VBA-Docs#282]
e.g. https://support.office.com/en-us/article/number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9684f8d-70ed-23da-0675-1701af991010
* Version Independent ID: 8e975f0c-21e5-4fe4-f9b7-4b40de47822c
* Content: [Range.NumberFormat Property (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.range.numberformat)
* Content Source: [api/Excel.Range.NumberFormat.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Range.NumberFormat.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@Masterxilo 
Thanks for the feedback. I added the support link to this page. Changes will go live in a day or so.
