### ISSUE TITLE
Is VBE documentation hosted here? If so, where?

### ISSUE THREAD

**Issue by sancarn** [MicrosoftDocs/VBA-Docs#288]
I've been looking for Visual Basic Editor Extensibility documentation for a while now and have struggled to find any decent documentation...

Are the docs hosted here? If not, should they be created here?

**Comment by Linda-Editor** [comment]
@sancarn 
It appears that the VBE topics are scattered throughout the table of contents. In the left navigation pane, enter "VBE" in the search filter to find them. Hope this helps.
