### ISSUE TITLE
Don't try this in a module

### ISSUE THREAD

**Issue by GCD56** [MicrosoftDocs/VBA-Docs#294]
For whatever reason you cannot use this from a module.
It will work with a single column but not with multiple columns, and yet if you copy the exact line used in this article or a similar one using Array()  to the code space of a sheet it will work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c798364e-7417-95a9-26a4-2a8d118dc935
* Version Independent ID: 2a7bed1a-6b0f-751f-e78e-70d0b5732030
* Content: [Range.RemoveDuplicates Method (Excel)](https://docs.microsoft.com/en-us/office/vba/api/Excel.Range.RemoveDuplicates)
* Content Source: [api/Excel.Range.RemoveDuplicates.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Range.RemoveDuplicates.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by TanBuiVan** [comment]
Pls try this:
Sub RemoveDuplicateRows()
'Demonstrates how to use the VBA RemoveDuplicates method to remove
'the duplicate rows from a particular column in a range of data.

Dim MyRange As Range
Dim LastRow As Long

LastRow = ActiveSheet.Range("A" & Rows.Count).End(xlUp).Row
Set MyRange = ActiveSheet.Range("A1:D" & LastRow)
MyRange.RemoveDuplicates Columns:=3, Header:=xlYes
End Sub

**Comment by GCD56** [comment]
Thanks for the help! I'm good now.
