### ISSUE TITLE
Where are the Object Members?

### ISSUE THREAD

**Issue by djdave238** [MicrosoftDocs/VBA-Docs#296]
I see at least 20 properties and methods in the VS2017 IDE associated with this object; why aren't *any* of them detailed here?  This documentation does not seem complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1ea1e9-2dce-8e5b-7c31-3975c6922e82
* Version Independent ID: 7f37f52d-2daa-f72b-7389-b2f4223e32ed
* Content: [File Object](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/file-object)
* Content Source: [Language/Reference/User-Interface-Help/file-object.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/file-object.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@djdave238 
Here is a link to more information: [Object library reference for Office (members, properties, methods)](https://docs.microsoft.com/office/vba/api/overview/library-reference/reference-object-library-reference-for-office)

Does this help? If not, please let me know what you expect to see. You can also use the filter at the top of the navigation pane to search for items.
