### ISSUE TITLE
semicolons

### ISSUE THREAD

**Issue by raintan** [MicrosoftDocs/VBA-Docs#298]
When I use the macro recorder in Excel Office 365, I get the same codes, but without the semicolons. If i try to use these codes with the semicolons, I get an error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5e55e0b-3b5d-9ae6-bfca-10227078ea89
* Version Independent ID: f61f8323-f35e-45df-8968-18511bfa3a49
* Content: [Formatting and VBA Codes for Headers and Footers](https://docs.microsoft.com/en-us/office/vba/excel/concepts/workbooks-and-worksheets/formatting-and-vba-codes-for-headers-and-footers)
* Content Source: [excel/Concepts/Workbooks-and-Worksheets/formatting-and-vba-codes-for-headers-and-footers.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/excel/Concepts/Workbooks-and-Worksheets/formatting-and-vba-codes-for-headers-and-footers.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@raintan 
Thank you so much for pointing this out and confirming that the semi-colons cause an error. The semi-colons were an error that happened when we migrated the content, so I've removed them from this page. Let me know if you run into any other instances like this.  The changes should be live in a day or so.
