### ISSUE TITLE
this entry needs a link to "the rest of the story" about Scripting.Dictionary

### ISSUE THREAD

**Issue by dickwatson** [MicrosoftDocs/VBA-Docs#299]
See https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/windows-scripting/x4k5wbx4(v%3dvs.84) for the complete reference information on Scripting.Dictionary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cc9bdf2-54b9-e787-dc1f-f58f83136d2b
* Version Independent ID: 73078319-88b6-e1c0-4c15-a6761fc492ae
* Content: [Dictionary Object](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/dictionary-object)
* Content Source: [Language/Reference/User-Interface-Help/dictionary-object.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/dictionary-object.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@dickwatson 
Thanks for the feedback. I added this link to the page. Changes will be live in a day or so...
