### ISSUE TITLE
Example appears corrupt

### ISSUE THREAD

**Issue by yut45390** [MicrosoftDocs/VBA-Docs#301]
It's a minor problem: "&" shows as &amp;amp;
VBA expects "&" only

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66c85d8a-59a8-5a0d-a108-754a5950f3a3
* Version Independent ID: 8f997b4d-050d-22bf-4aac-4faf2bb2052d
* Content: [Categories Object (Outlook)](https://docs.microsoft.com/en-gb/office/vba/api/outlook.categories)
* Content Source: [api/Outlook.Categories.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Outlook.Categories.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by yut45390** [comment]
And my comment got garbled, because I meant "&" shows as &amp;amp; that is &, followed by amp and followed by semicolon.

**Comment by Linda-Editor** [comment]
@yut45390  Thanks for your feedback. I've updated &amp; to &. Changes should appear live in a day or so.
