### ISSUE TITLE
Operator links point to wrong location

### ISSUE THREAD

**Issue by gary-ji** [MicrosoftDocs/VBA-Docs#302]
[Enter feedback here]
For *Operator, /Operator, \Operator and -Operator, all links point to *Operator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e27b5ff-1480-7741-2fe5-b0cb37793d2d
* Version Independent ID: 918645b0-eeb6-4c48-21e4-f57a271b404d
* Content: [Arithmetic Operators](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/arithmetic-operators)
* Content Source: [Language/Reference/User-Interface-Help/arithmetic-operators.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/arithmetic-operators.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@gary-ji I added three new pages from this source to fix the missing topics: https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/aa242772(v%3dvs.60)

Changes will be live later today. Let me know if you have any questions.
