### ISSUE TITLE
IT SPEC(INFOSEC), SR Security Architect and Engineering Support.

### ISSUE THREAD

**Issue by poundjd** [MicrosoftDocs/VBA-Docs#305]
Where is the rest of the information to allow me to use this property correctly? You know examples and the .text, .replacement. and .wrap, as well as all of the examples of how to use them in some non-trivial way!!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b777d89e-f8ef-0f2b-d701-397cbca909c9
* Version Independent ID: 530e90fb-556d-2ec8-3008-c6039f0a7cb2
* Content: [Range.Find Property (Word)](https://docs.microsoft.com/en-us/office/vba/api/word.range.find)
* Content Source: [api/Word.Range.Find.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Word.Range.Find.md)
* Product: **word**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@poundjd 
Thanks for your feedback. The other information is in the left navigation. Please use the filter option at the top of the table of contents to find what you're looking for. Hope this helps.
