### ISSUE TITLE
Code 38, two characters?

### ISSUE THREAD

**Issue by GregoryManiatis** [MicrosoftDocs/VBA-Docs#316]
The character(s) listed for code 38 are both the ampersand and the semicolon.
Should it only list one character?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f12a6fc-a985-a1db-1257-1ed66b6257ca
* Version Independent ID: 41b9c562-7791-29ef-b064-5a7fe4e9ab2e
* Content: [Character set (0 - 127)](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/character-set-0127)
* Content Source: [Language/Reference/User-Interface-Help/character-set-0127.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/character-set-0127.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by GregoryManiatis** [comment]
Related: In the doc for the Format function, [Format function (Visual Basic for Applications)](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/format-function-visual-basic-for-applications), under the section headed "User-defined string formats (Format function)," the ampersand appears twice. Both appearances have the ampersand followed by the semicolon. In the same doc, under the section headed "User-defined numeric formats (Format function)," the ampersand-semicolon appears in the description for the (\\) character as well.

The issue seems too common to be a typo. It is an artifact from an older markup language used to write the source doc?

**Comment by Linda-Editor** [comment]
@GregoryManiatis Thanks for this feedback. We did have an ampersand issue in the migration; adding the guy who helped fix these: @Kagre, can you take a look?

**Comment by Linda-Editor** [comment]
@GregoryManiatis I determined that these were a few leftovers that didn't get changed when we did a global pass to replace &; with &, so I went ahead and fixed them. Closing this bug.
