### ISSUE TITLE
Missing links to constant enumeration

### ISSUE THREAD

**Issue by ashleedawg** [MicrosoftDocs/VBA-Docs#317]
This document should include links to:
 [WdUnits Enumeration](https://docs.microsoft.com/office/vba/api/word.wdunits)
[WdMovementType Enumeration](https://docs.microsoft.com/office/vba/api/word.wdmovementtype)

Also, the code sample throughout the new documentation are often labelled "VB" when they should be labelled "VBA".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a753920a-e380-4db2-6ff8-add4b95ecd5f
* Version Independent ID: 27426772-d935-4acb-a47b-699942a25533
* Content: [Selection.EndKey Method (Word)](https://docs.microsoft.com/en-us/office/vba/api/word.selection.endkey)
* Content Source: [api/Word.Selection.EndKey.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Word.Selection.EndKey.md)
* Product: **word**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ashleedawg 
Thanks for your feedback. I've added links as you requested. Changes will be live in a day or so.
