### ISSUE TITLE
Needs link to enumeration of constants

### ISSUE THREAD

**Issue by ashleedawg** [MicrosoftDocs/VBA-Docs#318]
This document is missing a link to:
- [WdInformation Enumeration](https://docs.microsoft.com/office/vba/api/word.wdinformation)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ed7b802-0e07-1b9e-803e-7f3b79ca1359
* Version Independent ID: d5a76ad1-5e41-ac2b-e0d1-07af3514d699
* Content: [Selection.Information Property (Word)](https://docs.microsoft.com/en-us/office/vba/api/word.selection.information)
* Content Source: [api/Word.Selection.Information.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Word.Selection.Information.md)
* Product: **word**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ashleedawg 
Thank you for your feedback. I added a link to WdInformation. Changes will be live in a day or so.
