### ISSUE TITLE
Duplicated text

### ISSUE THREAD

**Issue by GregoryManiatis** [MicrosoftDocs/VBA-Docs#328]
The explanatory paragraph for the first example seems to have duplicated text that states the example will perform the beeping function twice. The code shown only performs the beeping function once and then ends.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 924e28e1-5e95-9a96-18cd-4d3af1982e28
* Version Independent ID: ac6bdb4d-fcc2-e25c-6597-eab958ac267c
* Content: [Calling Sub and Function Procedures](https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/calling-sub-and-function-procedures)
* Content Source: [Language/Concepts/Getting-Started/calling-sub-and-function-procedures.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Concepts/Getting-Started/calling-sub-and-function-procedures.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@GregoryManiatis 
Thanks for finding this bug! I'm doing a scrub of our content now, and this duplication pops up from time to time; not sure how it gets there. I've updated the markdown to the following; changes will go live in a day or so:

You can use a **Sub** procedure to organize other procedures so they are easier to understand and debug. In the following example, the **Sub** procedure `Main` calls the **Sub** procedure `MultiBeep`, passing the value 56 for its argument. 

After `MultiBeep` runs, control returns to `Main`, and `Main` calls the **Sub** procedure `Message`. `Message` displays a message box; when the user clicks **OK**, control returns to `Main`, and `Main` finishes.
