### ISSUE TITLE
uncomplete documentation

### ISSUE THREAD

**Issue by deugister** [MicrosoftDocs/VBA-Docs#332]
What is missing:
- architecture overview of the object
- lifecycle overview of the main methods
- links to all relevant sub items like methods, properties, related objects
- ..
bad stuff... but at least some documentation comes up... shhhh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2653102d-307b-ef5e-31be-67d06ff233c8
* Version Independent ID: 9114d165-d300-b262-c1a5-3fed9a86aacd
* Content: [UserForm Object](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/userform-object)
* Content Source: [Language/Reference/User-Interface-Help/userform-object.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/userform-object.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@deugister 
Thanks for your feedback. We're in the midst of upgrading the content, so will consider your suggestions in our edit pass. Thanks.
