### ISSUE TITLE
return type shows raw markdown instead of link

### ISSUE THREAD

**Issue by phanos** [MicrosoftDocs/VBA-Docs#337]
link to markdown? not rendered correctly for return type.
"expression An expression that returns a [Font](Excel.Font(Graph property).md) object."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be674a3d-0a0c-e7fd-1877-789a8dd24486
* Version Independent ID: 0b8ae0bf-d70e-f3e6-35f2-bd7826702cdc
* Content: [Font.Size Property (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.font.size)
* Content Source: [api/Excel.Font.Size.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Font.Size.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@phanos 
Thanks for your feedback. I fixed the link, and it will appear in the next live build.
