### ISSUE TITLE
Repeated Loop Keyword

### ISSUE THREAD

**Issue by HaythamAmairah** [MicrosoftDocs/VBA-Docs#35]
In the last line of the Example code, the Loop keyword is repeated, causing a compiler error!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4973425-3c29-214e-f38d-cd3f7e69cf8b
* Version Independent ID: a03ee91b-a585-c8e2-b94b-930e5108f5b8
* Content: [Do...Loop Statement](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/doloop-statement#feedback)
* Content Source: [Language/Reference/User-Interface-Help/doloop-statement.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/doloop-statement.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
Fixed in https://github.com/MicrosoftDocs/VBA-Docs/pull/42.
