### ISSUE TITLE
macro

### ISSUE THREAD

**Issue by KRISHAN0091** [MicrosoftDocs/VBA-Docs#362]
Create a list box with option buttons 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29e9f197-1dae-2741-20a6-87e7d465a3fd
* Version Independent ID: 36978bfa-2b26-753a-c238-67c866cfd1b3
* Content: [Create a list box with option buttons or check boxes](https://docs.microsoft.com/en-us/office/vba/language/concepts/forms/create-a-list-box-with-option-buttons-or-check-boxes)
* Content Source: [Language/Concepts/Forms/create-a-list-box-with-option-buttons-or-check-boxes.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Concepts/Forms/create-a-list-box-with-option-buttons-or-check-boxes.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@KRISHAN0091 
Thanks for your feedback. However, we're not sure what your issue is, so we're closing it. If you're still having a problem, please re-open the issue with more information. Thanks.
