### ISSUE TITLE
a

### ISSUE THREAD

**Issue by Maestra89** [MicrosoftDocs/VBA-Docs#365]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d9033d7-3ece-14a9-360f-626e62ad0205
* Version Independent ID: 71a3f004-546b-3238-fe0f-e4d71dd369f2
* Content: [Errors occurred during load](https://docs.microsoft.com/en-us/office/vba/Language/Reference/User-Interface-Help/errors-occurred-during-load)
* Content Source: [Language/Reference/User-Interface-Help/errors-occurred-during-load.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/errors-occurred-during-load.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@Maestra89 - I need more information to address your issue. Please open a new issue with more information. Thanks.
