### ISSUE TITLE
Scripting.FileSystemObject documentation is very poorly organized

### ISSUE THREAD

**Issue by SLaks** [MicrosoftDocs/VBA-Docs#367]
The methods on Scripting.FileSystemObject aren't listed anywhere; instead, they're scattered among a list of general methods on all objects available in VBA. (https://docs.microsoft.com/en-us/office/vba/language/reference/methods-visual-basic-for-applications)

Can you please document it like a normal class with a list of its own methods on this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ac84c35-2487-f8b5-d9ac-7702fd48d294
* Version Independent ID: 6b7905f8-077d-97fc-beba-bed4022446ec
* Content: [FileSystemObject Object](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/filesystemobject-object)
* Content Source: [Language/Reference/User-Interface-Help/filesystemobject-object.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/filesystemobject-object.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by SLaks** [comment]
Actual documentation can be found on third-party sites like https://www.w3schools.com/asp/asp_ref_filesystem.asp, which AFAIK stole this content from MSDN back when it was well-organized.

**Comment by Tomalak** [comment]
I agree with SLaks. This once had been a very well-put-together and useful documentation, it' a shame that this is no longer the case. These technologies still ship with Windows, and will be for the foreseeable future, the technical documentation had already been completely written cleanly organized. There is no reason at all to let them become this useless.

**Comment by Linda-Editor** [comment]
Thanks for these comments guys. When the content was migrated from MSDN, for some reason a lot of the organization was lost. I'm trying to restore it, but no longer have access to the MSDN version. If you're willing to work with me to let me know how you want this to look, I can try to fix it. I just need specifics (for example, send me a Word doc with the layout you're expecting). Thanks!

**Comment by SLaks** [comment]
Automatic mirror sites like W3Schools have preserved most of the structure.
At the very least, can you please add a list of all members on the various VBA / ASP objects?
For example, https://www.w3schools.com/asp/asp_ref_filesystem.asp (scroll down).

**Comment by Linda-Editor** [comment]
@SLaks @Tomalak 
Thanks for the links. I added the list of Methods and Properties that were on the web.archive.org page to the filesystemobject-object.md page. Hope this helps. Let me know if you have any questions or further requests. Changes should be live later today.

**Comment by Linda-Editor** [comment]
@Slaks @Tomalak 

FYI - I also added Methods and Properties for similar pages in the same section of the table of contents, and will continue to keep my eye out for these on other pages as I scrub the repo.
