### ISSUE TITLE
It miss a link for Variable types

### ISSUE THREAD

**Issue by RBR66** [MicrosoftDocs/VBA-Docs#369]
Please, insert a link on this to the Variable Types page. It will be much more useful.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 37530060-c4c2-cb99-7407-9ec1a0593c0c
* Version Independent ID: 80c13e2c-022a-251d-cac7-3e989e65c47b
* Content: [Declarando variáveis](https://docs.microsoft.com/pt-br/office/vba/language/concepts/getting-started/declaring-variables)
* Content Source: [Language/Concepts/Getting-Started/declaring-variables.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/live/Language/Concepts/Getting-Started/declaring-variables.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@RBR66 Thanks for the feedback. I added a link to [Data type summary](../../reference/user-interface-help/data-type-summary.md). Let me know if you're expecting something else, and if so, please send me the link. Changes will be live later today.
