### ISSUE TITLE
missing spaces

### ISSUE THREAD

**Issue by ruvox** [MicrosoftDocs/VBA-Docs#373]
There are two spaces missing. One after "buttons" here: //*[@id="main"]/p[3]/strong[2]/em
Another after "these" here: //*[@id="main"]/p[2]/text()[7]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dd5a6c8-ef54-9972-f692-cbe6c78942f2
* Version Independent ID: 3c5342c2-3e1c-f000-ea16-82067e0cac97
* Content: [MsgBox Function](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/msgbox-function)
* Content Source: [Language/Reference/User-Interface-Help/msgbox-function.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/msgbox-function.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ruvox Thanks for your feedback. I've fixed these and other issues on the page. You'll see the changes on LIVE in a few days.
