### ISSUE TITLE
Links to/from documentation

### ISSUE THREAD

**Issue by ashleedawg** [MicrosoftDocs/VBA-Docs#374]
Links from this page to the reference for the methods used in the examples would be handy.

For instance, `PutInClipboard` to `https://docs.microsoft.com/office/vba/language/reference/user-interface-help/putinclipboard-method`, and also that page should probably have a link to this one, for easy access to an example.

One example of thousands of un-linked pages in the new doc system that should be. Rather than manual updates, this should be completely across the whole site programmatically (requiring only basic logic)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1d1d2a-ea7d-81dc-7de6-b933d1081735
* Version Independent ID: c3492877-cc14-d298-2b57-97aae028027c
* Content: [Paste, PutInClipboard, SetText Methods Example](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/paste-putinclipboard-settext-methods-example)
* Content Source: [Language/Reference/User-Interface-Help/paste-putinclipboard-settext-methods-example.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/paste-putinclipboard-settext-methods-example.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ashleedawg 
Per your request, I updated all the [examples under Microsoft Forms](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/examples-microsoft-forms) with links to the properties, methods, etc. I also cleaned up all the formatting on the properties, methods, etc. pages (everything under Microsoft Forms), and added links to the top examples page. Sorry that I didn't link each property to its corresponding example, but I don't have the bandwidth for that. Let me know if you have any questions.
