### ISSUE TITLE
eng

### ISSUE THREAD

**Issue by newnana** [MicrosoftDocs/VBA-Docs#376]
nocommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4529e26b-bd7b-a1c1-8043-0eb01b9a2009
* Version Independent ID: 56362f71-7606-df89-811c-a2244cdf15fc
* Content: [Method or data member not found (Error 461)](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/method-or-data-member-not-found-error-461)
* Content Source: [Language/Reference/User-Interface-Help/method-or-data-member-not-found-error-461.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/method-or-data-member-not-found-error-461.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@newnana 
Thanks for your feedback. However, we're not sure what your issue is, so we're closing it. If you're still having a problem, please re-open the issue with more information. Thanks.
