### ISSUE TITLE
first sentence inconsistent with itself

### ISSUE THREAD

**Issue by dickwatson** [MicrosoftDocs/VBA-Docs#392]
says: "Returns or sets the author of the comment. Read-only String ."

Should say:

"Returns the author of the comment. Read-only String."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8cfefe8-1e5e-c048-cee1-821df6591367
* Version Independent ID: 2ce46ce2-8042-b60d-b555-50832763c2dd
* Content: [Comment.Author Property (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.comment.author)
* Content Source: [api/Excel.Comment.Author.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Comment.Author.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@dickwatson 

Thanks. I updated the text to remove "or sets." Changes should be live later today.
