### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by iceworld00** [MicrosoftDocs/VBA-Docs#394]
This function is useful in error handling sections of the code where you are not sure whether an object was instantiated before the error occured and let's say for example you want to close it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfc2726f-e67a-4549-874b-59cc8286ed35
* Version Independent ID: f6490785-1472-22e8-888b-3f236fc59008
* Content: [IsObject Function](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/isobject-function)
* Content Source: [Language/Reference/User-Interface-Help/isobject-function.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/isobject-function.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@iceworld00 
Thanks for the feedback. I added this as a note on the page. Changes will go live later today.
