### ISSUE TITLE
error

### ISSUE THREAD

**Issue by feifan1996** [MicrosoftDocs/VBA-Docs#399]
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0e42d3bb-a2dd-4f4a-a12d-6e2817727ffd
* Version Independent ID: 528bb34c-5e0a-d434-b93a-0fc3b407fe93
* Content: [自动化错误（错误 440）](https://docs.microsoft.com/zh-cn/office/vba/language/reference/user-interface-help/automation-error-error-440?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev11.query%3FappId%3DDev11IDEF1%26l%3Dzh-CN%26k%3Dk(vblr6.chm1000440)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv16)%26rd%3Dtrue)
* Content Source: [Language/Reference/User-Interface-Help/automation-error-error-440.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/live/Language/Reference/User-Interface-Help/automation-error-error-440.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
Thanks for your feedback. However, we're not sure what your issue is, so we're closing it. If you're still having a problem, please re-open the issue with more information. Thanks.
