### ISSUE TITLE
very good

### ISSUE THREAD

**Issue by yinpaizhu** [MicrosoftDocs/VBA-Docs#40]
English is not very good, how can I find the previous Chinese version?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 458b36e8-23f2-1b45-eb3d-721c5a449a48
* Version Independent ID: 80f84021-025c-e52c-94aa-674631e97fb6
* Content: [Range Object (Excel)](https://docs.microsoft.com/zh-cn/office/vba/api/excel.range(object)#feedback)
* Content Source: [api/Excel.Range(object).md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Range(object).md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
@yinpaizhu You can find the list of previous versions in Chinese here:
https://docs.microsoft.com/zh-CN/previous-versions/office/

To locate Chinese version of a topic, in the URL replace "en-US" with "zh-CN"
