### ISSUE TITLE
WHAT a USELESS WebSite !

### ISSUE THREAD

**Issue by RobinClay** [MicrosoftDocs/VBA-Docs#41]
I cannot BELIEVE how USELESS this whole arrangement is !!!

I have Excel.  
I have a need for an explanation of e.g. the use of a particular function.  
I click on "Help" and get sent to this USELESS WebSite !

e.g. here:-
https://docs.microsoft.com/en-us/office/vba/api/overview/excel
I am told that 
"This reference contains conceptual overviews, programming tasks, samples, and references to help you develop Excel solutions."
and it shows "Concepts", "How to" and "Reference" - but taht is all !  No Links, NOTHING.  And not even a HINT as to how to access these !

1/10 - not even trying.
 Bottom of the class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1346c144-90c6-3c01-b2f7-555910efc581
* Version Independent ID: 101b99a2-ed7c-879f-36ca-2b9c439f6afe
* Content: [Excel VBA reference](https://docs.microsoft.com/en-us/office/vba/api/overview/excel)
* Content Source: [api/overview/Excel.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/overview/Excel.md)
* Product: **vba**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
Hi Robin, we're sorry that you're having a bad experience with the user interface of our site. Have you tried clicking through the table of contents (TOC) in the left navigation pane? You can also add a keyword in the "Filter by title" box at the top of the TOC to help you find what you're looking for. Hope this helps.
