### ISSUE TITLE
Missing s

### ISSUE THREAD

**Issue by ruvox** [MicrosoftDocs/VBA-Docs#411]
There is an 's' missing after 'show' in the first line there: //*[@id="main"]/p[15]/text()[1]
It should be "The following example shows ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3863a487-9d92-6aec-2768-01dc3a6197f0
* Version Independent ID: 67a01bc1-ddcc-3cef-2b27-09c9e9325e1c
* Content: [ComboBox.ColumnWidths property (Access)](https://docs.microsoft.com/en-us/office/vba/api/access.combobox.columnwidths)
* Content Source: [api/Access.ComboBox.ColumnWidths.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Access.ComboBox.ColumnWidths.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
Fixed in https://github.com/MicrosoftDocs/VBA-Docs/pull/412. Please only submit a PR OR an Issue for the same item; you don't need to submit it twice.
