### ISSUE TITLE
Why not to put a link to the VBA Functions section here?

### ISSUE THREAD

**Issue by RBR66** [MicrosoftDocs/VBA-Docs#415]
The VBA Help is very confusing in some aspects. For instance, there are at least three pages with instructions about Excel functions. But, where is the page for VBA Functions? I know that it exists but, thinking in the user experience, I ask you to put a link in every one of the Excel Functions pages to VBA Functions page.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5f88fcfb-22e3-83e6-d03d-daf28f71f233
* Version Independent ID: 6decbd5e-11cc-e6ab-2840-34a255bf32ae
* Content: [Usando Funções de Planilha do Excel no Visual Basic](https://docs.microsoft.com/pt-br/office/vba/excel/concepts/events-worksheetfunctions-shapes/using-excel-worksheet-functions-in-visual-basic)
* Content Source: [excel/Concepts/Events-WorksheetFunctions-Shapes/using-excel-worksheet-functions-in-visual-basic.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/live/excel/Concepts/Events-WorksheetFunctions-Shapes/using-excel-worksheet-functions-in-visual-basic.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by retailcoder** [comment]
The term "VBA functions" is itself ambiguous. The page is about *using* `Excel.WorksheetFunction`, which has nothing to do with anything defined in the VBA standard library.

On the other hand, I fully agree the organisation is confusing - for example the page for the [MsgBox function](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/msgbox-function.md) is under **language/reference/user-interface-help** (which seems to be what the F1 key takes you to), when it would be clearer under **language/reference/standard-library/interaction** (the function is defined in the `VBA.Interaction` module).

If you're looking for the [`Function` statement](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/function-statement.md), it's also under **/user-interface-help**, which [only lists the first 1000 files](https://github.com/MicrosoftDocs/VBA-Docs/tree/master/Language/Reference/User-Interface-Help), making it hard to navigate with the GitHub UI - but then again, it seems these pages are meant to be fetched with F1-help, not browsed from GitHub.

I don't think linking to "VBA functions" from the "Excel.WorksheetFunction" page would be an improvement however; the Excel type library is one thing, the VBA type library is another entirely different thing. F1-help is one thing, and "concepts" pages are another thing.

Did you know you could browse all referenced type libraries with the *Object Browser* by hitting <kbd>F2</kbd> while inside the VBE? Once you find the specific function you're looking for, researching documentation for it should be easier: simply search for its fully-qualified name (e.g. "VBA.Information.Err")... although that might not necessarily land you on MS-Docs.

Hope it helps!

**Comment by Linda-Editor** [comment]
@RBR66 @retailcoder 

Thanks for this info. I added this link to some pages: - [Excel functions (by category)](https://support.office.com/article/excel-functions-by-category-5f91f4e9-7b42-46d2-9bd1-63f26a86c0eb)

If you come up with anything else, let me know. Thanks.
