### ISSUE TITLE
VBA Code Wildly Inaccurate

### ISSUE THREAD

**Issue by ctstewar** [MicrosoftDocs/VBA-Docs#418]
The code listed above has several errors, and the Microsoft provided support tools for VBA are generally unhelpful and incorrect.

Corrected code:

Dim objEmbedded As Object 
 
Documents.Add 

Set objEmbedded = ActiveDocument.Shapes _
  .AddOLEObject(ClassType:="Word.Document")
objEmbedded.OLEFormat.Activate
Selection.TypeText "Test"
objEmbedded.OLEFormat.ConvertTo _
  ClassType:="Word.Picture"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312c8c1d-67ee-3352-570e-b296780c0a23
* Version Independent ID: aa7fbc88-9d1b-c86c-13fa-4c5d7601281f
* Content: [OLEFormat.ConvertTo method (Word)](https://docs.microsoft.com/en-us/office/vba/api/word.oleformat.convertto)
* Content Source: [api/Word.OLEFormat.ConvertTo.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Word.OLEFormat.ConvertTo.md)
* Product: **word**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by brreich** [comment]
To clarify the issue here, the online documentation has 
objEmbedded.Activate
instead of
objEmbedded.OLEFormat.Avtivate

**Comment by ctstewar** [comment]
No, that is not the only issue here, and you've spelled "Activate" wrong in the last line of your comment. 
- objEmbedded.Activate becomes objEmbedded.OLEFormat.Activate
- objEmbedded.OLEFormat.OLEFormat.ConvertTo _  becomes objEmbedded.OLEFormat.ConvertTo _

**Comment by Linda-Editor** [comment]
@brreich If you approve these changes, I can make them in the documentation.

**Comment by Linda-Editor** [comment]
@ctstewar and @brreich - Thanks for the input. I updated the code to the following, and changes will be live by EOD. Let me know if you have any questions.

```vb
Dim objEmbedded As Object 
 
Documents.Add 
 
Set objEmbedded = ActiveDocument.Shapes _ 
  .AddOLEObject(ClassType:= "Word.Document") 
objEmbedded.OLEFormat.Activate 
Selection.TypeText "Test" 
objEmbedded.OLEFormat.ConvertTo _ 
  ClassType:="Word.Picture"

```
