### ISSUE TITLE
Well that was helpful!

### ISSUE THREAD

**Issue by russbroom** [MicrosoftDocs/VBA-Docs#435]
What?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d110c23b-34ae-c86c-fe4a-759a7039a617
* Version Independent ID: 90f9cb28-5cf2-d5c4-9a69-4da4b6fb3f39
* Content: [Overflow (Error 6)](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/overflow-error-6)
* Content Source: [Language/Reference/User-Interface-Help/overflow-error-6.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/overflow-error-6.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@russbroom If you'd like us to address this, we need more information about the problem you're having. If you'd like to provide that, you can reopen this issue.
