### ISSUE TITLE
more linkage for the user to follow.

### ISSUE THREAD

**Issue by poundjd** [MicrosoftDocs/VBA-Docs#474]
This description was among the better ones that I have seen here,  The issue that would make it and all of your other help pages better would be to  link every one of the usages of KEY words, TYPES, Objects, methods, and so on, back to their definition Pages and to expound on those with more examples where they, the examples are thoroughly explained would help a lot.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54711c82-54da-7530-eb5b-0541b5dd0b19
* Version Independent ID: 47013abf-144d-bd31-0344-3adad9b53032
* Content: [Property Set Statement](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/property-set-statement)
* Content Source: [Language/Reference/User-Interface-Help/property-set-statement.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/property-set-statement.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@poundjd Thanks for the feedback. I am going through a clean-up of the VBA site, and will consider your request as I'm making updates.

**Comment by poundjd** [comment]
Please ensure that you understand that some of us are using this resource to LEARN VBA and VB as well as object coding as well.  So the more info the better, especially the examples.

**Comment by Linda-Editor** [comment]
@poundjd Thanks again for the feedback. I can't help with the examples, but as I'm scrubbing the documentation, I'm adding links where I can.
