### ISSUE TITLE
404 error on link

### ISSUE THREAD

**Issue by rmunozblay** [MicrosoftDocs/VBA-Docs#512]
Received a 404 error when clicking the link 
Forms: Populate Controls/Text Boxes Based on Combobox Selection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cba3b76-72e5-86e7-0bb9-09490e891033
* Version Independent ID: 78ba0491-8ba1-23fd-6aa7-da4685d1328a
* Content: [Form object (Access)](https://docs.microsoft.com/en-us/office/vba/api/access.form)
* Content Source: [api/Access.Form.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Access.Form.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@rmunozblay Thanks for reporting this broken link. It appears that all the pages linked to in that section were taken down on the Utter Access site, so I removed the section. Let me know if you have any questions.
