### ISSUE TITLE
Feedback on poorly edited articles

### ISSUE THREAD

**Issue by DiamondKnight23** [MicrosoftDocs/VBA-Docs#519]
Please, please... can't anyone just do some QC? Take a look at the finished product, as we see it. I'm sure you'll see what's wrong with it. It takes me way too long to find what I'm looking for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 627fc40f-1379-257b-c31c-491b1e414c8d
* Version Independent ID: 77cb55a3-70c8-f475-bb70-ba8becab53ba
* Content: [OnGotFocus Property, Access \[vbaac10.chm4090\]](https://docs.microsoft.com/en-us/office/vba/f1/ongotfocus-property-access-vbaac10-chm4090?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev11.query%3FappId%3DDev11IDEF1%26l%3Den-US%26k%3Dk(vbaac10.chm4090)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv16)%26rd%3Dtrue)
* Content Source: [F1/ongotfocus-property-access-vbaac10-chm4090.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/F1/ongotfocus-property-access-vbaac10-chm4090.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@DiamondKnight23 There are about 50,000 files in this repo, and we are getting to these one-by-one. When we migrated this content, it introduced these formatting issues. Just be patient. Thanks.

**Comment by DiamondKnight23** [comment]
Hey Linda,

I just went to the page “OnGotFocus property, Access - [vbaac10.chm4090]”
& it looks great!
Ok, that’s the good news. Now got the pain in the arse request... any chance the list could be alphabetized? It’d make it even easier & quicker to find the option you’re looking for.

Rick

**Comment by Linda-Editor** [comment]
@DiamondKnight23  Done. Changes will be live later today.

**Comment by DiamondKnight23** [comment]
Hi Linda,

Let me start by saying I really appreciate what you do. I’m sure it’s not easy.
Also, if I ever get to be too much of a pain, please tell me.

I’m not even sure if this would be something you have control over, but I thought I’d mention it.
When in the design of a form in 2016 Access, I pressed F1 while in the BorderStyle of the form. I was taken to this URL...
> https://docs.microsoft.com/en-us/office/vba/api/Access.Attachment.BorderStyle

and I think I should have been taken here...
> https://docs.microsoft.com/en-us/office/vba/api/access.form.borderstyle


Thanks,
Rick Haney
