### ISSUE TITLE
 Calling Information on a Range duplicated from the Selection unselects the selection

### ISSUE THREAD

**Issue by ccbosch** [MicrosoftDocs/VBA-Docs#52]
Calling Information on a Range duplicated from the Selection unselects the selection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba3d05b6-68ae-4be8-b683-ce5f2e220fd8
* Version Independent ID: 9de06d64-f33e-51ff-17ea-3c7796e2ed5c
* Content: [Range.Information Property (Word)](https://docs.microsoft.com/en-us/office/vba/api/word.range.information)
* Content Source: [api/Word.Range.Information.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Word.Range.Information.md)
* Product: **word**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ccbosch Are you still experiencing this issue? If so, please re-open this issue with more information about how to solve it. Thanks.
