### ISSUE TITLE
Excellent

### ISSUE THREAD

**Issue by Kbrq** [MicrosoftDocs/VBA-Docs#526]
Exactly what I needed. Thumbs up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9213bc42-83b0-978a-b947-be8feb13008c
* Version Independent ID: ee256776-e115-b4db-c79d-78c2763e6470
* Content: [Send information to the Clipboard](https://docs.microsoft.com/en-us/office/vba/access/concepts/windows-api/send-information-to-the-clipboard)
* Content Source: [access/Concepts/Windows-API/send-information-to-the-clipboard.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/access/Concepts/Windows-API/send-information-to-the-clipboard.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@Kbrq Thanks for the positive feedback. :-)
