### ISSUE TITLE
Incomplete value set

### ISSUE THREAD

**Issue by minhcatx** [MicrosoftDocs/VBA-Docs#527]
This enumeration is used by Excel PivotField.AutoSortOrder that also includes value xlManual = -4135 (actually its default value)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bdfa86a-81e8-5c00-a36a-9403c5492338
* Version Independent ID: 46e2d7ab-9faa-88e4-a986-a1a477efae06
* Content: [xlSortOrder enumeration (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.xlsortorder)
* Content Source: [api/Excel.XlSortOrder.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.XlSortOrder.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@minhcatx So...can you be specific about what you'd like to see in the documentation? I'm an editor who can update the documentation, but I'm not a developer, so I need this clarification from you in order to move forward. Thanks...

**Comment by minhcatx** [comment]
You already have the 2 entries xlAscending with value 1 and xlDescending
with value 2.  I suggest you add a 3rd entry, name xlManual, value -4135,
Description "Manual sort (you can drag items to rearrange them)".

Thanks for the quick response.
Minh Nguyen
Director, Business Process Engineering
Aviat Networks

**Comment by Linda-Editor** [comment]
@minhcatx Thanks for your contribution. I updated the topic. It should be live in a few hours.
