### ISSUE TITLE
Return type

### ISSUE THREAD

**Issue by srldaniel** [MicrosoftDocs/VBA-Docs#537]
What is the return type of the Count function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccefe740-2453-f86d-8920-5c05bd123d78
* Version Independent ID: 402b0814-2f43-7e7c-7913-961e21ce36f4
* Content: [Count Property (FileSystemObject object)](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/count-property-filesystemobject-object)
* Content Source: [Language/Reference/User-Interface-Help/count-property-filesystemobject-object.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/count-property-filesystemobject-object.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by barnam3** [comment]
object.Count returns a Long

**Comment by Linda-Editor** [comment]
Updated description at count-property-dictionary-object (which is where the link above redirects to).
