### ISSUE TITLE
It would be helpfull to list actual color values in addition.

### ISSUE THREAD

**Issue by LokiMidgard** [MicrosoftDocs/VBA-Docs#544]
I currently translating some code that used to manipulate word documents, to also manipulate html pages.

I would like to use the same colors as the code I got. For that it would have been helpfull if the documentation not only lists the name of the color, but also the exact rgb values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 700b3235-232e-dcaa-50b0-cb700cfe00d8
* Version Independent ID: 7c91d9bc-3983-f57f-f6b7-e8ebb96841af
* Content: [WdColor enumeration (Word)](https://docs.microsoft.com/en-us/office/vba/api/word.wdcolor)
* Content Source: [api/Word.WdColor.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Word.WdColor.md)
* Product: **word**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@LokiMidgard Thanks for this suggestion. I'd be happy to add the RGB values but don't know what they are. Is there a reference I can use to match the RGB values with the existing values?

**Comment by LokiMidgard** [comment]
@Linda-Editor Unfortunately I don't know where those values are defined.

**Comment by barnam3** [comment]
Name | Decimal | Description | HEX | R | G | B
-- | -- | -- | -- | -- | -- | --
wdColorAqua | 13421619 | Aqua color. | #33CCCC | 51 | 204 | 204
wdColorAutomatic | -16777216 | Automatic color. Default; usually black. | #000000 | 0 | 0 | 0
wdColorBlack | 0 | Black color. | #000000 | 0 | 0 | 0
wdColorBlue | 16711680 | Blue color. | #0000FF | 0 | 0 | 255
wdColorBlueGray | 10053222 | Blue-gray color. | #666699 | 102 | 102 | 153
wdColorBrightGreen | 65280 | Bright green color. | #00FF00 | 0 | 255 | 0
wdColorBrown | 13209 | Brown color. | #993300 | 153 | 51 | 0
wdColorDarkBlue | 8388608 | Dark blue color. | #000080 | 0 | 0 | 128
wdColorDarkGreen | 13056 | Dark green color. | #003300 | 0 | 51 | 0
wdColorDarkRed | 128 | Dark red color. | #800000 | 128 | 0 | 0
wdColorDarkTeal | 6697728 | Dark teal color. | #003366 | 0 | 51 | 102
wdColorDarkYellow | 32896 | Dark yellow color. | #808000 | 128 | 128 | 0
wdColorGold | 52479 | Gold color. | #FFCC00 | 255 | 204 | 0
wdColorGray05 | 15987699 | Shade 05 of gray color. | #F3F3F3 | 243 | 243 | 243
wdColorGray10 | 15132390 | Shade 10 of gray color. | #E6E6E6 | 230 | 230 | 230
wdColorGray125 | 14737632 | Shade 125 of gray color. | #E0E0E0 | 224 | 224 | 224
wdColorGray15 | 14277081 | Shade 15 of gray color. | #D9D9D9 | 217 | 217 | 217
wdColorGray20 | 13421772 | Shade 20 of gray color. | #CCCCCC | 204 | 204 | 204
wdColorGray25 | 12632256 | Shade 25 of gray color. | #C0C0C0 | 192 | 192 | 192
wdColorGray30 | 11776947 | Shade 30 of gray color. | #B3B3B3 | 179 | 179 | 179
wdColorGray35 | 10921638 | Shade 35 of gray color. | #A6A6A6 | 166 | 166 | 166
wdColorGray375 | 10526880 | Shade 375 of gray color. | #A0A0A0 | 160 | 160 | 160
wdColorGray40 | 10066329 | Shade 40 of gray color. | #999999 | 153 | 153 | 153
wdColorGray45 | 9211020 | Shade 45 of gray color. | #8C8C8C | 140 | 140 | 140
wdColorGray50 | 8421504 | Shade 50 of gray color. | #808080 | 128 | 128 | 128
wdColorGray55 | 7566195 | Shade 55 of gray color. | #737373 | 115 | 115 | 115
wdColorGray60 | 6710886 | Shade 60 of gray color. | #666666 | 102 | 102 | 102
wdColorGray625 | 6316128 | Shade 625 of gray color. | #606060 | 96 | 96 | 96
wdColorGray65 | 5855577 | Shade 65 of gray color. | #595959 | 89 | 89 | 89
wdColorGray70 | 5000268 | Shade 70 of gray color. | #4C4C4C | 76 | 76 | 76
wdColorGray75 | 4210752 | Shade 75 of gray color. | #404040 | 64 | 64 | 64
wdColorGray80 | 3355443 | Shade 80 of gray color. | #333333 | 51 | 51 | 51
wdColorGray85 | 2500134 | Shade 85 of gray color. | #262626 | 38 | 38 | 38
wdColorGray875 | 2105376 | Shade 875 of gray color. | #202020 | 32 | 32 | 32
wdColorGray90 | 1644825 | Shade 90 of gray color. | #191919 | 25 | 25 | 25
wdColorGray95 | 789516 | Shade 95 of gray color. | #0C0C0C | 12 | 12 | 12
wdColorGreen | 32768 | Green color. | #008000 | 0 | 128 | 0
wdColorIndigo | 10040115 | Indigo color. | #333399 | 51 | 51 | 153
wdColorLavender | 16751052 | Lavender color. | #CC99FF | 204 | 153 | 255
wdColorLightBlue | 16737843 | Light blue color. | #3366FF | 51 | 102 | 255
wdColorLightGreen | 13434828 | Light green color. | #CCFFCC | 204 | 255 | 204
wdColorLightOrange | 39423 | Light orange color. | #FF9900 | 255 | 153 | 0
wdColorLightTurquoise | 16777164 | Light turquoise color. | #CCFFFF | 204 | 255 | 255
wdColorLightYellow | 10092543 | Light yellow color. | #FFFF99 | 255 | 255 | 153
wdColorLime | 52377 | Lime color. | #99CC00 | 153 | 204 | 0
wdColorOliveGreen | 13107 | Olive green color. | #333300 | 51 | 51 | 0
wdColorOrange | 26367 | Orange color. | #FF6600 | 255 | 102 | 0
wdColorPaleBlue | 16764057 | Pale blue color. | #99CCFF | 153 | 204 | 255
wdColorPink | 16711935 | Pink color. | #FF00FF | 255 | 0 | 255
wdColorPlum | 6697881 | Plum color. | #993366 | 153 | 51 | 102
wdColorRed | 255 | Red color. | #FF0000 | 255 | 0 | 0
wdColorRose | 13408767 | Rose color. | #FF99CC | 255 | 153 | 204
wdColorSeaGreen | 6723891 | Sea green color. | #339966 | 51 | 153 | 102
wdColorSkyBlue | 16763904 | Sky blue color. | #00CCFF | 0 | 204 | 255
wdColorTan | 10079487 | Tan color. | #FFCC99 | 255 | 204 | 153
wdColorTeal | 8421376 | Teal color. | #008080 | 0 | 128 | 128
wdColorTurquoise | 16776960 | Turquoise color. | #00FFFF | 0 | 255 | 255
wdColorViolet | 8388736 | Violet color. | #800080 | 128 | 0 | 128
wdColorWhite | 16777215 | White color. | #FFFFFF | 255 | 255 | 255
wdColorYellow | 65535 | Yellow color. | #FFFF00 | 255 | 255 | 0

**Comment by Linda-Editor** [comment]
@barnam3 Hi, thanks for submitting this. Can you submit these updates as a pull request instead? We can then just merge it. Thanks!

**Comment by barnam3** [comment]
I don't know how to do that... but I'm sure I can figure it out.

**Comment by Linda-Editor** [comment]
@barnam3 See the instructions here: https://github.com/MicrosoftDocs/VBA-Docs/blob/master/contributing.md

**Comment by barnam3** [comment]
@Linda-Editor How does this issue get closed?

**Comment by Linda-Editor** [comment]
@barnam3 I'll close it now. Thanks for your contribution!

**Comment by barnam3** [comment]
Sure thing - thanks for the encouragement ;-)
