### ISSUE TITLE
Provide an example of vba  find and replace 

### ISSUE THREAD

**Issue by qt3m45su0najc7** [MicrosoftDocs/VBA-Docs#549]
Use case: cells containing arbitrarily repeated strings (e.g., multiple spaces that you would like reduced to a single space).  Wildcard characters do not support this kind of pattern matching.  Suitable examples are very difficult to find.  For the example, use something visible like '#'. The loop would be: 

Dim results as object
 Columns("c:c").Select 'arbitrarily selected column c to perform replacement on

    Do
            Selection.Replace What:="##", Replacement:="#", LookAt:=xlPart, _

        SearchOrder:=xlByRows, MatchCase:=False, SearchFormat:=False, _
        ReplaceFormat:=False
        Set results = Selection.Find("##")
        Loop While Not results Is Nothing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 887c0d0a-9936-e2b4-98dd-88d9fdcd3818
* Version Independent ID: 382a45f8-d13d-3efa-45cf-b431d28a2409
* Content: [Range.Replace method (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.range.replace)
* Content Source: [api/Excel.Range.Replace.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Range.Replace.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@qt3m45su0najc7 Thanks for the feedback. Does the following topic address your request? If not, let us know... https://docs.microsoft.com/en-us/office/vba/api/excel.range.find
