### ISSUE TITLE
should show versions 

### ISSUE THREAD

**Issue by BillPennock** [MicrosoftDocs/VBA-Docs#550]
this should show the versions it works with.  With office 16 the command
 Dim cmbShortcutMenu As Office.CommandBar 
fails

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23b1e9e0-1284-e545-908b-680e8c92353d
* Version Independent ID: ec153220-a2a8-5884-cd1f-05f4c1c0734d
* Content: [Create a shortcut menu for a form, form control, or report](https://docs.microsoft.com/en-us/office/vba/access/Concepts/Miscellaneous/create-a-shortcut-menu-for-a-form-form-control-or-report)
* Content Source: [access/Concepts/Miscellaneous/create-a-shortcut-menu-for-a-form-form-control-or-report.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/access/Concepts/Miscellaneous/create-a-shortcut-menu-for-a-form-form-control-or-report.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@BillPennock Thanks for the feedback. In the second paragraph, it mentions Access 2013, but I also just added it to the top of the page. See the following page for other shortcut menu resources (just search on shortcut menu in the list): https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/concepts-microsoft-forms 

Hope this helps.
