### ISSUE TITLE
No example of Option Compare Database

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/VBA-Docs#551]
You have the example of Option Compare Binary and Option Compare Text but where is the example of Option Compare Database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee232b11-46a2-6732-9c5e-4bb7c745132f
* Version Independent ID: 6514967c-d56c-ff26-22da-269f99b22ad1
* Content: [Option Compare statement (VBA)](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/option-compare-statement)
* Content Source: [Language/Reference/User-Interface-Help/option-compare-statement.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/option-compare-statement.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@chanmmn Thanks for the feedback. However, there doesn't appear to be a sample for this; perhaps because it can only be used in Access? Even in our previous docs at https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/aa266181(v%3dvs.60), there wasn't an example.
