### ISSUE TITLE
Missing example or old remark

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/VBA-Docs#552]
In the Remarks section it says "For example, in the following expression, A ( result ) equals 5" but the example expression is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 931ade49-e1d3-8f94-a904-d71ccdbfc660
* Version Independent ID: 9f808274-2b5a-55d9-35e0-7d031101b648
* Content: [Mod operator](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/mod-operator?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev11.query%3FappId%3DDev11IDEF1%26l%3Den-US%26k%3Dk(vblr6.chm1008976)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv16)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396)
* Content Source: [Language/Reference/User-Interface-Help/mod-operator.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/mod-operator.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@EddieLotter  Good catch, Eddie! I was able to locate the expression on our previous documentation, and updated the page. Let me know if you find any more of these.... Changes will be live later today.
