### ISSUE TITLE
Add more details

### ISSUE THREAD

**Issue by kinetikGitHub** [MicrosoftDocs/VBA-Docs#554]
Add:
The root of these registry settings is:
Computer\HKEY_CURRENT_USER\Software\VB and VBA Program Settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6564d2e5-8be3-0aa5-64be-28aebbc38a4e
* Version Independent ID: f0a86ee0-dfa9-4788-d05b-7a0e8e33e12b
* Content: [SaveSetting statement (VBA)](https://docs.microsoft.com/en-us/office/vba/Language/Reference/user-interface-help/savesetting-statement)
* Content Source: [Language/Reference/User-Interface-Help/savesetting-statement.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/savesetting-statement.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@kinetikGitHub Thanks for the feedback. Where on the page do you want this added?

**Comment by kinetikGitHub** [comment]
I would put it in the Remarks section.

Tom van Stiphout
Software Development Manager – Kinetik I.T., Inc.
P 602-957-0058 | www.kinetik-it.com<http://www.kinetik-it.com/>

**Comment by Linda-Editor** [comment]
@kinetikGitHub Done. Changes will be live later today.
