### ISSUE TITLE
Property incorrectly stated as R/O

### ISSUE THREAD

**Issue by JamieG-UK** [MicrosoftDocs/VBA-Docs#559]
The property is R/W (tested with O365/PowerPoint V1901 B11128.20000)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8dd9f13-c9c9-6633-d51e-854c717d8da7
* Version Independent ID: d0b56c13-a34d-79e8-5c07-252110f91d35
* Content: [MotionEffect.Path Property (PowerPoint)](https://docs.microsoft.com/en-us/office/vba/api/powerpoint.motioneffect.path)
* Content Source: [api/PowerPoint.MotionEffect.Path.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/PowerPoint.MotionEffect.Path.md)
* Product: **powerpoint**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@JamieG-UK Thanks for catching this. I updated the doc to "Read/write." Changes will be live later today.
