### ISSUE TITLE
How big is a twip? 

### ISSUE THREAD

**Issue by llewellyndg** [MicrosoftDocs/VBA-Docs#569]
How big is a twip? This article makes NO SENSE if you do not explain this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 399e5b3b-5167-c491-10af-80999d206fd9
* Version Independent ID: 4b399e9a-2f79-aedf-13fd-193cf6f5b6d2
* Content: [TextBox.ColumnWidth property (Access)](https://docs.microsoft.com/en-us/office/vba/api/access.textbox.columnwidth)
* Content Source: [api/Access.TextBox.ColumnWidth.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Access.TextBox.ColumnWidth.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@llewellyndg Thanks for pointing this out. I'll add a link to the glossary entry, which states the following: "A unit of screen measurement equal to 1/20 point. A twip is a screen-independent unit used to ensure that placement and proportion of screen elements in your screen application are the same on all display systems. There are approximately 1440 twips to a logical inch or 567 twips to a logical centimeter (the length of a screen item measuring one inch or one centimeter when printed)."

https://docs.microsoft.com/en-us/office/vba/language/glossary/vbe-glossary#twip
