### ISSUE TITLE
Grammatical error in the opening paragraph

### ISSUE THREAD

**Issue by Webbarrr** [MicrosoftDocs/VBA-Docs#57]
Should be a space between "these" & "arguments"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8491870-0736-38b3-d6f3-783b08c02dd2
* Version Independent ID: dbe5fc99-e9a2-a3c3-3628-4517f28dd945
* Content: [InStr Function](https://docs.microsoft.com/en-us/office/vba/Language/Reference/User-Interface-Help/instr-function)
* Content Source: [Language/Reference/User-Interface-Help/instr-function.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/instr-function.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
Fixed and also made some other formatting updates. Thanks for contributing!

**Comment by Linda-Editor** [comment]
Change is live: https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/instr-function
