### ISSUE TITLE
"not all Visual Basic host applications can create objects"

### ISSUE THREAD

**Issue by retailcoder** [MicrosoftDocs/VBA-Docs#575]
That remark is vaguely correct, but rather confusing:

> Not all Visual Basic host applications can create objects. See your host application's documentation to determine whether it can create classes and objects.

The remark is *version-specific*, not *host-specific* - and should mention it. Something like:

> Hosts running Visual Basic for Applications earlier than version 4.0 cannot create objects; `Err` being a function returning an `ErrObject` instance, it cannot be used in these early versions. Refer to the 'About' dialog of your Visual Basic Editor (VBE) to know what version of VBA your host application is running.

Assuming all VBE versions have that "About Microsoft Visual Basic for Applications" menu command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af331826-64e8-e447-1891-3f0e289244e8
* Version Independent ID: b59a7a4e-9cb6-3d66-7c7b-6950e3694815
* Content: [Error statement (VBA)](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/error-statement)
* Content Source: [Language/Reference/User-Interface-Help/error-statement.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/error-statement.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@retailcoder Thanks for the feedback. I updated the NOTE as follows (trying to combine your comments without removing the existing comments): 

> [!NOTE] 
> Not all Visual Basic [host applications](../../Glossary/vbe-glossary.md#host-application) can create objects; for example, hosts running versions of Visual Basic for Applications earlier than 4.0 cannot create objects. Because **Err** is a function returning an **ErrObject** instance, it cannot be used in these early versions. To know what version of VBA your host application is running, see the **About** information for your Visual Basic Editor (VBE), and see your host application's documentation to determine whether it can create [classes](../../Glossary/vbe-glossary.md#class) and objects.

Changes will be live later today. Let me know if you have any questions.
