### ISSUE TITLE
Where are the original pre-butchered docs?

### ISSUE THREAD

**Issue by aberglas** [MicrosoftDocs/VBA-Docs#586]
E.g. what object does this apply to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8017c6ea-e7ca-565d-6b5f-13282f89d0d4
* Version Independent ID: 4ee5302b-d55f-163e-960a-fc5f2c41c73f
* Content: [DeleteLines method (VBA Add-In Object Model)](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/deletelines-method-vba-add-in-object-model)
* Content Source: [Language/Reference/User-Interface-Help/deletelines-method-vba-add-in-object-model.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/deletelines-method-vba-add-in-object-model.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@aberglas Sorry that this section of the documentation (VBA Add-In object model) isn't fully fleshed out. This content was migrated as is from MSDN. I think this method goes with the CodeModule object. There's a similar method in Access. See https://docs.microsoft.com/en-us/office/vba/language/reference/visual-basic-add-in-model/objects-visual-basic-add-in-model and https://docs.microsoft.com/en-us/office/vba/api/access.module.deletelines. (I'm just an editor, not a developer, so hope this helps.)
