### ISSUE TITLE
OlDisplayMode Enum formatting

### ISSUE THREAD

**Issue by jozefizso** [MicrosoftDocs/VBA-Docs#587]
This content is not formatted correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43d441be-e7f7-d213-a396-6ae5c281e406
* Version Independent ID: c9046e3e-1f64-01e0-1fdc-ac96e14c9493
* Content: [OlDisplayMode Enumeration (Outlook)](https://docs.microsoft.com/en-us/office/vba/api/outlook.oldisplaymode)
* Content Source: [api/Outlook.oldisplaymode.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Outlook.oldisplaymode.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@jozefizso Thanks for catching this! I fixed it, and changes will go live later today.
