### ISSUE TITLE
Missing enumeration

### ISSUE THREAD

**Issue by lifescholar** [MicrosoftDocs/VBA-Docs#595]
This list is missing xlCSVUTF8 (value 62)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a051762-67dc-bae9-7cda-1ecde2cc8d28
* Version Independent ID: 0057bfc4-2ed5-aa5f-0e71-6279c4d7c920
* Content: [xlFileFormat enumeration (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.xlfileformat)
* Content Source: [api/Excel.XlFileFormat.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.XlFileFormat.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@lifescholar Thanks! I added this value to the list; changes will be live later today.
