### ISSUE TITLE
None of these pages are useful...unless you already know it all

### ISSUE THREAD

**Issue by SKelem** [MicrosoftDocs/VBA-Docs#596]
Every one of these pages uses the least number of words to describe, narrowly, a property, method, object, etc. However there is no context or examples to show how or where you would use this info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6a920f6-2783-a0b9-6918-7e9a28fad7fc
* Version Independent ID: 7b70ce55-8fb1-836a-a270-4c7b0bbc333f
* Content: [Shape.Shapes Property (Visio)](https://docs.microsoft.com/en-us/office/vba/api/visio.shape.shapes)
* Content Source: [api/Visio.Shape.Shapes.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Visio.Shape.Shapes.md)
* Product: **visio**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@SKelem Sorry that you're having trouble. If you're new to VBA, try these conceptual topics: https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/visual-basic-conceptual-topics, which give a good introduction.
