### ISSUE TITLE
Adding white-space or proper separation between <code>-enclosed enumeration values

### ISSUE THREAD

**Issue by johnwait** [MicrosoftDocs/VBA-Docs#601]
If this documentation is meant to be current, it would helpful to properly separate enumerated values enclosed within `&lt;code&gt;` blocks, for instance within the description of members **xlCurrencyNegative** and **xlDateOrder**, such that the first paragraph of the description for the former could be properly displayed as:

&gt; Currency format for negative currency values: `0 = (symbolx) or (xsymbol)`, `1 = -symbolx or -xsymbol`, `2 = symbol-x or x-symbol` or  `3 = symbolx- or xsymbol-` where symbol is the currency symbol of the country or region.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7de599-1b69-3c9e-141d-535a19ff02bd
* Version Independent ID: 5296d320-ad57-0f2e-dbf5-4deb079ef4c8
* Content: [xlApplicationInternational enumeration (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.xlapplicationinternational)
* Content Source: [api/Excel.XlApplicationInternational.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.XlApplicationInternational.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@johnwait Thanks so much for pointing this out. I've made the fixes. Changes will be live later today.
