### ISSUE TITLE
Invalid hyperlink: http://msdn.microsoft.com/library/02a99ec8-2d93-587a-ae4a-31529be9d307%28Office.15%29.aspx

### ISSUE THREAD

**Issue by seydel1847** [MicrosoftDocs/VBA-Docs#603]
Invalid hyperlink in line:
[Indexes object (Word)02a99ec8-2d93-587a-ae4a-31529be9d307](http://msdn.microsoft.com/library/02a99ec8-2d93-587a-ae4a-31529be9d307%28Office.15%29.aspx)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7102116f-ee4c-01ab-fdf4-5642c9c3b24c
* Version Independent ID: f8f4f885-5df1-97ed-8cc2-bd805a7d0d1a
* Content: [Indexes Object, Word \[vbawd10.chm2428\]](https://docs.microsoft.com/en-us/office/vba/f1/indexes-object-word-vbawd10-chm2428)
* Content Source: [F1/indexes-object-word-vbawd10-chm2428.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/F1/indexes-object-word-vbawd10-chm2428.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@seydel1847 Thanks for pointing out the broken link. Here's the new link - https://docs.microsoft.com/office/vba/api/Word.indexes. I updated the topic.
