### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by gdowdy3** [MicrosoftDocs/VBA-Docs#607]
I'm still learning about VBA, so this is probably too bold for me to suggest feedback, but I'm wondering if you may have a typo in your last sentence.  Instead of "...implicitly after the last object variable set to Nothing goes out of scope", did you mean to say "...implicitly after the last object variable referencing the actual object goes out of scope"?  My apologies if I'm wrong.  Again, I'm still learning this stuff.  :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c76ecae-3382-8453-414f-f2dd24085eed
* Version Independent ID: 900c7733-da10-caff-61b8-34b006c0e692
* Content: [Nothing keyword (VBA)](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/nothing-keyword)
* Content Source: [Language/Reference/User-Interface-Help/nothing-keyword.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/nothing-keyword.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@gdowdy3 You may be right. I'm only an editor, so will see if I can find someone who can answer this. Thanks.

@brreich Bryan -- what do you think?

**Comment by MarkFern** [comment]
Had a look at @gdowdy3's suggested edit. I believe he is right. His suggestion appears to fix the documentation in respect of what appears to be a mistake that he has highlighted.

**Comment by Linda-Editor** [comment]
@MarkFern Thanks for the feedback and your help confirming this change.

@gdowdy3 Thanks for your patience. I've made your update; changes will be live later today. Thanks for your contribution.

**Comment by gdowdy3** [comment]
:grin:
