### ISSUE TITLE
Een typefout

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#609]
There is an error in the Remarks section. Under 'If bit in expression is' is an o instead of a 0. I know I am terrible, but I thought I should report it anyway.
Greeting, Peter van Loosbroek.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 9ef90588-3738-2191-a81c-dc7b685515e3
* Version Independent ID: c201f110-2359-0db4-684f-ee3dcc4391a8
* Content: [Not operator](https://docs.microsoft.com/nl-nl/office/vba/language/reference/user-interface-help/not-operator)
* Content Source: [Language/Reference/User-Interface-Help/not-operator.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/not-operator.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks for catching this! Please don't hesitate to let us know about stuff like this. It's an easy fix. Changes will be live later today.

**Comment by PeterVanLoosbroek** [comment]
Your welcome, Linda.

 

Hartelijke groet,

Peter van Loosbroek

 

 



 

Microsoft Office Development

Wilgenstraat 4

5382 KH   Vinkel

W.  <http://www.officeprograms.nl/> www.officeprograms.nl

E.  <mailto:info@officeprograms.nl> info@officeprograms.nl

M. +31 (0)6 218 532 20

 

Van: Linda Caputo <notifications@github.com> 
Verzonden: woensdag 2 januari 2019 23:45
Aan: MicrosoftDocs/VBA-Docs <VBA-Docs@noreply.github.com>
CC: PeterVanLoosbroek <info@officeprograms.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/VBA-Docs] Een typefout (#609)

 

@PeterVanLoosbroek <https://github.com/PeterVanLoosbroek>  Thanks for catching this! Please don't hesitate to let us know about stuff like this. It's an easy fix. Changes will be live later today.
