### ISSUE TITLE
Example Error Needs Correction

### ISSUE THREAD

**Issue by BandTSV** [MicrosoftDocs/VBA-Docs#618]
As stated in Remarks,
"The LinkToFile and SaveWithDocument arguments cannot have the same value, or else an error occurs. If either argument is msoTrue, the other must be msoFalse."

In the example given both attributes are True and the example text fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8ae92ca-5fb2-db40-2e24-7d52fbb01a81
* Version Independent ID: a0e9eb84-e044-4a5f-4a63-c7a48eb94986
* Content: [Shapes.AddPicture Method (Publisher)](https://docs.microsoft.com/en-us/office/vba/api/publisher.shapes.addpicture)
* Content Source: [api/Publisher.Shapes.AddPicture.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Publisher.Shapes.AddPicture.md)
* Product: **publisher**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@BandTSV Excellent find! I updated the code example to this; is this correct now?

```vb
Dim shpPicture As Shape 
 
Set shpPicture = ActiveDocument.Pages(1).Shapes.AddPicture _ 
 (FileName:="PathToFile", _ 
 LinkToFile:=msoTrue, _ 
 SaveWithDocument:=msoFalse 
 Left:=72, Top:=72)
```

**Comment by BandTSV** [comment]
Looks good. The fix you presented works in my document. Thank you.

While we are here, perhaps you might be able to provide me with some
additional insight or a steer in the right direction.

I am using Access to produce a program. My only problem is that the quality
of pictures included in the program is significantly downgraded. Ultimately
my program will be exported to a .pdf file to send to the printer. In
its current format, the picture quality is insufficient. The same picture
produced by Word, PowerPoint or Publisher is fine. What's the issue with
pictures in Access? Is there a solution? I have employed the "convert all
pictures to bitmaps" switch but still no luck.

Thanks for any help you can provide.

Cheers, Bill
