### ISSUE TITLE
Registry incorrectly mentioned as dword instead of String Value

### ISSUE THREAD

**Issue by SarveshDongare** [MicrosoftDocs/VBA-Docs#625]
HKEY_CURRENT_USER\Software\Policies\Microsoft\Office\16.0\Outlook\Resiliency\AddinList
Under this The registry with ProgId of addin should be string and not dword.
Also mentioned in below article:
https://support.microsoft.com/en-in/help/2733070/no-add-ins-loaded-due-to-group-policy-settings-for-office-2013-and-off

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29565b93-a15a-c761-f3b2-315028b995d1
* Version Independent ID: f54fdbc6-93b8-d62a-7d69-e08a6b030428
* Content: [Support for keeping add-ins enabled](https://docs.microsoft.com/en-us/office/vba/outlook/concepts/getting-started/support-for-keeping-add-ins-enabled)
* Content Source: [outlook/Concepts/Getting-Started/support-for-keeping-add-ins-enabled.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/outlook/Concepts/Getting-Started/support-for-keeping-add-ins-enabled.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@SarveshDongare Thanks for your feedback, but I don't understand what you're wanting to update. Please be more specific (I'm just an editor, not a developer).

**Comment by SarveshDongare** [comment]
Hello Linda,

That registry I mentioned needs to be string value and not sword as mentioned in the technet article.

Thanks,
Sarvesh.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Linda-Editor** [comment]
@SarveshDongare @fthorsen76 Thanks. I updated both instances of |DWORD|ProgID of the add-in| to |String|ProgID of the add-in| in the tables.

Is that what you requested? Changes will be live later today.
