### ISSUE TITLE
Incorrect syntax

### ISSUE THREAD

**Issue by nojoble** [MicrosoftDocs/VBA-Docs#631]
Worksheets("Sheet1").Range("A1").Style.Name = "Normal" 
did not work for me, however
Worksheets("Sheet1").Range("A1").Style = "Normal"
worked fine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6997781e-d873-52ba-77dc-d591bb100ce6
* Version Independent ID: c2f9f374-dd1a-0908-4328-a084881a24f8
* Content: [Range.Style property (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.range.style)
* Content Source: [api/Excel.Range.Style.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Range.Style.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by pedro-w** [comment]
I've just come across the same thing. It gives

    Run-time error '450':
    Wrong number of arguments or invalid property assignment

Using 

    Worksheets("Sheet1").Range("A1").Style = ThisWorkbook.Styles("Normal")

is also OK, suggesting you can assign a `Style` object or the name of a style, but altering the name of the style is not allowed.

**Comment by Linda-Editor** [comment]
@nojoble and @pedro-w Thanks for this feedback. I've made the following updates to the text; changes will be live later today. Let me know if you have any questions or further comments.

## Example

This example applies the Normal style to cell A1 on Sheet1.

```vb
Worksheets("Sheet1").Range("A1").Style = "Normal"

```

An alternative is the following:

```vb
Worksheets("Sheet1").Range("A1").Style = ThisWorkbook.Styles("Normal")
```

If cell B4 on Sheet1 currently has the Normal style applied, this example applies the Percent style.

```vb
If Worksheets("Sheet1").Range("B4").Style = "Normal" Then 
 Worksheets("Sheet1").Range("B4").Style = "Percent" 
End If

```
