### ISSUE TITLE
Return is not null but nothing

### ISSUE THREAD

**Issue by Fdepraetre** [MicrosoftDocs/VBA-Docs#633]
For new comment Level, the return is Nothing. When you use IsNull(X.Ancestor) you will get False.

You need to test If( X.Ancestor Is Nothing ) Then.... to get the true information.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 534accdf-4599-7753-6871-6a8b227f609d
* Version Independent ID: 0520f57e-6adb-4671-4de6-54caff808d41
* Content: [Comment.Ancestor property (Word)](https://docs.microsoft.com/en-us/office/vba/api/word.comment.ancestor)
* Content Source: [api/Word.comment.ancestor.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Word.comment.ancestor.md)
* Product: **word**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@Fdepraetre Thanks for the info. I updated "returns null" to "returns Nothing". Changes will be live later today.
