### ISSUE TITLE
Here's What Would Be Really Helpful

### ISSUE THREAD

**Issue by JohnFauss** [MicrosoftDocs/VBA-Docs#647]
Very nice post, especially since I am just starting to code for 64-bit. Thank you!

It would be really helpful if Microsoft would include in the Windows API documentation whether or not an argument value or return value should be declared as a LongPtr. In your post, you state: "Use LongPtr for pointers and handles". That's a very broad brush. ALL handles? A handle to a window - OK. A handle to a font? A handle to a device context? A handle to a result value (HRESULT)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed3a457f-5acb-5e53-c59b-83b36517c029
* Version Independent ID: 70f25e95-bbc7-04ab-744b-c11edd97e274
* Content: [64-bit Visual Basic for Applications overview](https://docs.microsoft.com/en-us/office/vba/Language/Concepts/Getting-Started/64-bit-visual-basic-for-applications-overview)
* Content Source: [Language/Concepts/Getting-Started/64-bit-visual-basic-for-applications-overview.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Concepts/Getting-Started/64-bit-visual-basic-for-applications-overview.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
Hi, thanks for your comment. You might find these topics helpful:
[LongPtr data type](https://docs.microsoft.com/en-us/office/vba/Language/Reference/User-Interface-Help/longptr-data-type) which links to [Compiler constants](https://docs.microsoft.com/en-us/office/vba/Language/Concepts/Getting-Started/compiler-constants). These topics should tell you when to use LongPtr.

Note you can also ask questions like this to the developer community on [StackOverflow](https://stackoverflow.com/search?q=LongPtr). In fact, this question has been asked there a couple of times. 

Good luck coding!
