### ISSUE TITLE
There should be a link for inputbox function in See also

### ISSUE THREAD

**Issue by geoffm** [MicrosoftDocs/VBA-Docs#648]
There should be a link for inputbox function in See also

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25a424ad-7579-654d-c65e-d6be8c3c1578
* Version Independent ID: 5464d046-fff7-8fff-d62e-4e65b7f9ee16
* Content: [Application.InputBox method (Excel)](https://docs.microsoft.com/en-us/office/vba/api/Excel.Application.InputBox)
* Content Source: [api/Excel.Application.InputBox.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Application.InputBox.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@geoffm I added this link. Thanks for your contribution. Changes will be live later today.
