### ISSUE TITLE
See also should contain a hyperlink to the inputbox method

### ISSUE THREAD

**Issue by geoffm** [MicrosoftDocs/VBA-Docs#649]
https://docs.microsoft.com/en-us/office/vba/api/excel.application.inputbox

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be8e31a8-1006-83c8-adde-16f35b6d97d2
* Version Independent ID: 48ac05de-bcfa-96f6-6113-fa35f0ff12f3
* Content: [InputBox function (Visual Basic for Applications)](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/inputbox-function)
* Content Source: [Language/Reference/User-Interface-Help/inputbox-function.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/inputbox-function.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@geoffm Thanks for the feedback. I added a link to the method. Changes will be live later today.
