### ISSUE TITLE
Ejecucion de SendKeys

### ISSUE THREAD

**Issue by alcidesp** [MicrosoftDocs/VBA-Docs#65]
Porque cuando se ejecuta el SendKeys dentro de un foreach se genera de forma ascendente y no descendente

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82810563-6d86-0d35-2ba6-2ded9a2ed183
* Version Independent ID: 1e0e514c-dc08-5c0c-b753-aa92cd522168
* Content: [Application.SendKeys Method (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.application.sendkeys#feedback)
* Content Source: [api/Excel.Application.SendKeys.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Application.SendKeys.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
@alcidesp Una solución: "Puede invertir el elemento (list.Reverse ()) en la lista antes de hacerlo foreach.'" 

Ver pregunta enStackOverflow: https://stackoverflow.com/questions/1211608/possible-to-iterate-backwards-through-a-foreach.
