### ISSUE TITLE
New

### ISSUE THREAD

**Issue by belovedinmn16** [MicrosoftDocs/VBA-Docs#650]
Looking

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7834403-cc71-6315-0e1d-b53f5738a359
* Version Independent ID: 6bca468e-6c84-a208-8790-010ef6bca959
* Content: [Concepts (Access VBA reference)](https://docs.microsoft.com/en-us/office/vba/access/concepts/miscellaneous/concepts-access-vba-reference)
* Content Source: [access/Concepts/Miscellaneous/concepts-access-vba-reference.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/access/Concepts/Miscellaneous/concepts-access-vba-reference.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
Looks like this issue was opened by mistake!
