### ISSUE TITLE
Git merge conflict evident in content

### ISSUE THREAD

**Issue by DonalLOConnor** [MicrosoftDocs/VBA-Docs#67]
There appears to be an unresolved git merge conflict in the content of this page.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c066231f-a640-7c17-ed14-5c54e315591e
* Version Independent ID: 4c8a9dca-aaf7-13dd-e50c-cd922ef6a24c
* Content: [Worksheet.Range Property (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.worksheet.range)
* Content Source: [api/Excel.Worksheet.Range.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.Worksheet.Range.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
All the merge issues are now fixed; let me know if you see any more: https://docs.microsoft.com/en-us/office/vba/api/overview/

**Comment by DonalLOConnor** [comment]
Will do, looks good, thanks.
