### ISSUE TITLE
BoundObjectFrame.SourceDoc property (Access)

### ISSUE THREAD

**Issue by ChessAce** [MicrosoftDocs/VBA-Docs#675]
Made many attempts at specifying a file (in record of db table) to load into image, including one of the lines herein, but could not get it to work.  With a complete set of lines from this doc, it worked the first time!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd7ce0-6601-6aa4-ccc2-35125ca6dca5
* Version Independent ID: 8e2f3cae-d582-8786-7e30-08746c0d1d31
* Content: [BoundObjectFrame.SourceDoc property (Access)](https://docs.microsoft.com/en-us/office/vba/api/access.boundobjectframe.sourcedoc#example)
* Content Source: [api/Access.BoundObjectFrame.SourceDoc.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Access.BoundObjectFrame.SourceDoc.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@ChessAce Thanks for the positive feedback!
