### ISSUE TITLE
The link "Calling Action Queries" leads to nothing useful.

### ISSUE THREAD

**Issue by unforgettableAshwin** [MicrosoftDocs/VBA-Docs#677]
Please update or delete this link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 654cd94e-6578-1f1c-8026-8bfc99f95b9d
* Version Independent ID: 09e86f18-d95e-8b7d-6856-6578098de5dc
* Content: [DoCmd.SetWarnings method (Access)](https://docs.microsoft.com/en-us/office/vba/api/access.docmd.setwarnings?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev11.query%3FappId%3DDev11IDEF1%26l%3Den-US%26k%3Dk(vbaac10.chm4183)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv16)%26rd%3Dtrue)
* Content Source: [api/Access.DoCmd.SetWarnings.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Access.DoCmd.SetWarnings.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@unforgettableAshwin Thanks...this was an old link, so I removed it. Changes will be live later today.
