### ISSUE TITLE
Invalid link: MDSCHEMA_ACTIONS -> https://msdn.microsoft.com/library/ms126032.aspx

### ISSUE THREAD

**Issue by seydel1847** [MicrosoftDocs/VBA-Docs#685]
Page: https://docs.microsoft.com/en-us/office/vba/excel/concepts/ole-db-for-olap-properties-used-by-excel
Invalid link: MDSCHEMA_ACTIONS -&gt; https://msdn.microsoft.com/library/ms126032.aspx
Redirection to: https://docs.microsoft.com/en-us/sql/analysis-services/schema-rowsets/ole-db-olap/mdschema-actions-rowset

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20d89907-1016-ebbf-38bd-53d574995a8f
* Version Independent ID: be0e95b8-fee0-28a5-2b13-20827a4dbcee
* Content: [OLE DB for OLAP Properties Used by Excel](https://docs.microsoft.com/en-us/office/vba/excel/concepts/ole-db-for-olap-properties-used-by-excel)
* Content Source: [excel/Concepts/ole-db-for-olap-properties-used-by-excel.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/excel/Concepts/ole-db-for-olap-properties-used-by-excel.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@seydel1847 Thanks. I replaced the link with https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/ms126032(v%3dsql.110), because the one you gave me also 404'd. Changes will be live later today.
