### ISSUE TITLE
Invalid link: "An automation server cannot pass a pointer to the picture object's IPictureDisp implementation across process boundaries." -> https://support.microsoft.com/kb/150034

### ISSUE THREAD

**Issue by seydel1847** [MicrosoftDocs/VBA-Docs#686]
Page: https://docs.microsoft.com/en-us/office/vba/api/outlook.folder.getcustomicon
Invalid link: "An automation server cannot pass a pointer to the picture object's IPictureDisp implementation across process boundaries." -&gt; https://support.microsoft.com/kb/150034

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e558c75-c149-323c-8ee9-bd5268342907
* Version Independent ID: a4db56ac-8e9b-688d-3606-3c686442ec3a
* Content: [Folder.GetCustomIcon Method (Outlook)](https://docs.microsoft.com/en-us/office/vba/api/outlook.folder.getcustomicon)
* Content Source: [api/Outlook.Folder.GetCustomIcon.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Outlook.Folder.GetCustomIcon.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by seydel1847** [comment]
The same problem here:
Page: https://docs.microsoft.com/en-us/office/vba/api/outlook.folder.setcustomicon
Invalid link: "An automation server cannot pass a pointer to the picture object's IPictureDisp implementation across process boundaries." -> https://support.microsoft.com/kb/150034

**Comment by seydel1847** [comment]
The same problem here:
Page: https://docs.microsoft.com/en-us/office/vba/api/outlook.exchangeuser.getpicture
Invalid link: "An automation server cannot pass a pointer to the picture object's IPictureDisp implementation across process boundaries." -> https://support.microsoft.com/kb/150034

**Comment by Linda-Editor** [comment]
@seydel1847 I couldn't find current instances of these 3 resources, so removed the links.
