### ISSUE TITLE
Invalid link: "839079" -> https://support.microsoft.com/kb/839079/

### ISSUE THREAD

**Issue by seydel1847** [MicrosoftDocs/VBA-Docs#688]
Page: https://docs.microsoft.com/en-us/office/vba/api/visio.invisibleapp.ondatachangedelay
Invalid link: "839079" -&gt; https://support.microsoft.com/kb/839079/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10d1abc4-2ef2-8011-6064-cbf89b58bf54
* Version Independent ID: de57372e-709d-49de-5747-d34cbdc23720
* Content: [InvisibleApp.OnDataChangeDelay Property (Visio)](https://docs.microsoft.com/en-us/office/vba/api/visio.invisibleapp.ondatachangedelay)
* Content Source: [api/Visio.InvisibleApp.OnDataChangeDelay.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Visio.InvisibleApp.OnDataChangeDelay.md)
* Product: **visio**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@seydel1847 Could not determine where old kb articles now live, so removed the reference.
