### ISSUE TITLE
Invalid link: "839079" -> https://support.microsoft.com/?scid=http%3a%2f%2fwww.support.microsoft.com%2fkb%2f839079%2f

### ISSUE THREAD

**Issue by seydel1847** [MicrosoftDocs/VBA-Docs#689]
Page: https://docs.microsoft.com/en-us/office/vba/api/visio.invisibleapp.ondatachangedelay
Invalid link: "839079" -&gt; https://support.microsoft.com/?scid=http%3a%2f%2fwww.support.microsoft.com%2fkb%2f839079%2f

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0adf9a8d-d77f-509e-b569-221ebe2bad13
* Version Independent ID: d2ee5e4e-c45b-987f-f7b1-4ef4612754d4
* Content: [Application.OnDataChangeDelay Property (Visio)](https://docs.microsoft.com/en-us/office/vba/api/visio.application.ondatachangedelay)
* Content Source: [api/Visio.Application.OnDataChangeDelay.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Visio.Application.OnDataChangeDelay.md)
* Product: **visio**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@seydel1847 I'm trying to find out where all these kb articles were migrated to...they're not easy to track down, so stay tuned.

**Comment by Linda-Editor** [comment]
@seydel1847 I could not determine where old support articles exist (if it all), so removed link from documentation.
