### ISSUE TITLE
Unnecessary string "%28Office.15%29.aspx)" appended to web link

### ISSUE THREAD

**Issue by seydel1847** [MicrosoftDocs/VBA-Docs#690]
Page: https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/this-document-was-opened-with-macros-disabled
Unnecessary string "%28Office.15%29.aspx)" appended to web link in line "[Enable or disable macros in Office documents (2007 and 2010)](https://support.office.com/article/Enable-or-disable-macros-in-Office-documents-7B4FDD2E-174F-47E2-9611-9EFE4F860B12 %28Office.15%29.aspx)" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6015849-2ecf-f35c-a6e6-7338d3985dd1
* Version Independent ID: d585d05f-e29e-81b1-e470-308def0811b5
* Content: [This document was opened with macros disabled](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/this-document-was-opened-with-macros-disabled)
* Content Source: [Language/Reference/User-Interface-Help/this-document-was-opened-with-macros-disabled.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/this-document-was-opened-with-macros-disabled.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@seydel1847 Thanks for the contribution. Both links appeared to go to the same destination, so I removed one and changed the other to this: 
[Enable or disable macros in Office files (2007, 2010, and 2013)](https://support.office.com/en-us/article/enable-or-disable-macros-in-office-files-12b036fd-d140-4e74-b45e-16fed1a7e5c6)
