### ISSUE TITLE
Offline Help was more accurate

### ISSUE THREAD

**Issue by grovelli** [MicrosoftDocs/VBA-Docs#70]
Fix this document formatting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbdf1cf8-dd51-64b8-ca1d-7523d8383f6b
* Version Independent ID: bad3ed43-d602-ae25-d9e1-e11dd36fc23c
* Content: [UBound Function](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/ubound-function?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev11.query%3FappId%3DDev11IDEF1%26l%3Den-US%26k%3Dk(vblr6.chm1009050)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv16)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396)
* Content Source: [Language/Reference/User-Interface-Help/ubound-function.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/ubound-function.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Kagre** [comment]
shame on you, you literally have the ability to fix it yourself.

**Comment by grovelli** [comment]
Didn't it occur to you that had I known how to fix it I would have done it myself? Not everyone is as knowledgeable as you are.

**Comment by grovelli** [comment]
Furthermore, if I try to edit the part in the article where it says, "UBound returns the following values for an array with these dimensions:" in order to add the example array, I get this message, "You’re editing a file in a project you don’t have write access to. We’ve created a fork of this project for you to commit your proposed changes to. Submitting a change to this file will write it to a new branch in your fork, so you can send a pull request. "

**Comment by Linda-Editor** [comment]
@grovelli - the above is the correct way to submit a change to a page. Someone from Microsoft will then review it and merge your changes to the documentation. By the way, I fixed the formatting on this page: https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/ubound-function. Was there something else you wanted changed?

**Comment by Kagre** [comment]
@grovelli fair points, if you make your changes it'll post to your local copy "Fork", then you need to click the button on the left-hand side of the `<>Code` tab that says "new pull request", then fill in the short name and quick description of what changed, and do the green "create pull request button". At that point your fixes are in the hands of the MS team to integrate into the master version.

If your looking for more detail, I went through the tutorial a couple weeks back and that helped me a lot.
https://guides.github.com/activities/hello-world/

**Comment by Kagre** [comment]
@grovelli also note that the MS team is in a major formatting makeover this week so, you're probably better holding off any changes till on/after Sept 5th
