### ISSUE TITLE
Inconsistency in the documentation (Excel)

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#710]
I have discovered an inconsistency in the documentation. It concerns all Enumerations within Excel. These are classes whose original name starts with a capital letter. In the documentation, however, they start with a lowercase letter.

For example: xlAboveBelow enumeration must be: XlAboveBelow enumeration
Check it on the next page:
https://docs.microsoft.com/en-us/office/vba/api/excel.xlabovebelow

Both on the page and in the left menu a lower case letter is used, instead of a capital letter.

If you search for the name in the object browser, you will also see that these classes start with a capital letter. On the contrary, the constants (the members of the Enumerations) do not. They are correctly displayed.

In Word, Outlook and PowerPoint this has all been done correctly. To make everything consistent, it would be a good idea to adjust Excel documentation.

Greetings, Peter van Loosbroek (The Netherlands)

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks, Peter. I can fix this in the next day or so. So, it should be capital X but lowercase "l" and then the enumeration name, right? "Xl" and not "XL"?

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek I fixed the titles in the TOC; the topics themselves will take longer. Be patient, I'll get to them eventually. Thanks. Changes will be live later today.

**Comment by PeterVanLoosbroek** [comment]
OK, Linda, do not rush for me. I have no problem with that. I would like to help you.

 

Greetings,

Peter van Loosbroek

 

Voor een onderbouwing van de hoogste kwaliteit:  <https://www.officeprograms.nl/ms-access/uniek.htm> Waarom is Office Programs uniek in MS Access?

 

 



 

Microsoft Office Development

Wilgenstraat 4

5382 KH   Vinkel

W.  <http://www.officeprograms.nl/> www.officeprograms.nl

E.  <mailto:info@officeprograms.nl> info@officeprograms.nl

M. +31 (0)6 218 532 20

 

Van: Linda Caputo <notifications@github.com> 
Verzonden: vrijdag 8 februari 2019 00:12
Aan: MicrosoftDocs/VBA-Docs <VBA-Docs@noreply.github.com>
CC: PeterVanLoosbroek <info@officeprograms.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/VBA-Docs] Inconsistency in the documentation (Excel) (#710)

 

@PeterVanLoosbroek <https://github.com/PeterVanLoosbroek>  I fixed the titles in the TOC; the topics themselves will take longer. Be patient, I'll get to them eventually. Thanks. Changes will be live later today.

**Comment by PeterVanLoosbroek** [comment]
That’s correct. If you have questions, you can always ask me.

 

 

Hartelijke groet,

Peter van Loosbroek

 

Voor een onderbouwing van de hoogste kwaliteit:  <https://www.officeprograms.nl/ms-access/uniek.htm> Waarom is Office Programs uniek in MS Access?

 

 



 

Microsoft Office Development

Wilgenstraat 4

5382 KH   Vinkel

W.  <http://www.officeprograms.nl/> www.officeprograms.nl

E.  <mailto:info@officeprograms.nl> info@officeprograms.nl

M. +31 (0)6 218 532 20

 

Van: Linda Caputo <notifications@github.com> 
Verzonden: vrijdag 8 februari 2019 00:16
Aan: MicrosoftDocs/VBA-Docs <VBA-Docs@noreply.github.com>
CC: PeterVanLoosbroek <info@officeprograms.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/VBA-Docs] Inconsistency in the documentation (Excel) (#710)

 

@PeterVanLoosbroek <https://github.com/PeterVanLoosbroek>  Thanks, Peter. I can fix this in the next day or so. So, it should be capital X but lowercase "l" and then the enumeration name, right? "Xl" and not "XL"?

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek I was able to do a search/replace and update the enumeration titles to "Xl". Thanks again for your input on this.
