### ISSUE TITLE
Huh?

### ISSUE THREAD

**Issue by MarkMoretto** [MicrosoftDocs/VBA-Docs#72]
Microsoft has a tendency to "go lean" on information pages. This is a great example of one.

For example, lets read about the number argument: "Numeric expression corresponding to the numeric order of the environment string in the environment-string table."

Okay...how do I find out about these?  You'd figure they'd be pretty important, yet the only links on the page are to a glossary of terms.

I feel like these pages could be super useful and there have been some that clearly define and provide examples for Microsoft platform functions, procedures, methods, etc., but Access/Excel VBA information always seems to assume  that the reader has 5+ years of programming experience, which isn't the case nowadays.

Because of this, I end up having to use multiple third-party sources for information, hoping and praying the entire time that those examples might fit with what I'm trying to do.  I'd rather have a comprehensive, centralized resource to tap when I'm trying to find out the intricacies of a language.

Thanks,

Mark M.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3476023f-79e8-05db-c11d-8f8a25f0ff35
* Version Independent ID: 8ab5d342-ca9e-8b8b-5a02-d83c92a20d9e
* Content: [Environ function](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/environ-function)
* Content Source: [Language/Reference/User-Interface-Help/environ-function.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/environ-function.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Kagre** [comment]
to be honest I don't even know why `number` is an option there, you almost always want to use `envstring`. Also part of why the documentation on the environment table is spotty is due to the fact that this is Excel documentation and not Windows documentation.

## See Also
- Windows [Environment Variables](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682653.aspx)

**Comment by lindalu-MSFT** [comment]
Thanks @Kagre @MarkMoretto thanks for your feedback. I've added See also section with links.
