### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by EstherHe** [MicrosoftDocs/VBA-Docs#73]
Unexpected error(50001),I need some help please.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d1239b71-082f-802b-bef0-4cf1df1c67d5
* Version Independent ID: 28111a2f-22a3-5b3f-6431-a90e9434a6f8
* Content: [Unexpected error; please contact Microsoft Technical Support](https://docs.microsoft.com/zh-cn/office/vba/language/reference/user-interface-help/unexpected-error-please-contact-microsoft-technical-support?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev11.query%3FappId%3DDev11IDEF1%26l%3Dzh-CN%26k%3Dk(vblr6.chm1057105)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv16)%26rd%3Dtrue)
* Content Source: [Language/Reference/User-Interface-Help/unexpected-error-please-contact-microsoft-technical-support.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/unexpected-error-please-contact-microsoft-technical-support.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
Hi @EstherHe, can you please give us more information? Please give us the steps to repro the error so we know where to begin.

**Comment by lindalu-MSFT** [comment]
No response, closing issue. If you still have problems, please provide repro steps so we can assist. Thanks, linda
