### ISSUE TITLE
Some documentation pages contain git merge conflict markers on the docs website

### ISSUE THREAD

**Issue by sanderdegroot** [MicrosoftDocs/VBA-Docs#77]
Nearly every page in the Docs / Office VBA Reference / Language Reference / Concepts / Getting Started section contains git conflict markers, e.g.:
https://docs.microsoft.com/en-us/office/vba/language/concepts/getting-started/avoiding-naming-conflicts

These markers do not appear to exist in this repository on any branch I've checked. Not sure which version of the docs pages is deployed on the live website.

![conflict markers](https://user-images.githubusercontent.com/20391979/44679618-7ccc6e00-aa09-11e8-93bf-94b57b7772ec.PNG)

**Comment by Linda-Editor** [comment]
We're dealing with this issue now, thanks. Check back later today, and let us know if you see any more.

**Comment by Linda-Editor** [comment]
These are fixed now. Let me know if you see any still around. 
https://docs.microsoft.com/en-us/office/vba/api/overview/
