### ISSUE TITLE
Doc bug

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#784]
A small doc bug: At the following page (in the first code example) "&-a-m-p-;" is used instead &. I've inserted the - sign to show the string (because this post is in HTML)
https://docs.microsoft.com/en-us/office/vba/api/word.characters

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks for catching this. I updated the code sample to use "&" only; changes will be live later today.
