### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#785]
The following page says (third paragraph): "There are 11 different story types represented by the WdStoryType constants of the StoryType property."
In the meantime, there are not 11, but 17. Because the development continues, it is better to use the following sentence: "There are several story types represented by the WdStoryType constants of the StoryType property."

https://docs.microsoft.com/en-us/office/vba/word/concepts/working-with-word/working-with-range-objects

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks for this submission. I updated the text and added a link to the enumeration: There are several story types represented by the **[WdStoryType](../../../api/word.wdstorytype.md)** constants of the **StoryType** property.

**Comment by PeterVanLoosbroek** [comment]
Great job Linda!

 

Hartelijke groet,

Peter van Loosbroek

 

Voor een onderbouwing van de hoogste kwaliteit:  <https://www.officeprograms.nl/ms-access/uniek.htm> Waarom is Office Programs uniek in MS Access?

 

 



 

Microsoft Office Development

Wilgenstraat 4

5382 KH   Vinkel

W.  <http://www.officeprograms.nl/> www.officeprograms.nl

E.  <mailto:info@officeprograms.nl> info@officeprograms.nl

M. +31 (0)6 218 532 20

 

Van: Linda Caputo <notifications@github.com> 
Verzonden: dinsdag 19 februari 2019 19:02
Aan: MicrosoftDocs/VBA-Docs <VBA-Docs@noreply.github.com>
CC: Peter van Loosbroek <info@officeprograms.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/VBA-Docs] Incorrect documentation (#785)

 

@PeterVanLoosbroek <https://github.com/PeterVanLoosbroek>  Thanks for this submission. I updated the text and added a link to the enumeration: There are several story types represented by the WdStoryType constants of the StoryType property.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks!
