### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#786]
Under the heading "Using the Range method", in the text "Use the Range method (…)" the link for Range is incorrect.

Page: https://docs.microsoft.com/en-us/office/vba/word/concepts/working-with-word/working-with-range-objects

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks, Peter. I updated the link to word.document.range.
