### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by FrankLennon** [MicrosoftDocs/VBA-Docs#80]
I was sent to this page after clicking Help in an Excel VBA message box for Error 400 (I assume that is what the white cross on a red background followed by '400' indicates?).  It is no help at all, nor are the two references offered.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c21b6159-f36a-a18f-07b3-ce8813515bed
* Version Independent ID: 0ec7aa90-caa9-4636-baec-1873c135b10b
* Content: [Language reference for Visual Basic for Applications (VBA)](https://docs.microsoft.com/en-au/office/vba/api/overview/language-reference)
* Content Source: [api/overview/Language-Reference.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/overview/Language-Reference.md)
* Product: **vba**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Linda-Editor** [comment]
@FrankLennon - Is this what you were looking for? https://docs.microsoft.com/en-us/office/vba/Language/Reference/User-Interface-Help/form-already-displayed-can-t-show-modally-error-400

If not, try using the search filter here: https://docs.microsoft.com/en-us/office/vba/api/overview/excel

Or let me know specifically what you were looking for, and we'll try to track it down. Thanks.

**Comment by lindalu-MSFT** [comment]
@FrankLennon Thanks for pointing this out. We recently migrated this repo and had to redo all of our F1 help messages. It was quite a task, and there are still some things not working as expected. Like Linda said in the previous comment, please tell us specifically what you were looking for and the steps to repro what happened to you so we can track it down and fix it. It might be a more global issue and your help is greatly appreciated.

**Comment by lindalu-MSFT** [comment]
Since we didn't hear back from @FrankLennon with the repo steps, I'm closing this issue. Feel free to reopen if you can supply the exact steps to repro so we know how to fix. Thanks,
