### ISSUE TITLE
Change upper-left to upper-right text 

### ISSUE THREAD

**Issue by feliperomero3** [MicrosoftDocs/VBA-Docs#803]
First paragraph in Subheading **What's changed in the User Interface**
It should say upper-right.

![image](https://user-images.githubusercontent.com/4691988/53282003-01fdba80-36ef-11e9-9925-32a64f6daac1.png)

Regards.

**Comment by Linda-Editor** [comment]
@feliperomero3 Fixed. Changes will be live tomorrow. Thanks for your contribution.
