### ISSUE TITLE
Duplicated word in the first bullet point at 'Custom Tasks Panes' subheading

### ISSUE THREAD

**Issue by feliperomero3** [MicrosoftDocs/VBA-Docs#805]
**Custom Tasks Panes** subheading has a duplicated word in the first bullet point (after first paragraph).

To summarize, as a developer, you will want to:

- Ensure that for any workbooks where you want to ~~want to~~ show the custom task pane, you write code to explicitly do that.

**Comment by Linda-Editor** [comment]
@feliperomero3 In the future, please include a link to the live page when you submit an issue, so we can easily find it. In this case, I was able to search on the string, so I fixed it. Changes will be live later today.

**Comment by feliperomero3** [comment]
Understood @Linda-Editor
