### ISSUE TITLE
Fix translations. セットアップ → setup

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#807]
https://docs.microsoft.com/ja-jp/office/vba/language/concepts/getting-started/document-conventions-visual-basic-for-applications

**Comment by Linda-Editor** [comment]
@Soran-M - could you look into this?

**Comment by hyoshioka0128** [comment]
セットアップ → setup(It is translated though it need not be translated)

![document-conventions-visual-basic-for-applications_1](https://user-images.githubusercontent.com/40815708/53402439-1692c900-39f5-11e9-8567-827e5206e9fb.png)

Japanese: https://docs.microsoft.com/ja-jp/office/vba/language/concepts/getting-started/document-conventions-visual-basic-for-applications

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 the parameter was updated and published live
