### ISSUE TITLE
TOC for VBA-Docs ja-jp document is empty. 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#808]
https://docs.microsoft.com/ja-jp/office/vba/language/concepts/getting-started/document-conventions-visual-basic-for-applications

**Comment by Linda-Editor** [comment]
@hyoshioka0128 We need more info. The TOC seems fine.

**Comment by hyoshioka0128** [comment]
TOC is not Translated.
![document-conventions-visual-basic-for-applications_2](https://user-images.githubusercontent.com/40815708/53402676-886b1280-39f5-11e9-8c28-90be76faca18.png)

Japanese: https://docs.microsoft.com/ja-jp/office/vba/language/concepts/getting-started/document-conventions-visual-basic-for-applications

**Comment by OfficeGlobal** [comment]
Translated TOC files are currently blocked from being published. We are working on a fix.

**Comment by Linda-Editor** [comment]
@hyoshioka0128 TOC is now appearing in Japanese.
