### ISSUE TITLE
Documentation little bug

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#809]
A small inaccuracy. See the following link at **wdKeyCategoryMacro**. The description is 'Key is assigned to a'. Must be: 'Key is assigned to a macro.'

https://docs.microsoft.com/en-us/office/vba/api/word.wdkeycategory

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks for finding this. I've fixed this and changes will be live later today.
