### ISSUE TITLE
Documentation note

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#810]
Paragraphs have not been placed correctly and something has been overlooked.
https://docs.microsoft.com/en-us/office/vba/api/word.range.sort
Under Parameter > Name > SortFieldType3:

"Some of these constants may not be available to you, depending on the language support (U.S. English, for example) that you?ve selected or installed. The default value is **wdSortFieldAlphanumeric**. Some of these constants may not be available to you, depending on the language support (U.S. English, for example) that you have selected or installed."

Must be:
Some of these constants may not be available to you, depending on the language support (U.S. English, for example) that you have selected or installed. The default value is **wdSortFieldAlphanumeric**.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks for this fix. I fixed it, and changes will be live later today.
