### ISSUE TITLE
Missing constants

### ISSUE THREAD

**Issue by JamieG-UK** [MicrosoftDocs/VBA-Docs#819]
The following enumeration constants are available in O365 and I suspect have been there since PowerPoint 2007 when the new slide master model was introduced:

ppLayoutSectionHeader | 33 | Section header
ppLayoutComparison | 34 | Comparison
ppLayoutContentWithCaption | 35 | Content with caption
ppLayoutPictureWithCaption | 36 | Picture with caption

**Comment by Linda-Editor** [comment]
@JamieG-UK Thanks, Jamie. I just need the link to the page where you want me to add these...

**Comment by JamieG-UK** [comment]
Ah. Sorry Linda! As you can see I don't know how to use this tool and I'd assumed the Issue button was linked to the source page, which is here : https://docs.microsoft.com/en-us/office/vba/api/powerpoint.ppslidelayout

**Comment by Linda-Editor** [comment]
@JamieG-UK Thanks, Jamie. It used to be, but for VBA-Docs, it no longer is. I'll take care of this shortly. Changes should be live tomorrow.

**Comment by Linda-Editor** [comment]
Updated document. Changes will be live later today.
