### ISSUE TITLE
More importantly than the icon, this affects the behavior of the message box. 

### ISSUE THREAD

**Issue by geoffm** [MicrosoftDocs/VBA-Docs#82]
Stop doesn't let the user enter a non-valid entry. Warning does with a "continue?" query, no being the default. Information says it doesn't fit, with OK letting the user enter invalid info and being the default button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7b08587-cb4e-66f9-455e-387685c37b16
* Version Independent ID: a01f831b-81e7-4cce-1700-603d0cc32aa1
* Content: [XlDVAlertStyle Enumeration (Excel)](https://docs.microsoft.com/en-us/office/vba/api/excel.xldvalertstyle)
* Content Source: [api/Excel.XlDVAlertStyle.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Excel.XlDVAlertStyle.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
Hi @Geoffm is this a question or a comment? Please provide more information/context so that we can assist, if needed.
