### ISSUE TITLE
after exportFragment, the style for p.msoNormal is using default template font-family instead of default document font-family 

### ISSUE THREAD

**Issue by zhiqiang-liu** [MicrosoftDocs/VBA-Docs#827]
when use wdFormatFilteredHTML as export format, in the generated html file, font-family for p.msoNormal is the default **template** font-family, but not the default **document** font-family. But if we just save_as this export format, the p.msoNormal font-family is the default document font-family. 

To reproduce, 

1. create a document, remember the default font-family.
2. change the default font-family to other font, and set as default for this document only. 
3. use exportFragment to export some range. the style in the extracted html file will show the wrong font-family.

**Comment by Linda-Editor** [comment]
@zhiqiang-liu Could you please provide the link to the page in question? Thank you...

**Comment by zhiqiang-liu** [comment]
Sorry, maybe I should close this issue, i think this issue is not related to doc, but the programming. Sorry about it.
