### ISSUE TITLE
Tiny doc error

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#829]
In the next link:
https://docs.microsoft.com/nl-nl/office/vba/word/Concepts/Working-with-Word/working-with-building-blocks

The next comment is repeated twice: in the first code example and in the second. The first is correct, but in the second it isn't.
It's about the comment:

' Set the template to store the building block
Under the heading **Creating a Custom Building Block** this is correct, because the building block is created (the building block must be **stored**). This is the first code example.

However, the same comment is repeated under the heading **Accessing an Existing Building Block**. In this code example nothing is **created**, so there is nothing to be stored, but to be referred.

In the second code example should be the comment: **' Set the template where the building block is stored.**
For beginners the wrong text can be confusing.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks, Peter. I changed the second instance to this:

```vb
Sub GetExistingBuildingBlock() 
 
 Dim objTemplate As Template 
 Dim objBB As BuildingBlock 
 
 ' Set the template where the building block is stored 
 Set objTemplate = ActiveDocument.AttachedTemplate 
 
 ' Access the building block through the type and category 
 Set objBB = objTemplate.BuildingBlockTypes(wdTypeCustomHeaders) _ 
 .Categories("Book Titles").BuildingBlocks("Title") 
 
End Sub
```
However, I noticed a third instance under "Inserting a building block into a document". Should that be changed to something else as well?

**Comment by PeterVanLoosbroek** [comment]
That's correct Linda. The third I overlooked. But don't mistake. The comment in the second and third
' Set the template to store the building block
Should be replaced by:
**' Set the template where the building block is stored.**
In both case the building blocks exists already and don't have to store. It must be referred instead of stored.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks. Should it be "Set the template to where the building block is stored." (add "to")? It sounds funny the other way, but I want to make sure it doesn't change the meaning.

**Comment by PeterVanLoosbroek** [comment]
Yes, it can be due to my poor English. Added is better. It fits in better with the text of the first example. There is added, of course.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek What I mean is, instead of "Set the template where the building block is stored", it would be "Set the template to where the building block is stored". Is that okay? Or do you mean to say "Add the template to where the building block is stored"?

**Comment by PeterVanLoosbroek** [comment]
Linda, by the way, in a template you can store things… The comment (first example): 'Set the template to **store** the building block' also says that it is stored. Stored is correct.

**Comment by PeterVanLoosbroek** [comment]
Sorry, sorry... I mean indead: "Add the template to where the building block is stored"?

**Comment by Linda-Editor** [comment]
Okay, thanks! I'll change 2 and 3 to "Add the template to where the building block is stored."

**Comment by PeterVanLoosbroek** [comment]
Very well, Linda. Sorry for the inconvenience. I'll pay more attention next time.

**Comment by PeterVanLoosbroek** [comment]
Dear Linda,
I have checked my faulty English, but what I initially indicated is indeed correct.
' Set the template where the building block is stored.
I am 100% sure of this.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Okay, thanks. I'll update this tomorrow in case you change your mind again. ;-)

**Comment by PeterVanLoosbroek** [comment]
OK, I'll check it... :-)

**Comment by PeterVanLoosbroek** [comment]
Hi Linda,
I see that you have not closed this case yet. Yet I want to remind you for the **third** code example (I promised to check it):
Replace: ' Set the template to store the building block 
By:
**' Set the template where the building block is stored.**

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks for confirming, Peter. I've finished updating this doc; changes will be live later today.
