### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#831]
At the page https://docs.microsoft.com/en-us/office/vba/api/word.find.execute in the table Parameters > at Replace, the link WdReplace is incorrect.

Must be: https://docs.microsoft.com/en-us/office/vba/api/word.wdreplace

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Good catch! I updated the link. Changes will be live later today.
