### ISSUE TITLE
"Chrb 関数 $" needs to be replaced with "ChrB$"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#841]
https://docs.microsoft.com/ja-jp/office/vba/language/concepts/getting-started/returning-strings-from-functions

**Comment by OfficeGlobal** [comment]
related issue: #842 
___
Working on a fix

**Comment by OfficeGlobal** [comment]
Tracking: Bug 3272654

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 Article has been HumanTranslated and published live. The issue is fixed
