### ISSUE TITLE
"場合.そうしたら。。。他" needs to be replaced with "If...Then...Else" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#844]
https://docs.microsoft.com/ja-jp/office/vba/language/concepts/getting-started/writing-executable-statements

**Comment by OfficeGlobal** [comment]
related issue: #845 
___
Working on a fix

**Comment by OfficeGlobal** [comment]
Tracking Bug 3272654

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 Article has been HumanTransalted and published live, The issue is fixed
