### ISSUE TITLE
"[パブリック | 秘密][静的]" needs to be replaced with "[ Public | Private ] [ Static ]"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#846]
https://docs.microsoft.com/ja-jp/office/vba/language/concepts/getting-started/writing-a-property-procedure

**Comment by OfficeGlobal** [comment]
Working on a fix (Bug 3272654)

**Comment by OfficeGlobal** [comment]
Over-localized text fixed
