### ISSUE TITLE
Showing "**#**" (extra asterisks appears) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#848]
https://docs.microsoft.com/ja-jp/office/vba/language/concepts/getting-started/visual-basic-naming-rules

**Comment by OfficeGlobal** [comment]
related issue: #849 
___
Working on a fix (Bug 3242658)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 The article has been HumanTranslated and published live. Issue is fixed
