### ISSUE TITLE
"各...次 のステートメント" needs to be replaced with "For Each...Next ステートメント"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#850]
https://docs.microsoft.com/ja-jp/office/vba/language/concepts/getting-started/using-for-eachnext-statements

**Comment by OfficeGlobal** [comment]
related issues: #858 | #859 | #860 
___
Working on a fix (Bug 3242652)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 The article has been HumanTranslated and published live. Issue is fixed
