### ISSUE TITLE
Very tiny doc error

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#851]
In next link:
https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/mid-function
The second example contains too many quotes:
' Returns ""CdEf"
' Returns ""bC"
It should be:
' Returns "CdEf"
' Returns "bC"

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks, Peter. I fixed this one. Is there ever a time where double quotes are okay, such as in the following?

```vb
  Debug.Print Eval("StrComp(""Joe"",""joe"", 1)")
```
or

```vb
Private Sub cboMainCategory_NotInList(NewData As String, Response As Integer)

    On Error GoTo Error_Handler
    Dim intAnswer As Integer
    intAnswer = MsgBox("""" &amp; NewData &amp; """ is not an approved category. " &amp; vbcrlf _
        &amp; "Do you want to add it now?" _ vbYesNo + vbQuestion, "Invalid Category")

    Select Case intAnswer
        Case vbYes
            DoCmd.SetWarnings False
            DoCmd.RunSQL "INSERT INTO tlkpCategoryNotInList (Category) "
                &amp; _ "Select """ &amp; NewData &amp; """;"
            DoCmd.SetWarnings True
            Response = acDataErrAdded
        Case vbNo
            MsgBox "Please select an item from the list.", _
                vbExclamation + vbOKOnly, "Invalid Entry"
            Response = acDataErrContinue

    End Select

    Exit_Procedure:
        DoCmd.SetWarnings True
        Exit Sub

    Error_Handler:
        MsgBox Err.Number &amp; ", " &amp; Error Description
        Resume Exit_Procedure
        Resume

End Sub
```

**Comment by PeterVanLoosbroek** [comment]
No, the statement:
Debug.Print Eval("StrComp(""Joe"",""joe"", 1)")
contains errors...
1) Eval is unknown to me and is not a VBA function.
2) StrComp (a VBA function) should not between quotes.
3) ""Joe"" and ""joe"" are no valid strings. Valid strings are: "Joe", "joe" etc. Strings are between quotes, but not like this: ""blabla"". In the example I mentioned, the author means by ' Returns "CdEf", that a String is returned. What really is returned is: CdEf.

When I Iook to your next example and question, I noticed that &amp; is used. This is used in HTML docs; not in VBA. But I do understand the 'problem'. Someone is trying to work with characters.  To return a VALID character, you need to use a character of the Character sets (https://docs.microsoft.com/en-us/office/vba/language/reference/character-sets)
You can use the VBA function Chr to return a character of these Character sets. For example Chr(34) terurns the " character. This character is many times helpfull to connecting strings.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks for the feedback. So, basically, every time I see double quotes around a string, I should change them to single quotes, right? Regarding `&amp;`; this has been an issue, and we've made global changes to update these to just `&`, but maybe we missed some. I can also update these when I find them. Does this seem like the right course of action to take (in both instances)?

**Comment by PeterVanLoosbroek** [comment]
It depends on the situation. At the same time, I want to ensure that you do not make any wrong changes. That is why I will give a few examples.
Each variable has a default value. For example, for a Long (numeric), that is 0. The default value of a String is "" (**double quotes**). This: "" is a String without characters (or with a length zero). If the String has value, then the string is: "this is a valid String".
However, in certain cases, a String can also be placed between single quotes, as is often used in criteria. In the following example, the String Amsterdam is set as a criterion for the field City. In such a case, a String can therefore also be placed between single quotation marks. VBA now knows that Amsterdam is a String. This way is often used.

Example 1:
X = DLookup("City", "Places", "City='Amsterdam'")
The above method is often used because that is the easiest way. Despite this being sufficient for VBA, this is nevertheless a **bad way and a bad example**. The single quotation mark can itself be part of the String, and that can result in a problem, for example in the case of our beautiful city 's-Gravenhage.

Example 2:
This way is always good:
X = DLookup("City", "Places", "City=""Amsterdam""")
X = DLookup("City", "Places", "City=""'s-Gravenhage""")
In the wrong way (Example 1) there will be **no match** in the case of 's-Gravenhage. In Example 2 it is.
Now you know that many wrong examples are given, but I advise you to leave these unchanged because the VBA is technically correct. People also have their own responsibility in how they approach things.
The basis is that a value of a String type must always be passed between **double quotes**. Now we are at the beginning of our story, because "this is a valid String". If this convention is adhered to, it does not matter what the value is between the double quotes.

Example 3:
In the following example, it may become clearer how it works. strX has been declared as a **String**. The value is then placed between **double** quotes, exactly as it should be (therefore Example 1 is a bad example).
There are several ways to pass strings. The way is irrelevant, as long as the passed value, is passed (or combined) as a String as it should be.
    Dim X As Variant
    Dim strX As String
    
    strX = "'s-Gravenhage"
    X = DLookup("City", "Places", "City=""" & strX & """")

As you have seen, you cannot generally say that 'only this is good' or "only this is good". In these cases you have seen that these are both valid strings.
When you combine strings together, the same principle actually applies. "ABC" & " DEF" will result in ABC DEF. But "ABC" & '" DEF" is not going to work.
Working correctly with strings can sometimes be difficult. With code you have to pay attention and it has to be tested well before you change anything. And keep in mind that there are different situations. Do you ever have a dilemma, just ask me.
Hopefully this will help you with your decisions on what and how to correct text.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks so much for this explanation. I won't change anything, but if I ever see something strange, I'll be sure to ask you. And please continue to file issues as you find these yourself. Thanks, Peter!

**Comment by PeterVanLoosbroek** [comment]
Your welcome Lida.
