### ISSUE TITLE
"もし。。。そうしたら。。。Else ステートメント" needs to be replaced with "If...Then...Else ステートメント"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#852]
https://docs.microsoft.com/ja-jp/office/vba/language/reference/user-interface-help/ifthenelse-statement

**Comment by Linda-Editor** [comment]
@Soran-M There are several issues in VBA-Docs that loc should address. I'll assign them to you now to investigate. Thanks.

**Comment by OfficeGlobal** [comment]
Working on a fix (Bug 3272654)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 Article has been HumanTranslated and published live. The issue is fixed
