### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/VBA-Docs#857]
There is a broken link within an article.

**Repro steps**:
1. Go to https://docs.microsoft.com/en-us/office/vba/api/publisher.application.pointstotwips
2. Search for the "twips" link in the header
3. Click on the link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link redirects correctly

**GH article:**
https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Publisher.Application.PointsToTwips.md

**Comment by Linda-Editor** [comment]
@OfficeGlobal I fixed all the errors on this page; thanks for finding it; there were more errors than just a broken link. I also updated the sister page TwipsToPoints. Changes will go live later today.
