### ISSUE TITLE
"**します。そうしたら。。。Else** ステートメント" needs to be replaced with "If...Then...Else ステートメント"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#860]
https://docs.microsoft.com/ja-jp/office/vba/language/concepts/getting-started/using-for-eachnext-statements

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 The article has been HumanTranslated and published live. Issue is fixed
