### ISSUE TITLE
"ます。Loop ステートメント" needs to be replaced with "Do...Loop ステートメント"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#861]
https://docs.microsoft.com/ja-jp/office/vba/language/concepts/getting-started/using-doloop-statements

**Comment by OfficeGlobal** [comment]
working on a fix.

**Comment by OfficeGlobal** [comment]
Article has been HumanTranslated and published live. The issue is fixed
