### ISSUE TITLE
Cannot find certain pages due to truncation

### ISSUE THREAD

**Issue by MojoRobbins** [MicrosoftDocs/VBA-Docs#862]
VBA-Docs/api directory shows that 31k documents were truncated from the list.  How do we access these files?

Additionally, can you put a link to the DEPLOYED location of these documents on the ReadMe?

Thx,
Mojo

**Comment by Linda-Editor** [comment]
@MojoRobbins You mean they were truncated in the GitHub repo? To find a file in GitHub, choose the Find File button in the top navigation. I'll add this link to the live docs in the ReadMe: https://docs.microsoft.com/en-us/office/vba/api/overview/
