### ISSUE TITLE
Some inconsistences

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#863]
At the page: https://docs.microsoft.com/en-us/office/vba/word/concepts/miscellaneous/concepts-word-vba-reference

**Case 1**
The links on this page are in a different **order** than the order in the left menu.

**Case 2**
If you click the menu item **Working with Word**, you'll see some inconsistences. I noticed that changes are made from capital to lower case in the use of words and names. And sometimes it's hard to decide what to do. Therefore I believe you have a kind of system, some conventions to follow, to hold on (to prevent inconsistencies). Now I see some deviations, and I think you'd rather not have that. That is why I point out this.
So click the menu item **Working with Word**. Some words in some menu items have a capital letter, while in other menu items not. For example **Working with Document objects**. Plus, at that page the title is: **Working with Document Objects**. Here is Objects with a capital letter (like in the old days).
So, in the names of the menu items themselves, there is an inconsistency. And the titles of the pages do not match the names in the menu either. Regarding the use of capital letters.

**Case 3**
**Important.**
I can follow your thought when you see in a menu item 'objects' that you assume that other items must therefore be plural too, but that is not always the case. For example, there are more than on Range Objects, but there is only one Selection Object.
You don't have to understand these technical aspects, if you know where to look. So here's a tip. Just look in de address bar and watch the name for the file in the URL. You'll see that the title not should be: **Working with Selection objects**, but **Working with the Selection Object**. (Apart from the choice with or without capital letters). The same for the UndoRecord Object.

**Case 4**
Just see another one on this page: https://docs.microsoft.com/en-us/office/vba/word/concepts/objects-properties-methods/using-activex-controls-on-a-document-word
See the menu items there: it's not Use … but Using. See the page title ande the address bar.

Hope this is helpful to you.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Thanks so much for these editorial comments! Many of these inconsistencies are due to the fact that the old style was to capitalize everything and now it's not. So I think when I first started my editorial pass on this repo, I sentence-cased the TOC but have not had time to get to all the topic titles yet.  You're definitely right about the singular/plural thing. By the way, the Miscellaneous topics were ones we added later; if you know that one or more belongs in one of the other categories, please let me know. I'm slowly working through the repo page by page to fix formatting, etc. and am only on Access right now. But I'll make some of these updates (in the TOC) that you suggest right now. Thanks again for pointing this out.

**Comment by Linda-Editor** [comment]
Also, we often shorten the TOC title; by design it does not have to exactly match the page title. So that's why you see "Use" instead of "Using" and other variations like that.

**Comment by PeterVanLoosbroek** [comment]
Ok Linda. I understand. Case 4 is the most important. Hope you can correct that.

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek I just made the fixes that you requested in Case 1 and Case 3. FYI - pages I've edited in VBA-Docs will have a 2018 or 2019 date; all other pages show a June 2017 date; if you see the 2017 date on a page, you'll know that I haven't gotten to it yet, but I will eventually. ;-)

Thanks again for your input.

**Comment by Linda-Editor** [comment]
Changes will be live later today.

**Comment by PeterVanLoosbroek** [comment]
OK Linda, Understood. Good job!
