### ISSUE TITLE
Incorrect enums on page: en-us/office/vba/api/word.list.applylisttemplate 

### ISSUE THREAD

**Issue by performatech** [MicrosoftDocs/VBA-Docs#869]
On this page: https://docs.microsoft.com/en-us/office/vba/api/word.list.applylisttemplate the Method description for apply to uses incorrect enums.

### Current (incorrect):

 The portion of the list that the list template is to be applied to. Can be one of the following WdListApplyTo constants: **wdListSelection** , **wdListWholeList** , or **wdListThisPointForward**.

### Should be:

The portion of the list that the list template is to be applied to. Can be one of the following WdListApplyTo constants: **wdListApplyToSelection** , **wdListApplyToWholeList** , or **wdListApplyToThisPointForward**.

**Comment by Linda-Editor** [comment]
@performatech Thanks for catching this. I made the fix; changes will be live later today.
