### ISSUE TITLE
[LOC] "クリア、エラーの場合を発生させる" needs to be replaced with "Clear, Error, Raise"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#870]
https://docs.microsoft.com/ja-jp/office/vba/language/reference/user-interface-help/errors-keyword-summary

**Comment by OfficeGlobal** [comment]
related issue: #871 
___
Working on a fix

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 The article has been HumanTranslated and published live. Overlocalized text is fixed now

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #870
