### ISSUE TITLE
[LOC] "エラーの場合、再開" needs to be replaced with "On Error, Resume"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#871]
https://docs.microsoft.com/ja-jp/office/vba/language/reference/user-interface-help/errors-keyword-summary

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 The article has been HumanTranslated and published live. Overlocalized text is fixed now

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #871
