### ISSUE TITLE
 [LOC] "日付、時刻" needs to be replaced with "Date, Time"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#873]
https://docs.microsoft.com/ja-jp/office/vba/language/reference/user-interface-help/dates-and-times-keyword-summary

**Comment by OfficeGlobal** [comment]
working on a fix.

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 

Topic was human translated and the issue is fixed.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #873
