### ISSUE TITLE
[LOC] "datevalue 関数" needs to be replaced with "DateValue"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#878]
https://docs.microsoft.com/ja-jp/office/vba/language/reference/user-interface-help/dates-and-times-keyword-summary

**Comment by OfficeGlobal** [comment]
Working on a fix BUG 3256802

@Soran-M

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 

The topic was human translated and the issue is fixed.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #878
