### ISSUE TITLE
[LOC] "Dateadd 関数、 datediff 関数、日付構成要素" needs to be replaced with "DateAdd, DateDiff, DatePart"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#879]
https://docs.microsoft.com/ja-jp/office/vba/language/reference/user-interface-help/dates-and-times-keyword-summary

**Comment by OfficeGlobal** [comment]
Working on a fix BUG 3256802

@Soran-M

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 

Topic was human translated and the issue is fixed.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #879
