### ISSUE TITLE
[LOC] "Exp、ログ、 Sqr" needs to be replaced with "Exp, Log, Sqr"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#882]
https://docs.microsoft.com/ja-jp/office/vba/language/reference/user-interface-help/math-keyword-summary

**Comment by OfficeGlobal** [comment]
Working on a fix BUG 3256790.

@Soran-M

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 

Topic was human translated and the issue is fixed.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #882
