### ISSUE TITLE
[LOC] "AppActivate、シェル" needs to be replaced with "AppActivate, Shell"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#885]
https://docs.microsoft.com/ja-jp/office/vba/language/reference/user-interface-help/miscellaneous-keyword-summary

**Comment by OfficeGlobal** [comment]
Working on a fix BUG 3256768

@Soran-M

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 Hello,

Topic was human translated and the issue is fixed.

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #885
