### ISSUE TITLE
Some enum articles in russian localization are totally broken

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/VBA-Docs#888]
Examples:
https://docs.microsoft.com/ru-ru/office/vba/api/excel.xlfilteraction
https://docs.microsoft.com/ru-ru/office/vba/api/excel.xlfileformat

Translation is really bad, even by standards of machine translation. Some translated words are totally unrelated to source words, such as "24" translated as "открыт". Some are translated into nonsence, like "Кслксв". Looks like a bug in machine translator.

**Comment by OfficeGlobal** [comment]
Working on a fix BUG 3256754.

@Soran-M

**Comment by OfficeGlobal** [comment]
The topics human translated and published to the live site.
