### ISSUE TITLE
Missing quotations break code example on dict page

### ISSUE THREAD

**Issue by gidven** [MicrosoftDocs/VBA-Docs#890]
VBA-Docs/Language/Reference/User-Interface-Help/dictionary-object.md

The sample code includes the following line:

```Set d = CreateObject(Scripting.Dictionary)```

Which should be:

```Set d = CreateObject("Scripting.Dictionary")```

**Comment by gidven** [comment]
Direct link to repo page:
https://github.com/MicrosoftDocs/VBA-Docs/blob/master/Language/Reference/User-Interface-Help/dictionary-object.md

**Comment by Linda-Editor** [comment]
@gidven Thanks for this contribution. I've made the fix; changes will be live later today. :-)
