### ISSUE TITLE
[LOC] "コマンド" needs to be replaced with "Command"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#892]
https://docs.microsoft.com/ja-jp/office/vba/language/reference/user-interface-help/miscellaneous-keyword-summary

related issue:#885

**Comment by OfficeGlobal** [comment]
Working on a fix (Bug 3272654)

**Comment by OfficeGlobal** [comment]
Tracking Bug 3272654

**Comment by hyoshioka0128** [comment]
@OfficeGlobal Thanks.
Close #892

**Comment by Linda-Editor** [comment]
@hyoshioka0128 This is not a closed issue, so I'm reopening it. Please do not close the issues. Our team will handle that when they are fixed.

**Comment by hyoshioka0128** [comment]
I understand.

**Comment by OfficeGlobal** [comment]
@Linda-Editor the over-localized text was already fixed

@hyoshioka0128 info from Linda is related only for VBA project at the moment
