### ISSUE TITLE
Is "GetImageMso" obsolete ?

### ISSUE THREAD

**Issue by VeV-HDT** [MicrosoftDocs/VBA-Docs#901]
https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Office.CommandBars.GetImageMso.md

GetImageMso seems to always return the dark themed image in the latest version of Office 365/2019. Maybe this should be reflected in the documentation, flag the method as obsolete or raise a bug to get it fixed.

**Comment by VeV-HDT** [comment]
Method was working fine until the latest Icon re-design. Ribbon was introduced in office 2007 so this looks more like an issue in the new icon pipeline. 
https://support.office.com/en-gb/article/your-ribbon-icons-have-a-new-look-c6bc4cd8-d151-41d3-8276-fc7c9975eb79

**Comment by Linda-Editor** [comment]
@VeV-HDT For now, I added this note to the page to inform users who may be experiencing the same issue: 

> [!NOTE] 
> If **GetImageMso** doesn't appear as expected, it may be due to the recent icon redesign. For more information, see [Your ribbon icons have a new look](https://support.office.com/article/your-ribbon-icons-have-a-new-look-c6bc4cd8-d151-41d3-8276-fc7c9975eb79).
