### ISSUE TITLE
Showing "application オブジェクト****" (extra asterisks appears)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#921]
https://docs.microsoft.com/ja-jp/office/vba/api/publisher.application

**Comment by OfficeGlobal** [comment]
related issue: #922

**Comment by OfficeGlobal** [comment]
Working on a fix: Bug 3290847

**Comment by OfficeGlobal** [comment]
other logged issues: #936 | #937 | #926 | #927 | #928 | #929 | #930 | #931 | #932 | #933 | #934 | #935

**Comment by OfficeGlobal** [comment]
Article has been HumanTranslated and published live. Issues fixed
