### ISSUE TITLE
MsoTriState is clearly not a tri-state value

### ISSUE THREAD

**Issue by poizan42** [MicrosoftDocs/VBA-Docs#93]
(Copying from https://github.com/OfficeDev/VBA-content/issues/586)

A lot can be said about this abomination, but the documentation right now states "Specifies a tri-state value.", which is factually wrong since only msoTrue and msoFalse are supported values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8289e5d1-1e28-577d-51f1-88dc22426d68
* Version Independent ID: 1adb3b14-876e-5fbe-9964-fca10c990c6e
* Content: [MsoTriState Enumeration (Office)](https://docs.microsoft.com/en-us/office/vba/api/office.msotristate)
* Content Source: [api/Office.MsoTriState.md](https://github.com/MicrosoftDocs/VBA-Docs/blob/master/api/Office.MsoTriState.md)
* Product: **office**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by poizan42** [comment]
Comment from https://github.com/OfficeDev/VBA-content/issues/586#issuecomment-404699013 by @lindalu-MSFT

> @poizan42 Sadly, you are 100% correct. In this case, there are only two logical meanings expressed by MsoTriState (tri, meaning 3, right?) which actually has 5 values! Only 2 of them are supported, msoFalse and msoTrue. I wish I could tell you that someone will take ownership and fix this! I will keep this issue open and at least see if I can find out WHY it's like this and hopefully improve upon the documentation. Thanks for making my day. lindalu

**Comment by lindalu-MSFT** [comment]
I don't think this will be changed, so I'm closing this issue. I asked around and was told this was used over ten years ago to return more than two values. Currently, though, it behaves like a Boolean and only has two possible values, True or False. 
The binary representation (assuming here an 8 bit value) for zero is 0000 0000, for -1 it's 1111 1111 and for 1 is 0000 0001. In some cases it has an advantage to use for an TRUE the -1. But other programmers are preferring an +1 for the TRUE. So Microsoft decided to define:
  msoFalse = 0
  msoTrue  = -1
  msoCTrue = +1
In MsoTriState, msoTrue and msoCTrue are both accepted and interpreted as an TRUE but in some cases, the value represented by msoCTrue may be unexpected and not work as expected and is therefore not supported. 
Office added:
  msoTristateMixed = -2
  msoTriStateToggle = -3 
(E.g. for for the property "CheckBox.Checked" with the TriState behavior.) These values may or may not work as expected and are therefore not supported. 
So my best answer, originally, years ago, the msoTriState did have three answers but only two meanings.

**Comment by lindalu-MSFT** [comment]
p.s. When I asked one of the programmers I spoke with what the C in msoCTrue stands for, he paused a sec and said "confusing!"

**Comment by poizan42** [comment]
I'm pretty sure the C in CTrue refers to the C programming language, where true is usually represented by the value 1.

I still think the documentation could be reformulated a bit, either the tristate values are supported or the claim of it representing a tri-state value is wrong.
