### ISSUE TITLE
[LOC] title:"調整オブジェクト (Publisher)" needs to be replaced with "Adjustments オブジェクト (Publisher)"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#938]
https://docs.microsoft.com/ja-jp/office/vba/api/publisher.adjustments
related issues: #914 | #915 | #916 | #917 | #918

**Comment by OfficeGlobal** [comment]
Working on a fix: Bug 3290847

**Comment by OfficeGlobal** [comment]
Article has been HumanTranslated and published live
