### ISSUE TITLE
Showing "**put**" (extra asterisks appears) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/VBA-Docs#950]
https://docs.microsoft.com/ja-jp/office/vba/access/concepts/miscellaneous/ado-for-visual-c-plus-plus-syntax-index-for-com

**Comment by Linda-Editor** [comment]
@hyoshioka0128 Hi Hiroshi, when you log these issues, is it possible for you to add an Assignee? If so, please add "OfficeGlobal" as an assignee for each issue that you log. Thank you.

**Comment by hyoshioka0128** [comment]
@Linda-Editor I understand. (I'm Poor English)
However, Assignees are not displayed at the stage of isssue.
![190412_issue](https://user-images.githubusercontent.com/40815708/56027245-a8118c80-5d50-11e9-9f20-3e16a300cf98.png)
I'm investigating if it can not be done by another method.

**Comment by Linda-Editor** [comment]
@hyoshioka0128 Are you not able to see this in the right navigation?

![image](https://user-images.githubusercontent.com/27295799/56040363-158ad200-5ceb-11e9-8283-41fef17f01b9.png)

**Comment by hyoshioka0128** [comment]
@Linda-Editor As in the previous screen shot, the right navigation  is not displayed.
Even after pressing 'Submit new issue' button, gear button does not appear.
