### ISSUE TITLE
Tiny doc error

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#954]
Page: https://docs.microsoft.com/en-us/office/vba/word/concepts/miscellaneous/storing-values-when-a-macro-ends
Under **Document properties**, third paragraph:
"Use the **CustomDocumentProperties**property (…)", should be: "(…) **CustomDocumentProperties** property (…)"

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Fixed. Changes will be live Monday night.
