### ISSUE TITLE
Doc error

### ISSUE THREAD

**Issue by PeterVanLoosbroek** [MicrosoftDocs/VBA-Docs#955]
Page: https://docs.microsoft.com/en-us/office/vba/api/word.document.customdocumentproperties
Under Example:
"This example inserts a list of custom built-in properties at the end of the active document."
There are no 'custom built-in properties'. But there are BuiltInDocumentProperties en CustomDocumentProperties.
Should be: "This example inserts a list of custom document properties at the end of the active document."
The same with the sentence at the second example:
"This example adds a custom built-in property to Sales.doc."
Should be: "This example adds a custom document property to Sales.doc."

**Comment by Linda-Editor** [comment]
@PeterVanLoosbroek Fixed. Changes will be live Monday night.
