### ISSUE TITLE
"About the author"

### ISSUE THREAD

**Issue by retailcoder** [MicrosoftDocs/VBA-Docs#972]
I'm noticing a number of .md files include an "About the Author" section that sometimes contains the original author's bio, or links to 3rd-party publishers' websites: my perception is that all contributors of a .md file are listed at such on every file, each linking to their respective GitHub profile, where contributors' bio and affiliations belong.

Is it ok to comment-out these sections in files I come across as I update code samples?

**Comment by Linda-Editor** [comment]
@retailcoder Sure. When I find these in files, I'm actually removing all of these sections because most are over 10 years old. But feel free to comment them out, and I'll remove them when I get to them. Thanks.
