### ISSUE TITLE
Can I create an ISSUE to notify ppl that in the upcoming weeks I plan to make a PR re. certain documentation?

### ISSUE THREAD

**Issue by MarkFern** [MicrosoftDocs/VBA-Docs#985]
Hello.

I've been making several commits over the course of days & weeks in my own fork of these docs.

Can I create an ISSUE to notify people that in the upcoming weeks I plan to make a PR regarding certain documentation? I believe this would help documentation collaboration.

Thanks.

**Comment by Linda-Editor** [comment]
@MarkFern  Sure. It's worth a try. Just be clear about what you're doing (keep it simple). :-)
