### ISSUE TITLE
Example missing hiragana text?

### ISSUE THREAD

**Issue by Linda-Editor** [MicrosoftDocs/VBA-Docs#995]
In the Example on this page, the strings are rendering as question marks: https://docs.microsoft.com/ja-jp/office/vba/api/excel.phonetics.add

```vb
ActiveCell.FormulaR1C1 = "?????????" 
ActiveCell.Phonetics.Add Start:=1, Length:=3, Text:="??????" 
ActiveCell.Phonetics.Add Start:=4, Length:=3, Text:="????" 
ActiveCell.Phonetics.CharacterType = xlHiragana 
ActiveCell.Phonetics.Font.Color = vbBlue 
ActiveCell.Phonetics.Visible = True
```

I've noticed that sometimes in the migration from the old authoring systems, certain characters have come across as question marks, and I'm just wondering if these were supposed to be hiragana characters. The same is true on the English page.

**Comment by Linda-Editor** [comment]
@hyoshioka0128 can you look into this?

**Comment by Linda-Editor** [comment]
I just found similar text on the [Length property](https://docs.microsoft.com/en-us/office/vba/api/excel.phonetics.length); can I just substitute that text (kanji, hiragana, and katakana) on the Add method page?

```vb
ActiveCell.FormulaR1C1 = "東京都渋谷区代々木" 
ActiveCell.Phonetics.Add Start:=1, Length:=3, Text:="トウキョウト" 
ActiveCell.Phonetics.Add Start:=4, Length:=3, Text:="シブヤク" 
MsgBox ActiveCell.Phonetics(2).Length
```

**Comment by Linda-Editor** [comment]
For now, I'm going to add the Japanese text in place of the question marks on the en-us page. Let me know if you think I should do otherwise. Please fix this on the ja-jp page.

**Comment by hyoshioka0128** [comment]
I'm poor English.(I always translate using bing translator.)

#1
 Q Can you substitute it?
  Quesutin text:  "https://docs.microsoft.com/ja-jp/office/vba/api/excel.phonetics.add"
  Substitute text:"https://docs.microsoft.com/en-us/office/vba/api/excel.phonetics.length"

 A Can be substituted
  similar text:   "https://docs.microsoft.com/ja-jp/office/vba/api/excel.phonetics.start"

#2 I noticed that I made additional corrections
 構文
  式。追加( _Start_ , _Length_ , _Text_ )

 (1)追加 → Add
 (2)_Start_ → "_" is italic?

**Comment by hyoshioka0128** [comment]
#3 <superfluity>It is not directly related
 The Microsoft headquarters in Japan is moving from "東京都渋谷区代々木" to "東京都港区港南" in 2011."
 "https://ja.wikipedia.org/wiki/%E3%83%9E%E3%82%A4%E3%82%AF%E3%83%AD%E3%82%BD%E3%83%95%E3%83%88#%E6%97%A5%E6%9C%AC%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E3%83%9E%E3%82%A4%E3%82%AF%E3%83%AD%E3%82%BD%E3%83%95%E3%83%88"

 If it matches the current head office, it will be as follows.
  ActiveCell.FormulaR1C1 = "東京都港区港南" 
  ActiveCell.Phonetics.Add Start:=1, Length:=3, Text:="トウキョウト" 
  ActiveCell.Phonetics.Add Start:=4, Length:=2, Text:="ミナトク" 
  MsgBox ActiveCell.Phonetics(2).Length

**Comment by hyoshioka0128** [comment]
@Linda-Editor I'm poor English.(I always translate using bing translator.)

#1
 Q Can you substitute it?
  Quesutin text:  "https://docs.microsoft.com/ja-jp/office/vba/api/excel.phonetics.add"
  Substitute text:"https://docs.microsoft.com/en-us/office/vba/api/excel.phonetics.length"

 A Can be substituted
  similar text:   "https://docs.microsoft.com/ja-jp/office/vba/api/excel.phonetics.start"

#2 I noticed that I made additional corrections
 構文
  式。追加( _Start_ , _Length_ , _Text_ )

 (1)追加 → Add
 (2)_Start_ → "_" is italic?

**Comment by hyoshioka0128** [comment]
@Linda-Editor
#3 <superfluity>It is not directly related
 The Microsoft headquarters in Japan is moving from "東京都渋谷区代々木" to "東京都港区港南" in 2011."
 "https://ja.wikipedia.org/wiki/%E3%83%9E%E3%82%A4%E3%82%AF%E3%83%AD%E3%82%BD%E3%83%95%E3%83%88#%E6%97%A5%E6%9C%AC%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E3%83%9E%E3%82%A4%E3%82%AF%E3%83%AD%E3%82%BD%E3%83%95%E3%83%88"

 If it matches the current head office, it will be as follows.
  ActiveCell.FormulaR1C1 = "東京都港区港南" 
  ActiveCell.Phonetics.Add Start:=1, Length:=3, Text:="トウキョウト" 
  ActiveCell.Phonetics.Add Start:=4, Length:=2, Text:="ミナトク" 
  MsgBox ActiveCell.Phonetics(2).Length

**Comment by Linda-Editor** [comment]
@hyoshioka0128 Thanks for your response. However, this doesn't have to have the new office information; it's just an example. So I'm going to leave it as is. ども ありがと ございます
