### ISSUE TITLE
outlook.contactitem.close(even) 

### ISSUE THREAD

**Issue by lindalu-MSFT** [MicrosoftDocs/VBA-Docs#997]
Hi @linda-editor! This came in via Feedback. The only way I know how to assign it to you is to open this issue in VBA-docs, then close the other one:
https://github.com/MicrosoftDocs/feedback/issues/1416#event-2318232357

Bug:
Link to article:
Tell us where exactly a problem occurs.
https://docs.microsoft.com/en-us/office/vba/api/Outlook.ContactItem.Close(method)
https://docs.microsoft.com/en-us/office/vba/api/outlook.contactitem.close(even)

Problem:
What's wrong with the article?

There's actually no such outlook.contactitem.close(even) in c# (vs 2017 ) . only Close (method) .

More info:
Thank you for creating the issue! One of our team members will get back to you shortly with additional information.

From submitter: @kerwinxu

public interface ContactItem : _ContactItem, ItemEvents_10_Event
but _ContactItem interface and ItemEvents_10_Event interface have the same name: Close

public interface _ContactItem
{
[DispId(61475)]
void Close(OlInspectorClose SaveMode);
}
public interface ItemEvents_10_Event
{
event ItemEvents_10_CloseEventHandler Close;
}

I found the solution , please put the below example into the document .

ItemEvents_10_Event appointmentItemEvent = (ItemEvents_10_Event)outlook_contact;
appointmentItemEvent.Close += AppointmentItemEvent_Close;

reference:
http://www.outlookcode.com/threads.aspx?forumid=2&messageid=23368

**Comment by Linda-Editor** [comment]
Original Issue in other repo: https://github.com/MicrosoftDocs/VBA-Docs/issues/997

**Comment by Linda-Editor** [comment]
Original issue in other repo: https://github.com/MicrosoftDocs/VBA-Docs/issues/997

**Comment by Linda-Editor** [comment]
@kerwinxu: Which document do you want this code added to? The **Close** method or the **Close** event? And is this C# code or VB code?

```
ItemEvents_10_Event appointmentItemEvent = (ItemEvents_10_Event)outlook_contact;
appointmentItemEvent.Close += AppointmentItemEvent_Close;
```

**Comment by Linda-Editor** [comment]
Also, please include an introductory sentence for this example.

**Comment by lindalu-MSFT** [comment]
Finally added this fix and update to the docs. Thanks, lindalu
